(() => {
  'use strict';
  const $ = selector => document.querySelector(selector);
  const escape = value => String(value).replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const caseData = [
    {id:'t0',title:'Normal blood',zh:'外周血（正常）',time:'T0 · Baseline',type:'Matched normal',site:'Peripheral blood',context:'用于区分 germline 与 somatic；不是 tumor tissue 的健康对照。',chain:[['DNA','Germline reference'],['RNA','Not profiled'],['Protein','Not profiled'],['Cell state','Blood cells'],['Tissue','Peripheral blood'],['Outcome','Baseline']],summary:'这份样本的主要工作是提供 matched-normal DNA。它不能回答原发肿瘤的 expression、protein activity 或 microenvironment。',boundary:{ok:['可帮助排除 inherited variant','可识别 normal genotype'],warn:['不能代表正常皮肤组织','不能作为 tumor RNA 对照']},variants:[['BRAF p.V600E',118,0,'0.00',2],['NRAS p.Q61K',104,0,'0.00',2]],steps:['确认 sample 是 blood-derived normal，而不是邻近组织。','0 ALT read 支持该位点在这份样本未检出，但仍受 depth 与 caller limit 约束。','若 tumor 中出现 ALT，可作为 somatic 候选；还需排除 artifact。'],answer:'Matched normal 未观察到这两个 ALT，而 tumor specimen 中可见；这支持 somatic classification，但不单独证明功能。'},
    {id:'t1',title:'Primary tumor',zh:'原发肿瘤',time:'T1 · Diagnosis',type:'Solid tumor biopsy',site:'Skin lesion',context:'Treatment-naive；估计 tumor purity 约 70%，bulk DNA/RNA/protein 混合多种细胞。',chain:[['DNA','BRAF variant'],['RNA','MAPK target ↑'],['Protein','pERK high'],['Cell state','Proliferative'],['Tissue','Immune-cold region'],['Outcome','Baseline disease']],summary:'多层结果与 MAPK pathway activity 相容，但 bulk 数据无法证明每层变化来自同一细胞，也不能仅凭相关链条宣布 BRAF 是所有下游状态的唯一原因。',boundary:{ok:['可报告 BRAF VAF 与 local CN','可描述 target RNA 和 pERK 同时偏高','可提出 pathway-dependence hypothesis'],warn:['不能把 VAF 当 tumor-cell fraction','不能从 bulk 共现证明单细胞内因果','需要 perturbation/rescue 测必要性']},variants:[['BRAF p.V600E',78,34,'0.30',2],['NRAS p.Q61K',103,1,'0.01',2]],steps:['先算 BRAF VAF：34 / (78 + 34) ≈ 0.30。','把 purity≈70% 与 total CN=2 放进模型；0.30 与 clonal heterozygous mutation 相容，但不是唯一解。','NRAS 的 1 条 ALT read 接近 error/low-support 区，不能称为 resistant clone。'],answer:'在 purity 与 diploid 假设下，BRAF p.V600E 的 0.30 VAF 与较大 tumor clone 中的 heterozygous somatic event 相容；clone fraction 仍需 allele-specific CNV、depth uncertainty 与更多位点联合估计。'},
    {id:'t2',title:'On-treatment biopsy',zh:'治疗中活检',time:'T2 · Day 14',type:'Core biopsy',site:'Same target lesion',context:'BRAF inhibitor 后 14 天；取样位置接近但并非 T1 的同一组细胞。',chain:[['DNA','BRAF persists'],['RNA','MAPK target ↓'],['Protein','pERK low'],['Cell state','Cycling ↓'],['Tissue','CD8 proximity ↑'],['Outcome','Partial response']],summary:'DNA driver 仍在，但 pathway activity 与 proliferation 下降。这个时间顺序支持 drug engagement；CD8 proximity 上升与 response 同时发生，尚不能证明它介导了 response。',boundary:{ok:['可比较同一患者的纵向方向','可把 DNA persistence 与 activity change 分开','可提出 immune recruitment hypothesis'],warn:['不同 biopsy 有 spatial sampling 差异','单一患者不能估计群体 treatment effect','on-treatment biomarker 不能冒充 pretreatment predictor']},variants:[['BRAF p.V600E',64,31,'0.33',2],['NRAS p.Q61K',91,1,'0.01',2]],steps:['BRAF VAF 与 T1 接近，不代表 tumor cell 数量没有下降；purity 与 sampling 都可改变分母。','pERK 与 cycling marker 下降是不同 assay 的 observation。','治疗发生在变化之前增加机制可信度，但仍需对照、剂量关系或 ex vivo perturbation。'],answer:'治疗后 BRAF variant 仍可检出，同时 pERK 与 proliferation marker 下降，支持 pathway 被药物抑制；不能仅凭这一位患者确定临床 response 完全由该机制造成。'},
    {id:'t3',title:'Resistant lesion',zh:'耐药病灶',time:'T3 · Progression',type:'Progression biopsy',site:'New metastatic lesion',context:'影像学进展时的新病灶；与 T1/T2 不同 anatomical site，purity 约 60%。',chain:[['DNA','NRAS emerges'],['RNA','MAPK target ↑'],['Protein','pERK rebounds'],['Cell state','Cycling resumes'],['Tissue','Lactate ↑ / CD8 distant'],['Outcome','Progression']],summary:'新出现的 NRAS signal、MAPK reactivation 与 progression 构成 resistance hypothesis。不同病灶与时间共同变化，仍需证明 NRAS event 对 rebound 必要或充分。',boundary:{ok:['可描述 acquired candidate event','可连接 rebound 与 progression 的时间关系','可设计 NRAS perturbation/rescue'],warn:['新 lesion 不等于原 lesion 的直接后代已被证明','lactate abundance 不等于 flux','immune exclusion 需要 spatial 与 functional evidence']},variants:[['BRAF p.V600E',71,29,'0.29',2],['NRAS p.Q61K',82,18,'0.18',2]],steps:['BRAF 继续存在，说明 resistant population 与原 driver 相容。','NRAS ALT support 从接近零升到 18 reads；先确认 matched normal、strand/batch 与 independent validation。','0.18 VAF 与 purity、CN、subclone fraction 共同决定；不能直接说 18% cancer cell。'],answer:'Progression lesion 中出现有独立 read support 的 NRAS p.Q61K，同时 pERK rebound；这支持 acquired resistance candidate。证明 mechanism 仍需 clone phasing/lineage、functional perturbation 与可重复 cohort evidence。'}
  ];
  const assays = {
    dna:{label:'DNA-seq',title:'Variant-supporting reads',visual:'table',rows:[['Locus','REF','ALT','Depth'],['BRAF V600E','71','29','100'],['NRAS Q61K','82','18','100'],['Matched normal NRAS','104','0','104']],reading:[['Direct observation','经过 alignment/filter 后支持 REF 或 ALT 的 reads。'],['Processed value','VAF、variant call 与 CN segment 都是模型输出。'],['Cannot conclude','ALT fraction 不能直接当作 mutated-cell fraction。']],question:'哪一句最贴近 DNA-seq 的直接 observation？',options:[['样本中 18% 的癌细胞携带 NRAS mutation',false],['100 条通过筛选的 reads 中有 18 条支持 NRAS ALT',true],['NRAS mutation 已被证明导致耐药',false]],feedback:'先描述 read support。细胞比例与耐药机制都需要更多模型或实验。'},
    rna:{label:'RNA-seq',title:'Expression table',visual:'table',rows:[['Feature','Raw count','TPM','Note'],['DUSP6','842','31.2','MAPK-responsive'],['MKI67','615','22.4','cycling-associated'],['CD8A','126','4.1','mixture-sensitive']],reading:[['Direct observation','reads 经 reference、annotation 与 counting pipeline 得到 feature count。'],['Processed value','TPM 使用 library 内 feature abundance 与长度进行缩放。'],['Cannot conclude','RNA 高不等于 protein active，也不说明来自哪种 cell。']],question:'CD8A TPM 较低，最稳妥的第一句是什么？',options:[['这个 bulk specimen 中 CD8A-associated RNA signal 较低',true],['患者没有 CD8 T cell',false],['CD8 T cell 一定已经 exhausted',false]],feedback:'Bulk RNA signal同时受 cell abundance 和 per-cell expression 影响；absence 与 functional state 需要其他证据。'},
    western:{label:'Western blot',title:'Protein bands',visual:'bands',rows:[['pERK',88],['total ERK',54],['ACTB loading',58],['pAKT',33]],reading:[['Direct observation','在给定 exposure 与 antibody 条件下的 band intensity。'],['Processed value','background correction 与 loading normalization 后的相对 signal。'],['Cannot conclude','单条 band 不能自动证明 pathway cause 或 absolute protein molecules。']],question:'解释 pERK band 前最重要的检查之一是什么？',options:[['是否有 loading control、linear exposure 与 biological replicate',true],['band 最黑所以一定是最重要 pathway',false],['只要 antibody 名称正确就不需要 negative control',false]],feedback:'Band intensity 依赖 loading、transfer、antibody specificity 与 exposure；先验证 signal 是否在线性且可比较。'},
    spatial:{label:'Spatial',title:'Cell-neighborhood summary',visual:'table',rows:[['Region','Tumor cells','CD8 cells','Median distance'],['Core','214','9','78 µm'],['Edge','132','31','24 µm'],['Stroma','18','47','19 µm']],reading:[['Direct observation','image/transcript coordinates 经 segmentation 与 cell typing 后形成的位置记录。'],['Processed value','distance、neighborhood 与 cell label 依赖 boundary、registration 和 marker model。'],['Cannot conclude','表达 ligand/receptor 且相邻，不等于发生 binding 或 downstream response。']],question:'tumor core 的 CD8 距离较远，下一步最需要核对什么？',options:[['segmentation、registration、region definition 与 patient-level replicate',true],['立刻宣布 tumor 通过某 ligand 排斥 T cell',false],['把每个 cell 当独立患者增加 n',false]],feedback:'空间关系先受测量与层级结构约束；机制还需要特定 perturbation 或功能证据。'}
  };
  const hypotheses = [
    {id:'h1',title:'NRAS drives MAPK rebound',short:'Resistance genetics',evidence:[['DNA','Progression lesion 出现 NRAS p.Q61K read support。','support'],['Protein','pERK 在 progression 时 rebound。','compatible'],['Timing','candidate event 与 progression 同时出现。','compatible'],['Causality','尚无 NRAS-specific perturbation 或 rescue。','missing']],next:['在 resistant cells 中抑制 mutant NRAS，观察 pERK 与 growth 是否下降。','在 sensitive background 引入 variant，测试是否足以产生 rebound。','用多区域/单细胞或 read-backed phasing 支持 clone lineage。']},
    {id:'h2',title:'Lactate contributes to immune exclusion',short:'Metabolism × immunity',evidence:[['Metabolite','Progression specimen 的 lactate abundance 较高。','compatible'],['Spatial','CD8 cell 与 tumor core 距离增大。','compatible'],['Flux','没有 isotope tracing 证明 lactate production/consumption route。','missing'],['Function','没有改变 lactate 后观察 T-cell function。','missing']],next:['用 isotope tracing 或 time-resolved media assay 估计 flux。','控制 pH、oxygen 与 cell density 后干预 lactate transport。','测 target-specific T-cell killing，而不只看 CD8 marker。']},
    {id:'h3',title:'Treatment recruits functional CD8 T cells',short:'Response immunology',evidence:[['Spatial','T2 中 CD8 proximity 上升。','support'],['Clinical','同时观察到 partial response。','compatible'],['Function','没有 antigen-specific killing 或 degranulation assay。','missing'],['Design','只有一位患者且 biopsy location 不同。','missing']],next:['增加患者级 replicate 与 pretreatment/on-treatment paired design。','结合 TCR clonality、tetramer 或 killing assay。','区分 cell number、activation、clonality 与 location。']}
  ];
  const claims = [
    {text:'Progression specimen 中 NRAS ALT reads 为 18/100。',answer:'observation',why:'这是明确限定 specimen、assay 与分母的 read-level observation。'},
    {text:'NRAS candidate event 与 pERK rebound 在 progression specimen 中同时出现。',answer:'association',why:'两个测量共同变化构成 association；尚未改变 NRAS 来检验必要性。'},
    {text:'在 resistant cells 中抑制 mutant NRAS 后，pERK 与 growth 恢复到 sensitive range；重新表达 resistant NRAS 可 rescue。',answer:'mechanism',why:'perturbation 与 rescue 更接近 causal mechanism，但仍需检查 off-target 与 model context。'},
    {text:'Pretreatment NRAS subclone score 将预测下一批患者的早期 resistance。',answer:'prediction',why:'这是待外部 cohort 检验的 predictive claim，不因 training accuracy 高就成为 mechanism。'}
  ];
  let activeTime = 1, activeAssay = 'dna', activeHypothesis = 0, dynamicsView = 'trajectory';
  function renderTimeline(){
    $('#timepoint-controls').innerHTML=caseData.map((item,index)=>`<button type="button" data-time="${index}" aria-pressed="${index===activeTime}"><b>${escape(item.title)}</b><span>${escape(item.zh)}</span><small>${escape(item.time)}</small></button>`).join('');
  }
  function renderCase(){
    const item=caseData[activeTime];
    $('#specimen-context').innerHTML=`<dl><div><dt>TIMEPOINT</dt><dd>${escape(item.time)}</dd></div><div><dt>SPECIMEN</dt><dd>${escape(item.type)}</dd></div><div><dt>SITE</dt><dd>${escape(item.site)}</dd></div><div><dt>WHY IT MATTERS</dt><dd>${escape(item.context)}</dd></div></dl>`;
    $('#evidence-chain').innerHTML=item.chain.map(([name,value])=>`<div class="pl-chain-node"><b>${escape(name)}</b><span>${escape(value)}</span><strong>${value==='Not profiled'?'not measured':'measured layer'}</strong></div>`).join('');
    $('#chain-summary').textContent=item.summary;
    $('#inference-boundary').innerHTML=`<ul>${item.boundary.ok.map(text=>`<li class="ok">${escape(text)}</li>`).join('')}${item.boundary.warn.map(text=>`<li class="warn">${escape(text)}</li>`).join('')}</ul><p>“Can infer” 仍是受 specimen、assay 与设计限制的有限结论，不是最终真相。</p>`;
    $('#variant-table').innerHTML=item.variants.map(row=>`<tr>${row.map(value=>`<td>${escape(value)}</td>`).join('')}</tr>`).join('');
    $('#genetics-steps').innerHTML=item.steps.map(text=>`<li>${escape(text)}</li>`).join('');
    $('#genetics-answer').textContent=item.answer;
  }
  function assayVisual(assay){
    if(assay.visual==='bands') return assay.rows.map(([label,value])=>`<div class="pl-band"><span>${escape(label)}</span><div><i style="width:${value}%"></i></div><b>${value}</b></div>`).join('')+'<p class="pl-small">Relative intensity · teaching values; exposure and loading matter.</p>';
    return `<table class="pl-raw-table">${assay.rows.map((row,index)=>`<tr>${row.map(cell=>index===0?`<th>${escape(cell)}</th>`:`<td>${escape(cell)}</td>`).join('')}</tr>`).join('')}</table>`;
  }
  function renderAssay(){
    $('#assay-tabs').innerHTML=Object.entries(assays).map(([id,a])=>`<button type="button" role="tab" data-assay="${id}" aria-controls="assay-panel" aria-selected="${id===activeAssay}" tabindex="${id===activeAssay?'0':'-1'}">${escape(a.label)}</button>`).join('');
    const assay=assays[activeAssay];$('#assay-panel-title').textContent=assay.title;$('#assay-visual').innerHTML=assayVisual(assay);
    $('#assay-reading').innerHTML=assay.reading.map(([term,text])=>`<div><dt>${escape(term)}</dt><dd>${escape(text)}</dd></div>`).join('');
    $('#assay-question').textContent=assay.question;$('#assay-options').innerHTML=assay.options.map(([text,correct],index)=>`<button type="button" data-option="${index}" data-correct="${correct}">${escape(text)}</button>`).join('');$('#assay-feedback').textContent='';
  }
  function renderDynamics(){
    const early=[90,55,28,20,27,38,52,64],sustained=[90,62,42,31,25,22,20,18],labels=['0h','2h','6h','12h','24h','48h','72h','96h'];
    $('#dynamics-chart').innerHTML=labels.map((label,index)=>{const hidden=dynamicsView==='endpoint'&&index!==4;return `<div class="pl-time-col" style="visibility:${hidden?'hidden':'visible'}"><i style="height:${early[index]}%" title="Transient inhibition ${early[index]}"></i><i class="alt" style="height:${sustained[index]}%" title="Sustained inhibition ${sustained[index]}"></i><span>${label}</span></div>`;}).join('');
    $('#dynamics-explanation').textContent=dynamicsView==='endpoint'?'只看 24 h，两组 response 接近；早期强度和后期 rebound 已经不可见。Endpoint 不能重建 trajectory。':'蓝色轨迹先下降后 rebound；coral 轨迹持续下降。时间序列把“同一个 24 h 数值”拆成不同的 pathway history。';
    document.querySelectorAll('[data-view]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.view===dynamicsView)));
  }
  function renderHypothesis(){
    $('#hypothesis-controls').innerHTML=hypotheses.map((item,index)=>`<button type="button" data-hypothesis="${index}" aria-pressed="${index===activeHypothesis}"><b>${escape(item.title)}</b>${escape(item.short)}</button>`).join('');
    const item=hypotheses[activeHypothesis];
    $('#integration-evidence').innerHTML=item.evidence.map(([layer,text,status])=>`<div class="pl-evidence-row"><span>${escape(layer)}</span><p>${escape(text)}</p><b class="${status}">${status==='support'?'SUPPORTS':status==='compatible'?'COMPATIBLE':'MISSING'}</b></div>`).join('');
    $('#integration-next').innerHTML=item.next.map(text=>`<li>${escape(text)}</li>`).join('');
  }
  function renderClaims(){
    $('#claim-example').innerHTML=claims.map((claim,index)=>`<option value="${index}">${escape(claim.text)}</option>`).join('');
    const levels=[['observation','Observation'],['association','Association'],['mechanism','Mechanism'],['prediction','Prediction']];
    $('#claim-levels').innerHTML=levels.map(([value,label])=>`<label><input type="radio" name="claim-level" value="${value}">${label}</label>`).join('');
  }
  $('#timepoint-controls').addEventListener('click',event=>{const button=event.target.closest('[data-time]');if(!button)return;activeTime=Number(button.dataset.time);renderTimeline();renderCase();});
  $('#assay-tabs').addEventListener('click',event=>{const button=event.target.closest('[data-assay]');if(!button)return;activeAssay=button.dataset.assay;renderAssay();});
  $('#assay-tabs').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const ids=Object.keys(assays),current=ids.indexOf(activeAssay);event.preventDefault();const next=event.key==='Home'?0:event.key==='End'?ids.length-1:(current+(event.key==='ArrowRight'?1:-1)+ids.length)%ids.length;activeAssay=ids[next];renderAssay();document.querySelector(`[data-assay="${activeAssay}"]`).focus();});
  $('#assay-options').addEventListener('click',event=>{const button=event.target.closest('[data-option]');if(!button)return;const correct=button.dataset.correct==='true';document.querySelectorAll('#assay-options button').forEach(item=>item.classList.remove('is-correct','is-wrong'));button.classList.add(correct?'is-correct':'is-wrong');$('#assay-feedback').textContent=(correct?'正确。':'还不够稳妥。')+' '+assays[activeAssay].feedback;});
  document.querySelector('.pl-dynamics-controls').addEventListener('click',event=>{const button=event.target.closest('[data-view]');if(!button)return;dynamicsView=button.dataset.view;renderDynamics();});
  $('#hypothesis-controls').addEventListener('click',event=>{const button=event.target.closest('[data-hypothesis]');if(!button)return;activeHypothesis=Number(button.dataset.hypothesis);renderHypothesis();});
  $('#check-claim').addEventListener('click',()=>{const picked=document.querySelector('input[name="claim-level"]:checked');const claim=claims[Number($('#claim-example').value)];$('#claim-feedback').textContent=!picked?'先选择一个 evidence level。':(picked.value===claim.answer?'判断正确。 ':'再看一次 evidence 的类型。 ')+claim.why;});
  $('#claim-example').addEventListener('change',()=>{$('#claim-feedback').textContent='';document.querySelectorAll('input[name="claim-level"]').forEach(input=>{input.checked=false;});});
  renderTimeline();renderCase();renderAssay();renderDynamics();renderHypothesis();renderClaims();
})();
