window.BIOCS_BOOK.push({
  code:'02', title:'分子生物学 Molecular Biology', description:'DNA 复制与修复、Central Dogma、RNA、蛋白和基因调控。', chapters:[
  {id:'m01',title:'DNA 复制、校对与修复',subtitle:'一份遗传材料怎样传给两个子细胞？',intro:'细胞分裂前必须复制基因组。碱基配对帮助复制，但真实过程依赖许多酶，且出错后的修复决定哪些变化会保留下来。',goals:['理解半保留复制','分清复制与转录','知道错误会被校对或修复'],prereq:['g01','b04'],flow:[['双链打开','两条旧链分开'],['模板配对','新链按 5′→3′ 合成'],['校对修复','减少永久错误'],['子细胞','各获一套 DNA']],sections:[
    ['半保留复制是什么意思',`<p>双链 DNA 分开后，每条旧链都作为模板合成互补的新链。复制后的两条双链，各含一条旧链与一条新链，因此称<strong>半保留复制</strong>。DNA 聚合酶只能把核苷酸加到新链的 3′ 端，所以新链沿 5′→3′ 方向增长。</p><p>两条模板方向相反，复制机器因此形成连续合成的 leading strand 与分段合成的 lagging strand；后者片段需要连接。这个方向性是理解测序和突变位置的基础。</p>`,['os14','nhDNA']],
    ['复制不是转录',`<p>复制要让整个 DNA 信息成为两套；转录通常只把选定区域的信息写成 RNA。复制使用 DNA 核苷酸，转录使用 RNA 核苷酸；两者都依赖模板互补，但目的、酶和产物不同。</p><p>细胞周期的 S 期进行核 DNA 复制。多数正常体细胞不是一直复制；复制受周期检查点与环境信号控制。</p>`,['os14','nhTrans','nhCycle']],
    ['错误、校对与修复',`<p>复制时可能插入错误碱基，DNA 也可能受到化学或物理损伤。聚合酶校对与不同 DNA 修复途径减少留下的错误。若变化没有被纠正，并传给后代细胞，就可能形成稳定的体细胞变异。</p><p>“DNA repair gene mutated”不等于每一个肿瘤都会产生同样的突变图谱；具体影响取决于基因、等位基因状态、组织、其他修复机制和取样时间。</p>`,['os14','nciGenetics']],

    ['把复制叉拆成五个动作',`<p>以真核细胞核 DNA 为例：①多个 <strong>origin / 起始点</strong>启动复制；② <strong>helicase / 解旋酶</strong>打开双链；③ <strong>primase / 引物酶</strong>提供可延伸的短引物；④ DNA polymerase 只能给新链的 3′ 端加核苷酸；⑤后随链形成的 <strong>Okazaki fragments / 冈崎片段</strong>经过引物处理与 <strong>ligase / 连接酶</strong>封口。方向限制解释了领先链连续、后随链分段的差别。</p><p>这是一张工作流程图；人类复制机器包含更多蛋白与质量控制。记忆时抓住“模板反向平行，但两条新链都只能 5′→3′ 增长”。</p>`,['osReplication','osFork']],
    ['复制一条染色体后，为什么还是一对同源染色体？',`<p>以一个普通二倍体细胞的一对同源染色体为例：G1 期有一条来自父方、一条来自母方，合计两条染色体，每条一条染色单体。S 期后，每条染色体各有两条姐妹染色单体；DNA 分子数从 2 变 4，但同源关系和细胞倍性仍按 2n 描述。M 期姐妹染色单体分离后，两个子细胞各得回一父一母的两条染色体。</p><p>“DNA 量翻倍”与“染色体拷贝数异常”不能混用。肿瘤 CNV 分析还要考虑非整倍体与肿瘤纯度。</p>`,['osCycle','nhChrom']],
    ['DNA 修复、复制错误与测序错误分属三层',`<p>复制错误发生在细胞里；修复决定它是否保留并被后代细胞继承；测序错误发生在样本处理与仪器读取阶段。一个 VCF 候选位点可能来自稳定的体细胞变异，也可能来自建库、比对或碱基调用伪影。两者都能产生 ALT reads，但生物学含义不同。</p><p>因此做肿瘤变异分析时，读段数、碱基质量、链偏倚、配对正常样本和技术验证各解决不同风险。</p>`,['osReplication','gdcDNA']],
    ['复制、PCR、测序是三个不同动作',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>动作</th><th>发生在哪里</th><th>产物或读数</th></tr></thead><tbody><tr><td>细胞 S 期复制</td><td>活细胞内部</td><td>给后代细胞分配的 DNA 副本</td></tr><tr><td>PCR 扩增</td><td>提取样本后的反应管或仪器</td><td>引物界定区域的大量 DNA 拷贝</td></tr><tr><td>DNA 测序</td><td>测序仪与分析流程</td><td>读段及其碱基/质量信息</td></tr></tbody></table></div><p>PCR 常通过加热分开 DNA 链，使用引物和耐热聚合酶扩增选定区域；它不是细胞把整个基因组复制给子细胞。部分测序建库还会用 PCR，因而可能引入扩增偏倚；但并非所有测序都必经同一种 PCR 步骤。测序读到的差异还需和细胞里真实存在的稳定变异区分。</p><details><summary>先猜：某个位点 0 条 ALT reads，能断言肿瘤没有这个变异吗？</summary><p>先看分母与质控。如果合格覆盖本来就是 0，就根本没有观测信息；若有 100 条合格 reads 且 0 条 ALT，只能说在这次测量和检测阈值下没有得到 ALT 证据，仍不能证明所有肿瘤细胞都没有该变异。</p></details>`,['osReplication','osPCR','gdcDNA']]
  ],worked:['从模板写新链',['旧模板为 <code>3′–TACG–5′</code>。','按互补配对加入 A、T、G、C；新链写作 <code>5′–ATGC–3′</code>。','复制结果包含这条新链与旧模板；另一条旧链也会各自指导新链合成。']],terms:[['Replication / 复制','细胞复制 DNA 以传递遗传信息。','os14'],['DNA polymerase / DNA 聚合酶','按模板合成 DNA 的酶。','os14'],['DNA repair / DNA 修复','识别并处理 DNA 损伤或错误的过程。','os14']],check:['为什么新链的 5′→3′ 合成方向会产生领先链和后随链的差别？','两条模板反向平行，而聚合酶只能沿新链 5′→3′ 合成；因此一侧能连续合成，另一侧需分段合成。']},
  {id:'m02',title:'Central Dogma：信息如何流动',subtitle:'把 DNA 复制、转录与翻译放在同一张地图上。',intro:'Central Dogma 是分子序列信息流的入门框架：DNA 可被复制，DNA 可转录成 RNA，部分 RNA 可翻译成蛋白质。它不是“一个基因必然制造一个蛋白并决定一个表型”。',goals:['区分复制、转录、翻译','认识 mRNA、rRNA、tRNA 与非编码 RNA','理解不同组学测量不同层'],prereq:['m01'],image:['assets/central-dogma-detail.svg','原创详细信息流示意：DNA 复制、转录、RNA 加工、翻译、非编码 RNA 分支','仅作信息流示意。',['nhDogma','nhRNA','ncbiRNA']],sections:[
    ['先读懂三条不同的箭头',`<p><strong>Replication / 复制：</strong>DNA → DNA，分裂前保留信息。<strong>Transcription / 转录：</strong>DNA → RNA，把特定区域的信息写成 RNA。<strong>Translation / 翻译：</strong>mRNA → 氨基酸链，核糖体按密码子读取。复制和转录都不是“细胞看见字母就自动执行”，而由分子机器与调控条件控制。</p><p>这些箭头描述<strong>序列信息</strong>的传递方向，不表示 DNA 变化会以固定比例改变 RNA、蛋白和疾病风险。</p>`,['nhDogma','nhTrans','nhTranslation']],
    ['四种 RNA，四种不同任务',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>RNA</th><th>先记住的功能</th><th>为什么对数据重要</th></tr></thead><tbody><tr><td>mRNA</td><td>携带可翻译的编码信息</td><td>常见 poly(A) RNA-seq 重点捕获它</td></tr><tr><td>rRNA</td><td>组成核糖体并参与翻译</td><td>总 RNA 中常很丰富；许多文库要去除它</td></tr><tr><td>tRNA</td><td>把 codon 与氨基酸连接</td><td>较短且有修饰，常规 mRNA 文库不等于完整测到了它</td></tr><tr><td>调控性 RNA</td><td>例如 miRNA、部分 lncRNA 调节其他分子</td><td>需要核对文库是否覆盖其类别与长度</td></tr></tbody></table></div><p>“transcriptome / 转录组”可指细胞里的全部 RNA，某些上下文却只统计 mRNA。读方法时先看作者用的是 poly(A) 富集、rRNA 去除、small-RNA 文库，还是其他 assay；文件同叫 RNA-seq 并不意味着测量范围相同。</p>`,['nhRNA','illuminaRNAprep']],
    ['真实路线有加工与分支',`<p>在人类细胞中，许多蛋白编码基因的初始 RNA 会被加帽、加 poly(A) 尾并剪接，成熟 mRNA 才参与翻译。部分 RNA 本身发挥功能，不进入蛋白质分支。某些病毒或遗传元件还有 RNA → DNA 的逆转录；RNA 病毒也可由 RNA 模板复制 RNA。因此中心法则简图是主要信息流的学习入口，不是所有系统的完整线路图。</p><p>新生蛋白还需折叠、定位、修饰与降解。单个 DNA、RNA 或蛋白质组读数都只观测其中一层；蛋白的折叠状态可以传播，但不等于把蛋白氨基酸序列直接倒写成核酸序列。</p>`,['nhRNA','ncbiRNA','nhDogma','osVirus']],
    ['先搭地图，再做完整推演',`<p>下一章会从两条反向平行 DNA 链写出 RNA；再下一章解释剪接；之后用 <code>AUG GCU UAA</code> 把 RNA 读成 Met–Ala–Stop。原站的 <a href="course.html#l06">逐步动画式讲解</a>也可作为这几章的配套练习。</p><p>如果读论文时看到“基因上调”，先停下来问：测到的是 RNA 增加、蛋白增加，还是蛋白活性改变？这是不同命题。</p>`,['nhDogma','gdcRNA']],
    ['箭头传递序列信息，不表示数值自动同步',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>同一个基因的教学样本</th><th>DNA 位点</th><th>RNA-seq observed count</th><th>蛋白实验信号</th></tr></thead><tbody><tr><td>样本 A</td><td>存在</td><td>0</td><td>检测到</td></tr><tr><td>样本 B</td><td>存在</td><td>30</td><td>未检出</td></tr></tbody></table></div><p>这是<strong>虚构的测量例子</strong>：两者都含有 DNA 位点，但 RNA 文库的 0 是“按这次方法和规则没有计到”，不能自动写成“基因不存在”；蛋白未检出也可能受翻译、降解、实验覆盖和阈值影响。DNA→RNA→蛋白说的是可用的序列信息路线，不规定每一层的数值相等、同时变化或必然能被仪器观测到。</p><details><summary>先猜：样本 A 的 RNA count 为 0，是否与蛋白实验检测到信号矛盾？</summary><p>未必矛盾。蛋白可能比对应 RNA 留存更久；也可能是 RNA 的捕获深度或蛋白实验的特异性问题。先确认是不是同一细胞来源、同一时间、同一基因或蛋白形式，再评价技术和生物解释。</p></details>`,['nhDogma','nhRNA','gdcRNA','pride']]
  ],worked:['给每种数据找对箭头',['DNA sequencing 报告序列、变异和拷贝数。','RNA-seq 报告 RNA 相关读数，受细胞类型和实验流程影响。','蛋白质组学报告被检测到的肽段或蛋白相关信号。','要提出 DNA→RNA→蛋白的机制，需要配对样本与跨层证据。']],terms:[['Central Dogma / 中心法则','关于核酸与蛋白序列信息流的核心框架。','nhDogma'],['Transcription / 转录','用 DNA 模板合成 RNA。','nhTrans'],['Translation / 翻译','按 mRNA 密码子合成多肽链。','nhTranslation']],check:['DNA → RNA → 蛋白质说明 RNA 值高就一定蛋白活性高吗？','不说明。翻译、定位、修饰、降解、细胞环境都可改变蛋白丰度和活性。']},
  {id:'m03',title:'转录：从 DNA 写出 RNA',subtitle:'方向、模板链、编码链与启动子。',intro:'“转录”比把 T 改成 U 多一步：先知道谁是模板、方向如何、从哪里开始，再考虑调控何时让 RNA 聚合酶进入。',goals:['分清 template 与 coding strand','手写一段 RNA','认识 promoter 与转录因子'],prereq:['m02'],flow:[['启动子附近','蛋白招募转录机器'],['模板链','按 3′→5′ 被读取'],['RNA 聚合酶','沿 5′→3′ 合成'],['初始 RNA','等待加工或发挥功能']],sections:[
    ['两条 DNA 链扮演不同角色',`<p>对某一个基因，RNA 聚合酶读取<strong>template strand / 模板链</strong>，沿模板链 3′→5′ 移动；新 RNA 以 5′→3′ 方向合成并与模板互补。另一条是<strong>coding strand / 编码链</strong>：在对应转录区域，其 5′→3′ 序列与初始 RNA 相同，只需把 T 换成 U。</p><p>“编码链”是相对于具体转录单位而言；同一染色体的不同基因可以位于不同方向，不是整条染色体永远只用一条链。</p>`,['nhTrans','nhRNA']],
    ['逐碱基写出 RNA',`<p>无内含子的教学片段：编码链 <code>5′–ATG GCT TAA–3′</code>，模板链 <code>3′–TAC CGA ATT–5′</code>。按互补规则，RNA 为 <code>5′–AUG GCU UAA–3′</code>。这里 A→U、T→A、C→G、G→C，且方向始终要一起写。</p><p>这只是展示序列规则；真实人类基因可能有长内含子、多个起点与转录本，mRNA 在翻译前也通常要加工。</p>`,['nhTrans','nhRNA']],
    ['什么时候转录，由调控决定',`<p><strong>Promoter / 启动子</strong>附近的 DNA 序列、转录因子、染色质状态与细胞信号影响转录机器的进入及活动。一个细胞的 DNA 含有许多基因，却只在特定时间与条件下表达其中一部分。</p><p>因此 DNA 序列表示潜在信息，RNA-seq 更接近某时某样本的转录快照；二者不能互换。</p>`,['os16','nhTrans']],
    ['TSS 与 AUG：转录起点不是翻译起点',`<p>RNA 从 <strong>TSS / transcription start site</strong>开始写出；核糖体通常在成熟 mRNA 的起始密码子附近开始翻译。两点之间的序列可成为 <strong>5′ UTR</strong>，保留在 RNA 中却不按标准阅读框翻译成蛋白。翻译停止后还可能有 <strong>3′ UTR</strong>；RNA 的终点又在更后面。</p><p>所以一条 read 落在 5′ UTR，仍可能是某转录本的证据；把“不是 CDS”误读成“不是 gene”会漏掉真实 RNA。<a href="#g02">回看基因结构图</a>，再读 <a href="#m04">RNA 加工与剪接</a>。</p>`,['gencodeFormat','osTranscription']],
    ['参考基因组的坐标方向，与基因方向分开',`<p>参考基因组通常把坐标从小到大列出；<strong>strand / 链方向</strong>则说明这个转录本沿参考序列的哪一条链转录。正链基因沿坐标增加的方向写出 RNA；负链基因沿坐标减小的方向写出 RNA。于是负链基因的 TSS 可以有比后面外显子更大的基因组坐标。“start 坐标较小”只是文件列的排序规则，不等于生物学的 5′ 端。</p><details><summary>先猜：GTF 一行写 chr1、start=100、end=200、strand=−，RNA 一定从 100 向 200 合成吗？</summary><p>不能这样判断。负链转录本的 5′→3′ 生物方向沿参考坐标减小；还要看具体转录本的 TSS 和 exon 注释。坐标顺序、DNA 链方向与 RNA 合成方向是三件要同时记录的事。</p></details>`,['gencodeFormat','nhTrans']]
  ],worked:['核对 template 与 coding 的方向',['给定编码链 <code>5′–ATG GCT TAA–3′</code>。','模板链要反向平行：<code>3′–TAC CGA ATT–5′</code>。','RNA 与模板互补且 5′→3′：<code>5′–AUG GCU UAA–3′</code>。','检查：RNA 与编码链对应区域一致，只是 U 代替 T。']],terms:[['Template strand / 模板链','转录时被 RNA 聚合酶读取的 DNA 链。','nhTrans'],['Coding strand / 编码链','与相应初始 RNA 序列相近、T/U 不同的 DNA 链。','nhTrans'],['Promoter / 启动子','影响转录起始的 DNA 区域。','os16']],check:['给定 DNA 模板 3′–TAC–5′，合成的 RNA 是什么？','按互补规则得到 <code>5′–AUG–3′</code>；方向必须写对。']},
  {id:'m04',title:'RNA 加工、剪接与转录本',subtitle:'基因级 count 为什么会掩盖重要差异？',intro:'人体很多蛋白编码基因先产生 pre-mRNA。细胞对它进行加工后，一个基因可以形成多种成熟 RNA，进一步影响蛋白产物。',goals:['认识 cap、poly(A)、splicing','区分 gene 与 transcript','理解 isoform 的数据意义'],prereq:['m03'],flow:[['pre-mRNA','含内含子的初始产物'],['5′ cap / poly(A)','保护、输出与翻译相关'],['splicing','移除内含子并连接外显子'],['mature RNA','可产生不同 isoform']],sections:[
    ['初始 RNA 还要加工',`<p>对许多人类蛋白编码基因，初始 <strong>pre-mRNA</strong>会形成 5′ cap、3′ poly(A) 尾并经过剪接。剪接通常去掉 intron / 内含子，连接 exon / 外显子。加工影响 RNA 稳定性、输出和翻译，不能把初始 DNA 区域一字不漏地直接当成成熟 mRNA。</p><p>这些步骤的具体顺序和形式有差异；并不是所有 RNA 都具有相同的加工模式。</p>`,['ncbiRNA','os15']],
    ['可变剪接产生不同 isoform',`<p>同一个基因的一组外显子可按不同方式连接，称<strong>alternative splicing / 可变剪接</strong>。不同 transcript / 转录本可能有不同的非翻译区或编码序列，甚至只有部分转录本编码蛋白。因此“一个基因对应一个蛋白”是过度简化。</p><p>两个样本的 gene-level 总 RNA count 相同，也可能 transcript A 与 B 的比例完全不同。分析时要问测量方法是否能分辨这些 isoform。<a href="#s07">剪接专题</a>会进一步解释 junction、PSI 和肿瘤研究中的验证。</p>`,['nhSplice','os15','rmats']],
    ['转录本注释会改变变异后果',`<p>一个 DNA 变异对转录本 A 可能是编码区错义，对转录本 B 可能位于非编码区；因此功能后果标签应带上转录本版本。短读长 RNA-seq 对相似转录本的定量可能不确定，不能只凭一个表格数字忽略这种歧义。</p><p>报告时同时写 gene ID、transcript ID、注释版本和采用的 RNA 定量单位。</p>`,['nhSplice','gdcRNA']],
    ['一条跨外显子的 read 能告诉我们什么',`<p>如果某条 RNA-seq read 的前半段对上 exon 1、后半段对上 exon 3，它可能支持 exon 1→3 的剪接连接；另一些 read 分别支持 exon 1→2 与 exon 2→3；若读段很短，这两类证据本身还不能证明它们来自同一条完整 RNA。算法用这样的 <strong>junction reads / 跨接读段</strong>等证据估计可变剪接。它看见的是采样与建库后留下的读段，不是直接看到每条完整 RNA。</p><details><summary>先猜：表里 exon 1→3 的 junction count 为 0，就能断言这种转录本在人体中不存在吗？</summary><p>不能。它只表示在该样本和该分析规则下没观察到支持该连接的 read；读长、深度、表达量、比对与过滤规则都可能影响结果。尤其在低覆盖时，0 比“生物学绝无”弱得多。</p></details>`,['nhSplice','rmats','gencodeFormat']]
  ],worked:['同一个 gene count 如何掩盖 isoform 改变',['样本 1：转录本 A=80、B=20，总量=100。','样本 2：A=20、B=80，总量仍=100。','只比较 gene-level 总量会得出“不变”；转录本组成却明显不同。','但也要确认测序读段是否足以准确区分 A 与 B。']],terms:[['Intron / 内含子','在许多前体 RNA 中被剪接去除的区域。','ncbiRNA'],['Exon / 外显子','剪接后保留于成熟转录本的区域；不全都编码蛋白。','nhSplice'],['Isoform / 异构体','同一基因产生的不同转录本或蛋白形式。','nhSplice']],check:['gene-level RNA count 相同，能断言蛋白产物种类没有变化吗？','不能。可变剪接可能改变转录本比例，且翻译与蛋白加工还有其他调控。']},
  {id:'m05',title:'密码子、翻译与蛋白结构',subtitle:'从三字母 RNA 读到氨基酸链，再走向功能。',intro:'核糖体一次按三碱基读取 mRNA。阅读框、起始与终止决定多肽序列，但最终蛋白功能还依赖折叠、位置和修饰。',goals:['逐 codon 翻译','理解阅读框','区分蛋白序列与活性'],prereq:['m04'],flow:[['mRNA','5′→3′ 的 codon'],['核糖体 + tRNA','按密码子加氨基酸'],['多肽链','线性氨基酸序列'],['成熟蛋白','折叠、定位、修饰']],sections:[
    ['三个碱基一组',`<p><strong>Codon / 密码子</strong>是 mRNA 上连续三个碱基。标准遗传密码中 <code>AUG</code>编码 Met，常作为起始密码子；<code>GCU</code>编码 Ala；<code>UAA</code>是终止信号，不编码氨基酸。核糖体与 tRNA 协作，把 mRNA 的顺序转成氨基酸链。</p><p>起始位置决定<strong>reading frame / 阅读框</strong>。对同一串碱基，向前或向后移动一格，后面三字母分组会全部改变。</p>`,['nhCode','nhTranslation','ncbiCode']],
    ['用一个短例子完整翻译',`<p>教学 mRNA <code>5′–AUG GCU UAA–3′</code>依次读作 Met、Ala、Stop；得到的多肽氨基酸序列是 Met–Ala。终止密码子是停下来的信号，不是第三个氨基酸。真实蛋白通常远比这个例子长，翻译起始还受周围序列和细胞状态影响。</p><p>遗传密码有冗余：不同 codon 可能编码同一种氨基酸。故同义变异不改变氨基酸序列，但仍未必完全没有其他影响。</p>`,['nhCode','ncbiCode']],
    ['蛋白是三维功能分子',`<p>氨基酸链会折叠；某些蛋白还需组合成复合物、进入特定细胞区室或接受磷酸化等修饰才能发挥作用。<strong>Protein abundance / 蛋白丰度</strong>与活性不是同义词：相同丰度下，活性可因修饰或抑制剂改变。</p><p>因此 DNA missense 预测是序列层提示，蛋白质组信号是测量层证据，功能结论还需看结构、生化或细胞实验。</p>`,['os3','os15','pride']],

    ['核糖体、tRNA 和终止因子各做什么',`<p>核糖体沿成熟 mRNA 的 5′→3′ 方向读取 codon；携带相应氨基酸的 <strong>tRNA</strong>以 anticodon / 反密码子与其配对，多肽链从 N 端向 C 端增长。起始建立阅读框，延长阶段反复加氨基酸，遇到终止 codon 时由释放因子结束。mRNA 的 5′ UTR 已被转录，但通常不属于这个标准阅读框的蛋白序列。</p><p>不同转录本可能有不同 UTR 或 CDS；只给一个 gene symbol，不足以唯一确定它翻译出的序列。</p>`,['nhTranslation','os15','gencodeFormat']],
    ['三种常见变异对翻译的初步影响',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>变异类型</th><th>最直观的序列结果</th><th>还要核对</th></tr></thead><tbody><tr><td>同义 SNV</td><td>codon 改了，氨基酸可能不变</td><td>剪接、RNA 稳定性等</td></tr><tr><td>错义 SNV</td><td>一个氨基酸可能改变</td><td>转录本、结构位置、功能</td></tr><tr><td>1 bp 编码区插入</td><td>下游阅读框可能改变</td><td>位置、是否发生于相关转录本</td></tr></tbody></table></div><p>“可能”是关键：每个标签都依赖转录本和注释，细胞是否产生、保存及使用该蛋白仍须另测。</p>`,['nhCode','gencodeFormat','nciGenetics']],
    ['亲手移动一次阅读框',`<p>原片段 <code>5′–AUG | GCU | UAA–3′</code>读出 Met–Ala–Stop。若在 AUG 后插入一个 C，新的连续序列是 <code>5′–AUGCGCUUAA–3′</code>，重新从同一起点分组为 <code>AUG | CGC | UUA | A…</code>。原来的 <code>UAA</code>不再落在同一个三联体位置，后续氨基酸与终止位置都可能改变。末尾单个 A 表示示例片段到此为止，不能凭它推断真实蛋白最终长度。</p><details><summary>先猜：如果插入三个碱基，后面的阅读框也必然整体移动吗？</summary><p>通常不会整体移位，因为插入长度是 3 的倍数；但可增加一个氨基酸或产生其他局部后果。具体后果仍依赖插入位置、转录本和翻译规则。</p></details>`,['nhCode','ncbiCode','gencodeFormat']]
  ],worked:['手算 AUG GCU UAA',['按 5′→3′ 每三位分组：<code>AUG | GCU | UAA</code>。','查标准遗传密码：AUG→Met，GCU→Ala，UAA→Stop。','得到 Met–Ala；Stop 不写成一个氨基酸。']],terms:[['Codon / 密码子','mRNA 上指定氨基酸或终止的三碱基单位。','nhCode'],['Reading frame / 阅读框','翻译时把序列切成连续三碱基组的起点与方式。','os15'],['Ribosome / 核糖体','读取 mRNA 并合成多肽的分子机器。','nhTranslation']],check:['若在编码区插入 1 个碱基，为什么后面许多氨基酸可能改变？','插入非 3 的倍数个碱基会改变阅读框，使后续 codon 分组改变。']},
  {id:'m06',title:'基因调控与表观遗传',subtitle:'为什么拥有近似同样 DNA 的细胞会不同？',intro:'DNA 提供可用序列，细胞类型和环境决定何时使用哪些区域。调控分布在染色质、转录、RNA、翻译和蛋白活性多个层面。',goals:['认识调控元件与转录因子','理解染色质和表观状态','避免把甲基化等同于关闭'],prereq:['m03','b05'],flow:[['染色质可及性','DNA 能否被接触'],['转录调控','启动子/增强子/TF'],['RNA 调控','剪接、稳定性'],['蛋白调控','翻译、修饰、降解']],sections:[
    ['转录因子和调控元件',`<p>转录因子可识别 DNA 序列并参与招募或阻碍转录机器。<strong>Promoter / 启动子</strong>与<strong>enhancer / 增强子</strong>等调控区域影响基因表达，增强子可能距离目标基因较远，因此“最近的基因”未必是它的调控目标。</p><p>一个受体接收外部信号后，细胞内分子可改变转录因子活动，使一组基因的 RNA 水平变化。这里就把细胞信号与 Central Dogma 接上了。读完基础后到 <a href="#s06">enhancer 专题</a>看 cCRE、靶基因与功能验证。</p>`,['os16','nhPath','encodeGlossary']],
    ['染色质与表观遗传',`<p>DNA 在细胞核中与组蛋白等结合形成染色质。其包装状态、DNA 甲基化及组蛋白修饰与基因使用方式相关。<strong>Epigenetics / 表观遗传</strong>讨论不改变 DNA 字母本身的调控状态及其在细胞分裂中的维持问题。</p><p>“某基因附近甲基化升高 → 该基因一定关闭”不是通用规则。不同区域、细胞类型和背景下的关系不同，测量还需区分关联与因果。</p>`,['nhEpigen','os16']],
    ['调控是多层的，不等于 RNA 一列',`<p>细胞可调控 RNA 的产生、剪接、输出、稳定性和翻译；蛋白活性还能被修饰、定位及降解决定。RNA-seq 很有用，但不能覆盖全部调控。ATAC-seq、甲基化、ChIP-seq 等实验从不同角度观察调控相关状态。</p><p>分析跨层关系时，把“DNA 变异→染色质→RNA→蛋白”当作待检验的模型，而不是仅凭相关矩阵画成已证实的因果网络。</p>`,['os16','encode']],
    ['把三种调控表格放在正确层级',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>实验</th><th>主要观察对象</th><th>不能直接证明</th></tr></thead><tbody><tr><td>ATAC-seq</td><td>在该样本中较易被酶接触的 DNA 区域</td><td>某区域必定调控最近基因</td></tr><tr><td>DNA 甲基化测量</td><td>特定位置或区域的甲基化状态/比例</td><td>旁边基因一定关闭</td></tr><tr><td>RNA-seq</td><td>捕获到的 RNA 相关读数</td><td>蛋白量或活性必然同向变化</td></tr></tbody></table></div><p>这些表格的<strong>行对象</strong>不同：DNA 区域、CpG 位点或基因/转录本。直接按行号合并会制造伪关系；先统一 genome build、注释版本、样本 ID 和细胞来源。一个开放的染色质峰可以提示候选调控区，但“峰→靶基因”仍需接触、表达或干预等证据。</p><details><summary>先猜：某 enhancer-like 峰距 gene A 最近，能把 gene A 写成已证靶基因吗？</summary><p>不能。候选调控标记及距离只生成假设；增强子可能作用于更远的基因，且作用依赖细胞背景。ENCODE 的 cCRE 也明确是“candidate”。</p></details>`,['encode','encodeGlossary','nhEpigen','gdcRNA']]
  ],worked:['为什么同一 DNA 可对应神经细胞与免疫细胞？',['两种细胞的核 DNA 绝大部分相同。','发育历史、转录因子、染色质状态和外部信号不同。','它们表达不同基因及转录本，产生不同蛋白组合与功能。']],terms:[['Transcription factor / 转录因子','参与调节基因转录的蛋白。','os16'],['Enhancer / 增强子','可影响目标基因转录的调控 DNA 区域。','os16'],['Epigenetics / 表观遗传','不改变 DNA 序列字母的遗传或稳定调控状态研究。','nhEpigen']],check:['某区域甲基化升高，能否在任何组织都推断邻近基因 RNA 一定下降？','不能。关系取决于区域和细胞背景；需要配对表达数据与进一步实验。']},
  {id:'m07',title:'从变异到表型：证据链',subtitle:'把分子生物学连接到真正的研究问题。',intro:'某 DNA 变异是否影响一个病人的癌症结局？从序列后果到临床现象至少跨越多个层级，任何一步都可能失效或被其他机制解释。',goals:['构造跨层机制假设','认识证据强度差异','区分关联与干预实验'],prereq:['g05','m05','m06'],flow:[['DNA 事件','变异/拷贝数'],['RNA 与调控','数量/剪接'],['蛋白功能','结构/活性/位置'],['细胞行为','增殖/死亡/迁移'],['患者结果','疾病和治疗结局']],sections:[
    ['第一步：证明事件真实存在',`<p>先查测序覆盖度、质量和正常对照，确认 DNA 事件不是比对伪影；再标明 build、转录本、样本来源。仅有“TP53 mutation”一个字符串，无法判断检测范围、是否体细胞、是否多亚克隆。</p><p>进一步问这个位点在人群中多常见、在该癌种中是否反复出现，以及它对 RNA 或蛋白的预测后果。</p>`,['gdcDoc','nhMutation']],
    ['第二步：寻找机制中间层',`<p>若假设拷贝数增加使 RNA 增加，需要同一病例中匹配的 CNV 与 RNA 样本，检查细胞组成和批次。若假设错义变异改变蛋白活性，就需蛋白结构、生化实验或相关功能读数；RNA 不变也不能排除蛋白活性改变。</p><p>每个箭头都要写出可观测的预测和可能的替代解释。这样分析图就从故事变成可证伪的研究设计。</p>`,['gdcRNA','os15']],
    ['第三步：把细胞结果与患者结果分开',`<p>培养皿中的细胞增殖变化不自动等于患者总体生存变化。肿瘤类型、免疫环境、治疗、分期和临床随访都可能改变结果。观察性 TCGA 数据可发现关联和提出机制，但因果主张通常需要干预、独立队列和多层证据。</p><p>报告应说清“我们看见了什么”和“我们推测了什么”，让读者知道结论边界。</p>`,['nciCancer','tcga','gdcDoc']],
    ['同一患者，不一定是同一次生物状态',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>虚构文件</th><th>case</th><th>sample</th><th>取样时间</th><th>读数</th></tr></thead><tbody><tr><td>DNA VCF</td><td>P01</td><td>T01</td><td>治疗前</td><td>变异</td></tr><tr><td>RNA count</td><td>P01</td><td>T02</td><td>治疗后</td><td>表达</td></tr><tr><td>临床表</td><td>P01</td><td>—</td><td>随访</td><td>结局</td></tr></tbody></table></div><p>三行都能用 P01 关联，但 DNA 与 RNA 来自不同取样时间和不同样本。可以研究“同一患者治疗前 DNA 与治疗后 RNA 的关系”，却不能未经说明就把两者画成同一次细胞状态的直接机制链。跨组学合并时，<strong>case、sample、时间、组织部位和 assay</strong>都要成为显式字段。</p><details><summary>先猜：这三行是三个独立患者吗？能直接写“DNA 变异导致 RNA 升高并使预后变差”吗？</summary><p>只有一位患者，不能把三份文件当成 n=3；时间不匹配，RNA 变化也可能受治疗、细胞组成或批次影响。更强的主张需要合适的配对、多患者比较、控制混杂及功能验证。</p></details>`,['gdcCase','gdcDoc','gdcRNA']]
  ],worked:['给“变异导致差预后”建立证据阶梯',['确认变异调用可靠且位于预先定义的队列。','确认它与 RNA、蛋白或细胞功能的具体改变相关。','在患者数据中控制主要混杂，报告效应和不确定性。','使用独立数据或功能干预检验机制，避免把关联写成已证因果。']],terms:[['Mechanism / 机制','描述一系列可检验分子或细胞过程的解释。','nhPath'],['Confounding / 混杂','第三因素同时影响比较变量与结果。','gdcDoc'],['Functional assay / 功能实验','直接测量或干预分子/细胞作用的实验。','os17']],check:['DNA 变异与生存显著相关，是否已经证明了细胞机制？','没有。观察性关联仍可能来自混杂、连锁、细胞组成或治疗差异；机制需中间层与干预证据。']}
]});
