window.BIOCS_BOOK.push({
  code:'09', title:'测序与表达定量精讲 Sequencing & Quantification', description:'从核酸、文库、测序循环和 FASTQ，一步步走到 counts、CPM、RPKM/FPKM、TPM 与差异表达。', chapters:[
  {id:'q01',title:'从组织里的 RNA 到测序文库',subtitle:'先弄清仪器拿到的材料，才知道表格丢失了什么。',intro:'RNA-seq 不是把一个细胞的 RNA 全部直接读出。取样、提取、选择目标、逆转录、加接头和扩增共同决定哪些分子有机会进入最终数据。以下以常见短读长 bulk RNA-seq 为主；具体试剂盒的步骤顺序会变化。',goals:['从组织追踪到 library fragment','区分 poly(A) 富集和 rRNA 去除','解释 index、UMI 与 PCR duplicate'],prereq:['m03','m04','d01'],image:['assets/sequencing-journey.svg','原创测序流程图：组织、RNA 提取、目标选择、cDNA 文库、flow cell、FASTQ 和计数','流程针对常见短读长 RNA-seq；不同平台、文库方案与样本质量会改变步骤。',['illuminaWorkflow','illuminaRNAprep','gdcRNA']],sections:[
    ['第一步：采集的是组织，不是“表达矩阵”',`<p>一块肿瘤包含癌细胞、免疫细胞、基质细胞及血管。取样位置、缺血时间、保存方式和肿瘤纯度决定混合比例。bulk RNA-seq 把许多细胞的 RNA 合并；得到的是这块材料的<strong>混合读数</strong>，不能把它当成每个肿瘤细胞的状态。</p><p>如果临床组与对照组使用不同的取样或保存流程，随后出现的表达差异可能来自前分析阶段。记录患者、材料、组织区域、采样时间和处理批次，比先选算法更重要。</p>`,['gdcSample','gdcRNA']],
    ['提取 RNA：完整性与来源会筛掉分子',`<p>提取后通常检查数量、纯度和片段完整性。RNA 易降解；FFPE 等保存材料常含较短片段。降解会造成沿转录本位置不均匀的覆盖，也影响哪些 RNA 能进入文库。DNA 残留可能混入测序信号，因此一些流程还会去除 DNA。</p><p>计算分析不能凭空恢复实验中已经丢掉的分子；若出现强烈 3′ 端偏倚、很低的比对率或异常 rRNA 比例，应回看实验条件与质量指标。</p>`,['illuminaRNAprep','gdcRNA']],
    ['先决定“测谁”：poly(A) 与 rRNA depletion',`<p>多数成熟真核 mRNA 有 poly(A) 尾；<strong>poly(A) selection</strong>用它富集一部分 mRNA。<strong>rRNA depletion</strong>去除大量核糖体 RNA，使 mRNA 和若干非编码 RNA 留在可测池中，也常用于较降解的材料。两种方案看到的 RNA 种类和偏差不相同。</p><p>因此“gene X 在 A 中是 0，在 B 中是 100”可能只是 A 的文库没覆盖这种 RNA。跨研究合并时，文库策略应作为 metadata；不能只看 FASTQ 文件扩展名。</p>`,['illuminaRNAprep','illuminaRRNA']],
    ['RNA 通常先变成 cDNA，再成为可测片段',`<p>常见 Illumina RNA-seq 先用逆转录酶把 RNA 信息写成 cDNA，再按方案片段化、合成双链、修复末端并加<strong>adapter / 接头</strong>。接头提供与 flow cell 结合及测序引物读取的序列；实验流程和方向性决定后续能否判断 RNA 来自哪一条 DNA 链。</p><p>不同试剂盒可能先片段化 RNA，也可能处理 cDNA；不要把某一套实验顺序当作所有 RNA-seq 的定义。测序读到的是文库中的核酸片段，不是完整原始 RNA。</p>`,['illuminaWorkflow','illuminaGlossary','gdcRNA']],
    ['index 标样本；UMI 标原始分子',`<p><strong>Sample index</strong>是给整个文库的标签，使多个样本混合上机后仍可拆分。<strong>UMI</strong>是在扩增前尽量给每个起始分子附上的短随机标签，可帮助区分来自同一分子的 PCR 复制。两者不能互换：同一患者文库的所有片段可共用 index，却需要许多不同 UMI。</p><p>UMI 去重是算法估计，仍受标签碰撞、测序错误和捕获效率影响；UMI count 也不是细胞中 RNA 总分子的无偏绝对数。</p>`,['illuminaUMI','illuminaGlossary']],
    ['PCR 放大了文库，也可能放大偏差',`<p>材料不足时常通过 PCR 增加可测文库量。两个相同 reads 可能来自同一个被放大的原始片段，也可能来自两个本来就相同位置的独立分子；是否去重取决于实验类型、UMI 是否存在和下游问题。对普通 bulk RNA-seq，不能简单删掉所有位置相同的 reads。</p><p>交付计算团队时，至少要有文库方案、是否 stranded、single/paired-end、index 与 UMI 设计、PCR 轮数、测序批次及读长；否则 count 的物理含义不完整。</p>`,['illuminaUMI','gdcRNA']]
  ],worked:['追踪一个 gene X 的 RNA 分子',['它先要存在于被取样的组织中，并在提取后存活。','文库选择必须保留这类 RNA；逆转录和片段化才能生成相应 cDNA。','片段加接头、可能被 PCR 扩增，测序后出现一个或多个 reads。','比对与定量算法再决定是否把这些 reads 分配给 gene X；count 因此是流程产物。']],terms:[['Library / 文库','可进入测序平台的一组带接头核酸片段。','illuminaWorkflow'],['Sample index','标记样本文库，供混合测序后的拆分使用。','illuminaGlossary'],['UMI','在扩增前给起始分子添加的标记，帮助识别 PCR 复制。','illuminaUMI']],check:['两个 reads 序列相同，就一定来自两个原始 RNA 分子吗？','不一定。PCR 可复制同一文库分子；反过来，独立分子也可能生成同一序列。要结合 UMI、位置和实验设计判断。']},

  {id:'q02',title:'测序仪怎样逐个碱基读出序列',subtitle:'把“测序”拆成可观察的化学循环。',intro:'以下用 Illumina 的 sequencing by synthesis（SBS）解释短读长测序。仪器并不是扫描 DNA 上现成的字母：聚合酶合成互补链，成像系统在每轮反应后把信号转换成碱基调用。其他平台的物理原理不同。',goals:['解释 cluster 与 SBS cycle','比较 Sanger 链终止与 SBS 的读序原理','区分 read、fragment、paired-end','把质量分数转成错误概率'],prereq:['g01','q01'],flow:[['文库固定','片段结合 flow cell'],['cluster','同源拷贝增强信号'],['SBS cycle','加入、成像、解除阻断'],['base call','序列与质量'],['FASTQ','可计算的读段']],sections:[
    ['互补配对是读序列的化学基础',`<p>DNA 聚合酶在模板上延长新链；模板 A 对应新链 T，C 对应 G。若模板为 <code>3′-T G C A-5′</code>，新链按方向可依次加入 <code>5′-A C G T-3′</code>。这里观察的是<strong>新合成链的碱基</strong>；后续比对软件会处理链方向。</p><p>测序错误是“仪器对这次加入的判断不确定”，与病人的真实变异不是同一概念。<a href="data-lab.html#sbs">在交互练习中逐轮查看示意</a>。</p>`,['os14','illuminaSBS']],
    ['flow cell 与 cluster：为什么一条分子会变成亮点',`<p>带适当接头的文库片段结合到 flow cell 表面。经典 Illumina 过程会在局部扩增形成由同一原始片段衍生的 <strong>cluster / 簇</strong>，让成像信号足够强。这里的许多拷贝不等于许多独立起始 RNA 分子。</p><p>cluster 密度、模板纯度和扩增偏差会影响读数；平台和 flow cell 的具体实现会变化，但“空间上分开并并行读取大量片段”是这类测序的关键。</p>`,['illuminaGlossary','illuminaSBS']],
    ['SBS 一轮做什么',`<ol><li>聚合酶在每个 cluster 的新链上加入一个可识别的核苷酸。</li><li>临时阻断使本轮通常只前进一步；仪器拍摄信号并对该位置调用 A/C/G/T。</li><li>解除荧光标记与阻断，再进入下一轮。</li></ol><p>这是理解性的简化；具体染料与通道编码随化学版本变化。一次 cycle 通常给一个 read 增加一个碱基。反复循环，便形成读段序列。</p>`,['illuminaSBS']],
    ['Sanger 与 SBS 为什么都能读出碱基',`<p>两者都利用聚合酶按模板合成互补 DNA，但<strong>如何把顺序变成信号</strong>不同。Sanger 的链终止法混入缺少延长所需 3′-OH 的 ddNTP；每条新链在不同位置停止，按片段长度分开后，末端标记的颜色与长度共同给出碱基顺序。Illumina SBS 在许多 cluster 上并行做逐轮可逆终止、成像和继续延长。</p><p>因此“Sanger 一次读一个目标区域”和“短读长平台并行读大量文库片段”的数据规模与后续拼接问题不同。这里讲的是原理；具体通量和长度随仪器版本变化。<strong>测序不是直接拍下整条染色体</strong>，而是从受实验设计约束的片段信号中推断序列。</p>`,['nhSanger','illuminaSBS']],
    ['read 长度、insert 与 paired-end 不是一个参数',`<p><strong>Read length</strong>是从一个端点读出的碱基数，如 150 bases。<strong>Insert/fragment length</strong>是文库原始插入片段的跨度。paired-end 会从同一片段的两端各读一次，得到 R1 与 R2；它们是一个片段的两个观测，不应在 fragment counting 中自动算两份独立分子。</p><p>较长或双端 reads 能帮助跨剪接位点、重复序列和 isoform 歧义，但并不自动解决所有多重比对。</p>`,['illuminaSBS','illuminaGlossary']],
    ['index read 与 demultiplexing',`<p>样本混合上机时，仪器还读取 index 序列。<strong>Demultiplexing</strong>根据 index 把 reads 分回各样本，输出每个样本的 FASTQ。index 识别错误、污染和样本混淆会影响后续矩阵；所以除了 gene count，也要保留上机与拆分信息。</p><p>R1、R2 和 index read 的用途不同；看到多个 FASTQ 文件，不等于多个独立样本。</p>`,['illuminaGlossary','illuminaWorkflow']],
    ['质量 Q 分数不是“正确率百分数”',`<p>Phred 风格质量分数定义为 <code>Q = −10 log10(P(error))</code>。Q20 对应估计碱基错误概率 1%，Q30 对应 0.1%，Q40 对应 0.01%。它衡量单次 <em>base call</em> 的不确定性；mapping quality、变异调用置信度又是其他概念。</p><p>某个变异位点即使单碱基 Q 高，也仍需考虑覆盖、链偏好、比对歧义、肿瘤纯度和匹配正常样本。</p>`,['illuminaQ','gdcDNA']],
    ['短读长之外：长读长如何形成',`<p>PacBio HiFi 通过对同一环状模板多次观察形成 consensus；Oxford Nanopore 根据单分子通过孔道时的电流变化做 basecalling。长 reads 常更有利于跨越复杂结构或完整 transcript，但准确度、吞吐、输入材料和分析方法取决于具体平台与版本。</p><p>“long-read RNA-seq”也要核对测的是 cDNA 还是直接 RNA；常见 Illumina RNA-seq 的逆转录步骤不能套用到所有平台。</p>`,['pacbioHiFi','nanoporeTech']]
  ],worked:['用 4 次 cycle 读一条示意链',['模板按 3′→5′ 写作 T-G-C-A。','第 1 轮加入互补 A，成像并解除阻断；新链目前为 A。','依次再加入 C、G、T；四轮后示意 read 为 5′-ACGT-3′。','每一位还附质量分数；真实读数还要经过样本拆分与质量检查。']],terms:[['Sequencing by synthesis / SBS','通过逐轮合成与信号检测推断碱基序列。','illuminaSBS'],['Cluster / 簇','同一起始文库片段在局部扩增形成的信号来源。','illuminaGlossary'],['Phred Q','用对数尺度表示碱基调用错误概率的质量分数。','illuminaQ']],check:['150 bp paired-end 是两位患者各贡献一条 150 bp read 吗？','不是。通常指同一文库片段两端各读约 150 个碱基；这两个 reads 仍属于同一片段。']},

  {id:'q03',title:'FASTQ：序列和质量值怎么读',subtitle:'一条 read 不只是 A/C/G/T 字符串。',intro:'测序仪经过 basecalling 与样本拆分后，常把未比对 reads 交给分析人员。FASTQ 是第一个常见的可计算对象；读懂它，才能理解后续“过滤”和“比对”到底删改了什么。',goals:['拆开 FASTQ 的四行','算出 Q30 对应的错误概率','区分读段 QC 与样本 QC'],prereq:['q02'],flow:[['header','read 标识'],['sequence','调用的碱基'],['+','分隔符'],['quality','每个位置的质量字符']],sections:[
    ['四行是一条记录',`<p>教学示意：</p><pre class="lesson-code">@read_001\nACGT\n+\nIIII</pre><p>第一行是 read 标识；第二行是调用的序列；第三行以 <code>+</code> 开始；第四行为每个碱基保存一个质量字符。这里 4 个序列碱基对应 4 个质量字符。真实 header 可能含仪器、run、lane 和配对端等信息；不要从文件名直接推断患者身份。</p>`,['hts','illuminaQ']],
    ['质量字符与概率',`<p>常见 Phred+33 编码把一个整数 Q 映射为 ASCII 字符；教学示意里的 <code>I</code> 对应 Q40。Q40 代表模型估计错误概率 <code>10^-4</code>，不是说这一碱基必然正确。不同历史数据可能用不同编码，应核对生产平台和元数据。</p><p>四个高 Q 碱基组成的 read 仍可能来自污染、错误样本，或无法唯一定位到参考基因组。</p>`,['illuminaQ','hts']],
    ['为什么要查每个 cycle 的质量',`<p>质量常随读段位置变化：后段可能出现更多低质量调用、接头序列或短插入片段相互重叠。QC 图通常看每碱基质量、接头、GC 分布、序列重复、rRNA 或污染比例等。异常是诊断线索，不是一个统一的“保留/删除”开关。</p><p>剪接头与低质量尾部会改变 read 长度和可比对性；过滤前后应保留读段数及理由。</p>`,['illuminaQ','gdcRNA']],
    ['R1/R2 与 gzip',`<p>双端测序的 R1、R2 文件按 read pair 对应；两端名称、顺序和数量要一致。<code>.fastq.gz</code>只是压缩的 FASTQ，并不表示已过滤或已比对。同一样本还可能跨多个 lane 产生多个文件，合并前要核对 read group 与 index。</p><p>把 R1 与另一个患者的 R2 配对，可能造成大量异常比对；这属于数据管理错误，不是生物现象。</p>`,['illuminaGlossary','gdcRNA']],
    ['读段级 QC 与病例级 QC 各回答什么',`<p>读段级 QC 问“这段序列与碱基信号可不可靠”。病例级 QC 问“该病例的文库、组织和数据是否适合本研究”。一个样本可以有漂亮的 Q30 却组织标错、肿瘤纯度低，或取样时间与任务不符。</p><p>先保存每一步 read 数、样本映射、参考版本与 QC 报告；后续看到离群样本，才能回溯是哪一层发生问题。</p>`,['illuminaQ','gdcDictionary']]
  ],worked:['解释示意 FASTQ 的 I 字符',['序列为 ACGT，质量行也有四个字符。','若使用 Phred+33，I 的 ASCII 值为 73，因此 Q=73−33=40。','按 Q 公式，单碱基调用的估计错误概率约为 0.0001。','这不是 read 的比对质量，也不等于“4 个碱基完全无错”的保证。']],terms:[['FASTQ','并列保存读段序列及逐碱基质量信息的常见文件格式。','hts'],['Basecalling / 碱基调用','把仪器信号转换成核苷酸序列及质量估计。','illuminaQ'],['Read pair / 读段对','从同一文库片段两端获得的两个读段。','illuminaGlossary']],check:['FASTQ 的质量行能告诉你 read 必定来自 gene X 吗？','不能。它描述碱基调用不确定性；gene 归属还要比对或定量，并检查注释与多重映射。']},

  {id:'q04',title:'从 FASTQ 到 gene count：比对与定量',subtitle:'“给基因计数”是一套算法规则，不是仪器直接输出。',intro:'短读段来自长分子的一部分；把它们接回基因，需要参考序列、基因注释和歧义处理。不同流程都可生成名为 count 的列，但其对象和规则可能不同。',goals:['区分 genome alignment 与 transcript quantification','解释 splice junction 与 multi-mapping','说明 gene count 如何受注释版本影响'],prereq:['q03','m04'],flow:[['FASTQ','序列与 Q'],['reference','genome/transcriptome + annotation'],['assignment','唯一、歧义或未分配'],['matrix','gene/transcript × sample']],sections:[
    ['参考基因组与注释是两套输入',`<p>参考基因组给出 DNA 序列和坐标；GTF/GFF 等注释描述哪些区间属于 gene、transcript、exon。RNA read 跨越剪接位点时，两个端点可能落在相距很远的基因组位置；RNA 比对器需要识别 exon–exon junction。</p><p>改用另一 build 或 GENCODE 版本，会改变可比对位置、可分配的基因和长度定义。跨研究比较前要核对这些版本。</p>`,['gdcRNA','gencode']],
    ['比对、伪比对和分配不是同一步',`<p>传统流程把每个 read 或 read pair 放到 genome 上，输出 BAM，再按基因区间计数。另一类流程利用转录本序列进行快速兼容性判断并估计 transcript abundance，随后汇总到 gene。二者都依赖参考集合及算法规则；它们的 counts 不一定逐项相同。</p><p>GDC 当前 RNA 协调流程给 gene-level STAR raw counts，也提供 FPKM/TPM 等派生列。下载时要记录 workflow type 与数据 release。</p>`,['gdcRNA','tximportGuide']],
    ['multi-mapping：一个片段可同时“像”多个位置',`<p>重复序列、基因家族和共享 exon 会让 read 匹配多个位置。流程可能丢弃、分数分配或用统计模型估计其来源。于是一个 0 既可能是没有分子，也可能是 reads 无法唯一归属。分配规则还可能产生非整数 estimated counts。</p><p>做免疫受体、假基因、融合或 isoform 分析时，歧义处理尤其重要；不要把不同 quantifier 的 count 表直接拼接。</p>`,['samSpec','tximportGuide']],
    ['gene 与 transcript 是不同的计数对象',`<p>一个 gene 可产生多种 transcript。落在共享 exon 的 read 往往不能独自告诉你它来自哪个 isoform；跨特异 exon 或剪接 junction 的 reads 才提供更多区分信息。算法估计 transcript abundance 后再求 gene 总量，可能用到每个样本的<strong>effective transcript length</strong>。</p><p>当 isoform 比例变化时，同一 gene 的“有效长度”也会改变；这正是从 transcript 结果推到 gene-level 差异分析时需要留意的地方。</p>`,['nhSplice','tximportGuide']],
    ['一个 paired-end fragment 应如何计数',`<p>若 R1 和 R2 来自同一片段，fragment-level counting 通常将这对读段作为一个片段证据，不能简单加成两份独立观察。single-end 常按 read 计数；paired-end 常按 fragment 计数。文件头和流程文档必须确认具体实现。</p><p>下游 FPKM 中的 F 就是 <em>fragments</em>；RPKM 中的 R 是 <em>reads</em>。这两个名称在双端数据里不能随意替换。</p>`,['gdcRNA','illuminaGlossary']],
    ['输出矩阵至少贴五个标签',`<p>对每列记录 sample/aliquot、文库方案、single/paired 与链特异性、参考 build、注释与定量器版本；对数值记录 read 或 fragment、raw 或 estimated、是否按 gene/transcript 汇总。没有这些标签，“gene X=100”只是一个孤立数字。</p><p><a href="textbook.html#q05">下一章</a>开始解释为什么同样 100 个 counts 在不同文库中不能直接比较。</p>`,['gdcRNA','gdcDictionary','tximportGuide']]
  ],worked:['读一条跨 exon 的 read',['在转录本上，它可能是连续的 100 bases。','在基因组上，前 50 bases 与后 50 bases 之间可能隔着一个内含子。','spliced aligner 识别 junction；再根据注释决定是否可归到 gene X。','若多个 transcript 共享该 junction，gene-level 计数较直接，isoform 归属仍可能不确定。']],terms:[['Spliced alignment','允许 RNA read 跨 exon–exon junction 与参考基因组对齐。','gdcRNA'],['Multi-mapping','一个读段或片段可匹配多个参考位置。','samSpec'],['Effective length','定量时考虑可产生可观测片段的转录本长度。','tximportGuide']],check:['同一 FASTQ 用不同注释版本得到不同 gene count，是否一定是软件 bug？','不一定。gene/transcript 边界与可分配对象发生变化，count 也可能合法地变化；应记录和比较版本。']},

  {id:'q05',title:'Raw count 与 CPM：先校正测序深度',subtitle:'先学会除以什么，再决定数字能不能比。',intro:'raw count 是给某个 feature 分配到的读段或片段数。它受测序深度和文库组成影响。CPM 是最直观的文库规模校正，但仍是样本内部的相对比例。',goals:['手算 CPM','区别深度变化与组成变化','解释为什么 CPM 不是差异表达检验'],prereq:['q04','k04'],flow:[['raw count','分配给基因的片段'],['library denominator','选定的总计数'],['CPM','每百万比例'],['解释','仍受组成偏差影响']],sections:[
    ['同一比例，raw count 可以不同',`<p>样本 A 的 gene X 有 100 counts，总可用 counts 为 1,000；样本 B 的 gene X 有 200 counts，总数为 2,000。B 的 raw 是 A 两倍，但 gene X 在两个样本中都占 10%。只看 raw 会把更深的测序误读为表达增加。</p><p>这个例子假设两个样本经历可比流程，且所有相关 feature 被同样纳入；真实实验还要看长度、RNA 组成与生物重复。</p>`,['gdcRNA','deseq2Guide']],
    ['CPM 公式：分母是哪个总数',`<div class="lesson-formula">CPM<sub>ij</sub> = count<sub>ij</sub> ÷ N<sub>j</sub> × 1,000,000</div><p><code>i</code> 是 gene，<code>j</code> 是 sample，<code>N_j</code> 是明确定义的库规模。这里的玩具矩阵把<strong>所有纳入的基因 count 之和</strong>设为 N，所以 A：100/1,000×10⁶=100,000 CPM；B：200/2,000×10⁶=100,000 CPM。只有当分母恰好是这张表中所有 feature 的 count 总和时，该表的 CPM 列才加起来等于 1,000,000；若分母用全部测序 reads 等其他范围，表中基因的 CPM 总和不一定是 1,000,000。</p><p>真实数据要先区分全部 reads、已比对 reads、分配到基因的 reads 或 fragments。GDC STAR TSV 开头的 <code>N_unmapped</code> 等 <code>N_*</code> 是诊断行，不是基因；不能不加区分地把整列数字求和当作“基因总 count”。CPM 是在原始数据上自行定义和计算的尺度，记录分母及 feature 集合才可复现。</p>`,['gdcRNA','tmmPaper']],
    ['为什么用“每百万”而不是百分数',`<p>CPM 与百分比都表达份额；乘 10⁶ 让小比例的数字更好读。例如 0.0005 的比例是 500 CPM。这个倍数本身不增加信息，也不使读数成为每个细胞的分子数。</p><p>CPM 可帮助做概览、表达过滤或简单可视化；用于比较时仍要考虑计数方差、低表达噪声与组间重复。</p>`,['tmmPaper','deseq2Guide']],
    ['组成偏差：一个基因大增会“挤小”其他基因',`<p>教学矩阵中 gene A/B 的 raw counts 在两个样本都是 100/200，但 gene C 从 700 增到 1,700，库总数从 1,000 变 2,000。A 的 CPM 从 100,000 降到 50,000，虽然它的 raw 没变。这是<strong>closure / 组成约束</strong>：份额加起来固定，某一部分增大，其余份额会变小。</p><p>因此 CPM 不能区分“ A 真变少”与“ C 占去更多文库”；<a href="data-lab.html#normalization">交互表</a>可切换不同尺度观察。</p>`,['tmmPaper','tpmPaper']],
    ['CPM 何时不足以做组间结论',`<p>单个样本没有“组内变异”的估计。即使两个 CPM 相差两倍，若样本来自不同患者、组织纯度不同或一组只有一位患者，也无法靠比值判断稳定差异。低 count 的随机波动尤其大。</p><p>用于正式差异表达时通常需要独立生物重复、过滤极低表达、明确定义设计矩阵，并用能建模 count 离散度的统计流程。</p>`,['deseq2Guide','deseq2']],
    ['CPM 仍没有解决基因长度',`<p>若同一文库中 gene L 的可测转录本是 gene S 的两倍长，即使每种转录本的分子数相同，L 也可能产生更多可分配片段。CPM只校正总量，没有除以长度；比较<strong>同一样本中不同基因</strong>的相对转录本丰度，通常还要考虑长度。</p><p>但同一个 gene 在两个样本间做 count-based 差异分析时，若长度稳定，它是两边共同因素；不应机械地先转 TPM 再送进 DESeq2。</p>`,['gdcRNA','deseq2Guide','tximportGuide']]
  ],worked:['手算深度例与组成例',['深度例：X=100/1,000 和 200/2,000，CPM 都为 100,000。','组成例：A=100/1,000 和 100/2,000，CPM 从 100,000 到 50,000。','第二例的 A raw 未变；不能单凭 CPM 下降判定其绝对 RNA 减半。','回到问题：你要描述样本组成，还是估计组别对 gene A 的影响？两者需要不同方法。']],terms:[['Raw count','根据参考与定量规则归给 feature 的原始读段或片段数。','gdcRNA'],['CPM','按选定文库总量缩放的每百万计数。','tmmPaper'],['Composition bias / 组成偏差','某些高丰度 RNA 占比变化导致其他 RNA 的相对份额改变。','tmmPaper']],check:['gene A 的 raw count 在两样本都是 100，但 CPM 从 100,000 降为 50,000，能直接说细胞内 A 减半吗？','不能。文库总量或组成改变就能造成这一现象；CPM 是相对比例。']},

  {id:'q06',title:'RPKM、FPKM、TPM：为什么还要除以长度',subtitle:'同一组数字，用不同归一化方式回答不同问题。',intro:'长 transcript 比短 transcript 有更多机会产生可测片段。RPKM/FPKM 与 TPM 都处理长度和文库规模，但计算顺序与总和约束不同。先按一个极小、虚构的矩阵手算，才容易看清它们各自保留和丢失了什么。',goals:['写出 RPKM/FPKM 与 TPM 公式','解释读段和片段的区别','比较 TPM 与 CPM、RPKM 的限制'],prereq:['q05','q04'],image:['assets/normalization-map.svg','原创归一化概念图：raw count、CPM、RPKM/FPKM、TPM 和模型 size factor 分别处理不同偏差','图中公式是教学简化，gene/transcript 的有效长度及软件实现需核对实际流程。',['gdcRNA','tpmPaper','deseq2Guide']],sections:[
    ['为什么长度影响计数',`<p>假设两种 transcript 每个样本都有 100 个分子，但一个可测部分长 1 kb，另一个长 2 kb。在相同的随机取片和覆盖条件下，较长者可产生的片段机会更多，raw count 可能较大。为了估计不同 transcript 在<strong>同一样本</strong>中的相对丰度，需要把 count 与可测长度联系起来。</p><p>“长度”在真实定量中可能是 effective length，受 read/fragment 长度、isoform 和流程影响；不是随手从数据库抄一个基因跨度。</p>`,['gdcRNA','tximportGuide']],
    ['RPKM 与 FPKM：先除总量，再除长度',`<div class="lesson-formula">RPKM 或 FPKM = C<sub>i</sub> ÷ ( L<sub>i,kb</sub> × N<sub>million</sub> )</div><p><code>C_i</code> 是分配给该 feature 的 reads（RPKM）或 fragments（FPKM）；<code>L_i,kb</code> 是流程定义的 feature 长度，以 kb 计；<code>N_million</code> 是相应的文库规模，以百万计。<strong>长度不能随手用“基因从起点到终点的跨度”代替：</strong>GDC 的 gene-level 转换用其流程确定的基因长度，而 Salmon/tximport 等转录本流程可用考虑片段与 isoform 的 effective length，两者定义须分别查文档。paired-end 时同一 fragment 的两端不是两个独立 fragment。</p><p>这类尺度尝试减轻深度和长度影响；但每列 RPKM/FPKM 总和通常不固定，相同数字并不能自动保证跨样本具有相同组成含义。</p>`,['gdcRNA','tpmPaper','tximportGuide']],
    ['TPM：先除长度，再让总和成为一百万',`<div class="lesson-formula">r<sub>i</sub> = C<sub>i</sub> ÷ L<sub>i,kb</sub><br>TPM<sub>i</sub> = r<sub>i</sub> ÷ Σ<sub>g</sub> r<sub>g</sub> × 1,000,000</div><p>第一步生成 length-adjusted rate；第二步在同一样本的所有纳入 feature 中归一化，所以每列 TPM 约为 1,000,000（显示值因四舍五入略有差别）。与 RPKM/FPKM 相比，TPM 先固定长度校正后的总量，便于描述样本内部组成。</p><p>“transcripts per million”是相对丰度单位，不是精确数出一百万个真实 RNA 分子。</p>`,['tpmPaper','gdcRNA']],
    ['用三行矩阵亲手算',`<p>以下纯教学矩阵假设 A、B、C 就是全部纳入 feature，长度定义一致；计算 RPKM 或 FPKM 时还分别假设计数单位与文库总量同为 reads 或同为 fragments。它不是 GDC 文件中的真实表达值。</p><div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>Gene</th><th>假设长度</th><th>S1 raw</th><th>S2 raw</th></tr></thead><tbody><tr><td>A</td><td>1 kb</td><td>100</td><td>100</td></tr><tr><td>B</td><td>2 kb</td><td>200</td><td>200</td></tr><tr><td>C</td><td>1 kb</td><td>700</td><td>1,700</td></tr><tr><th>总 count</th><th>—</th><th>1,000</th><th>2,000</th></tr></tbody></table></div><p>S1 的 length-adjusted rates 是 100、100、700，总数 900；所以 A TPM≈100/900×10⁶≈111,111，B 也是 111,111。S2 的 rates 为 100、100、1,700，总数 1,900；A TPM≈52,632。A 的 raw 没变，TPM 却变小，原因是 C 的<strong>观测 count</strong> 改变了相对组成；这张表本身不能说明 C 在每个细胞中的绝对分子数如何改变。</p><p><a href="data-lab.html#normalization">打开可切换的完整数表</a>。</p>`,['gdcRNA','tpmPaper']],
    ['为何 RPKM/FPKM 与 TPM 数字不同',`<p>以上矩阵中，S1 的 A RPKM/FPKM=100/(1×0.001)=100,000；S2 为 100/(1×0.002)=50,000。A 的 TPM 则约 111,111 与 52,632，因为两种方法的第二个分母不同。S1 的 RPKM/FPKM 列总和是 900,000，S2 是 950,000；TPM 两列都约 1,000,000。</p><p>不要比较一个文件的 TPM 与另一文件的 FPKM 数字；也不要把“FPKM-UQ”当作普通 FPKM。GDC 提供这些不同列，使用时要保留列名与管线版本。</p>`,['gdcRNA','tpmPaper']],
    ['FPKM-UQ：为什么 GDC 还有一个上四分位版本',`<p>普通 FPKM 把总测序量放进分母，少数极高表达基因可能让总量变化明显。GDC 的 <strong>FPKM-UQ</strong> 改用蛋白编码基因计数分布中第 75 百分位的基因，再结合所纳入的常染色体蛋白编码基因数，构造库规模项。直觉是以分布中较稳健的位置代表样本规模，减少极端高值的影响。</p><div class="lesson-formula">GDC FPKM-UQ<sub>i</sub> = count<sub>i</sub> × 10<sup>9</sup> ÷ (length<sub>i,bp</sub> × UQ<sub>sample</sub> × G)</div><p><code>UQ_sample</code> 是此样本位于第 75 百分位的蛋白编码基因 count；<code>G</code> 是公式使用的常染色体蛋白编码基因数。GDC 文档示例取 count=1,000、长度=3,000 bp、UQ=2,000、G=19,029，得到约 8.76。这个分母<strong>不是</strong>普通 FPKM 的总 mapped reads。</p><p>FPKM-UQ 仍是相对表达量：它不恢复每个细胞的绝对 RNA 数，不替代病例重复或差异表达模型，也不能与普通 FPKM/TPM 当成同一列数值拼接。feature 集合与缩放常数以 GDC 所下载文件的版本为准。</p>`,['gdcRNA']],
    ['TPM 能比较什么，不能比较什么',`<p>在相同定量流程、相近文库方案与一致 feature 集合下，TPM 可描述样本内和样本间的<strong>相对 RNA 组成</strong>。但是所有 TPM 加起来固定；若大量 RNA 同时变化、肿瘤纯度不同、目标 panel 不同或长度估计不一致，某基因 TPM 的变化不能直接解释为每细胞绝对分子数变化。</p><p>TPM 也没有给出生物重复、离散度或组别模型。因此它本身不是正式差异表达的 p 值，也通常不是直接输入 DESeq2 的数据。</p>`,['tpmPaper','deseq2Guide','gdcRNA']],
    ['gene-level 长度会被 isoform 比例改变',`<p>一个 gene 可以有短、长两种 transcript。若 S1 以短 isoform 为主、S2 以长 isoform 为主，就不存在一条对所有样本都正确的固定“gene length”。用 transcript 定量汇总到 gene 时，tximport 可保留样本特定 effective length 的 offset，或生成适合下游模型的 length-scaled counts。</p><p>3′ tag/UMI 实验并非全长均匀取片，盲目按基因长度校正反而可能引入偏差；具体做法以 assay 和工具文档为准。</p>`,['tximportGuide','nhSplice']]
  ],worked:['算出 gene B 在 S1 的四种尺度',['S1：B raw=200；长度=2 kb；文库总 count=1,000。','CPM=200/1,000×10⁶=200,000。','RPKM/FPKM=200/(2×0.001)=100,000。','length-adjusted rate=200/2=100；全列 rate=900，TPM≈111,111。','四个数都描述同一份数据，但分母不同；标注单位才有意义。']],terms:[['RPKM','reads per kilobase per million；按读段、长度和文库总量缩放。','tpmPaper'],['FPKM','fragments per kilobase per million；与 RPKM 类似但按片段。','gdcRNA'],['TPM','先做长度相关校正，再让每样本纳入特征的总和为一百万。','tpmPaper']],check:['gene A 的 TPM 从 111,111 变成 52,632，能否仅凭此断定 A 的绝对分子数减少？','不能。示意矩阵中 A raw 保持 100，只是 C 大幅增多；TPM 的分母跟着改变。']},

  {id:'q07',title:'DESeq2 size factor 与 edgeR TMM：处理组成偏差',subtitle:'正式组间比较不只“把每列总和调成一样”。',intro:'CPM/TPM 的固定总量会受少数高丰度 feature 影响。差异表达流程常估计一个相对有效文库规模，再用计数模型结合生物重复评估组别效应。本章拆解两个常见方法的思路，不把算法名字当魔法。',goals:['手算一个极小 median-of-ratios 例子','理解 TMM 的 trimmed 比值思想','区分归一化、统计模型和批次调整'],prereq:['q05','q06','r03'],flow:[['raw counts','保留离散测量'],['size factors','估计相对规模'],['model','组别 + batch + dispersion'],['result','log2FC、误差与 FDR']],sections:[
    ['相对文库规模不是总 RNA 的绝对量',`<p>没有外加参照时，测序通常只给“样本内被观察的 RNA 组成”。若某肿瘤每细胞所有转录本都翻倍，仅靠固定总 reads 的标准 RNA-seq 很难判断绝对增量。常规 size factor 估计借助“多数基因不发生同向剧变”等假设得到<strong>相对规模</strong>。</p><p>当全转录组广泛改变、细胞大小变化或 panel 很窄时，这些假设需要特别检验；外加 spike-in、细胞数或其他绝对参照可帮助设计更合适的问题。</p>`,['tmmPaper','deseq2Guide']],
    ['DESeq2 median-of-ratios 的三步',`<ol><li>每个 gene 先跨样本取几何平均，构成一个虚拟参考列。</li><li>把每个样本的该 gene count 除以参考值，得到比率。</li><li>对可用 gene 的比率取中位数，得到该样本的 size factor；模型内用它调整期望计数。</li></ol><p>这避免让极少数非常高的基因独自决定总量。默认 <code>ratio</code> 方法中，只要某基因在任一样本为 0，跨样本几何平均就为 0，该基因不用于这个比率；若所有基因都遇到这种情况，默认方法无法估计 size factor。DESeq2 提供 <code>poscounts</code>、<code>iterate</code> 等替代方法，应按 assay 与文档选择，不要擅自把零改成 1。<a href="https://bioconductor.org/packages/release/bioc/manuals/DESeq2/man/DESeq2.pdf" target="_blank" rel="noopener noreferrer">DESeq2 官方手册 ↗</a></p>`,['deseq2Guide','deseq2']],
    ['三基因例子：总 count 两倍，size factor 却相同',`<p>继续用 A=100/100、B=200/200、C=700/1,700 的两列矩阵。A 与 B 的几何平均分别是 100、200，因此两个样本在 A/B 上的比率都为 1。C 的参考约为 √(700×1,700)=1,091，其比率约为 0.64 与 1.56。三项比率取中位数，两个样本都得到<strong>size factor≈1</strong>。</p><p>它反映“多数 gene 没变”的教学假设；只有三个 gene 不能做真实、稳健的差异推断。用它可直观看出为何按总数 CPM 会把 A/B 错看成下降。</p>`,['deseq2Guide','tmmPaper']],
    ['TMM 的直觉：别让极端基因定义全局缩放',`<p>edgeR 的 <strong>TMM / trimmed mean of M-values</strong>比较两个样本的 log expression ratios，去掉比率极端或丰度极端的 feature，再计算加权平均，从而估计组成校正因子。它同样依赖足够多可比 feature 与多数未差异的合理性。</p><p>它不是“给每个基因都除以同一个神奇常数后就完成统计”；effective library size 进入后续模型，仍需要重复、离散度和设计矩阵。</p>`,['tmmPaper']],
    ['为什么 DESeq2 通常输入原始 counts',`<p>DESeq2 通过负二项模型描述计数的均值与变异，并在模型里估计 size factor。其常规输入是未预先做 CPM、TPM、FPKM 或 log 变换的 counts；若来源是 Salmon 等 transcript estimated counts，应遵循 tximport/tximeta 的特定导入路径与长度 offset/调整方式，而非把任意 TPM 表硬塞进去。</p><p>先变成 TPM 再做一般 count 检验，会破坏输入与模型假设的对应关系。看清“软件需要什么”和“画图想展示什么”是两件事。</p>`,['deseq2Guide','tximportGuide']],
    ['归一化 ≠ batch correction ≠ 统计显著性',`<p>size factor 主要处理有效文库规模；它不会消除医院、仪器、取样和组织纯度造成的系统差异。若 batch 与组别都已知，可在设计中表示，如 <code>~ batch + condition</code>；如果组别与 batch 完全重合，就没有足够信息单独估计两者效应。</p><p>统计结果还依赖每组独立患者数、离散度、效应方向、置信度和多重检验。单次样本的 normalized count 差一倍并不能替代这些条件。</p>`,['deseq2Guide','tmmPaper','gdcDictionary']],
    ['注意原始 counts 和 estimated counts 的例外',`<p>gene-level read assignment 常给整数 raw counts；transcript quantifier 可输出小数 estimated counts。tximport 既可传 estimated counts 与 length offset，也可生成适合下游模型的 abundance-scaled count-like 数据。它们不是直接使用原始 TPM 当 DESeq2 count。</p><p>对 3′ tagged RNA-seq，基因长度校正可能不合适；对单细胞，应按 assay 与供体层级选择专门流程。通用建议必须附上输入数据的生成方法。</p>`,['tximportGuide','deseq2Guide']]
  ],worked:['为什么 CPM 和 median-of-ratios 看法不同',['在示意矩阵中，S2 总 count 因 C 增加而翻倍。','CPM 把 A/B 都除以 2,000，使它们数值减半。','median-of-ratios 依多数稳定 gene A/B 估计两个 size factors 都约为 1。','这个 toy 只说明校正思路；真实组间检验要更多基因及独立生物重复。']],terms:[['Size factor / 规模因子','模型用于估计样本相对有效文库规模的量。','deseq2Guide'],['Median-of-ratios','按 gene 与虚拟参考的比率中位数估计 size factor。','deseq2Guide'],['TMM','裁剪极端 log 比率后估计组成校正因子的办法。','tmmPaper']],check:['DESeq2 size factor 已校正，是否说明医院批次和肿瘤纯度也自动被消除了？','没有。它主要处理相对文库规模；batch、纯度等要靠设计、协变量、分层和实验安排处理。']},

  {id:'q08',title:'log、VST、z-score 与批次：不要叫成同一种 normalization',subtitle:'图上看起来都“更平滑”，数学任务却不同。',intro:'从 counts 到热图、PCA 和模型输入，研究者常做对数、方差稳定、按 gene 标准化和批次处理。每一步都改变数值语义；保存原始矩阵与参数，才能解释结果。',goals:['解释 log1p 与 VST 的目的','区分 z-score 与表达量','区分 batch adjustment 与文库规模归一化'],prereq:['q07','k06'],flow:[['count + scale factor','相对文库大小'],['log/VST','压缩或稳定变异'],['z-score','每基因相对高低'],['batch model','处理已知技术差异']],sections:[
    ['log 变换压缩动态范围',`<p>gene counts 可以从 0 到数十万；若直接画图，少数高值支配尺度。<code>log2(x+1)</code>或自然对数 <code>log1p(x)</code>把大值压近，使中低范围更可见。<code>+1</code>是处理零的 pseudocount，但它会显著影响很小的数。</p><p>log 后的 1 不再代表 1 read；“log1p TPM”与“log2 normalized count+1”也不是同一个单位。写图注必须注明底数、pseudocount 和输入尺度。</p>`,['deseq2Guide','gdcRNA']],
    ['VST/rlog 是为探索数据服务',`<p>RNA count 的方差往往随平均值变化。DESeq2 的 variance stabilizing transformation（VST）和 rlog 利用模型信息，试图让不同表达水平的变异更适合 PCA、聚类或样本距离图。它们不等于计数统计检验的输入，也不保证完全去掉批次。</p><p>如果在训练/测试框架下使用数据驱动变换，参数拟合应限定在训练集内，再应用到测试集，避免泄漏。</p>`,['deseq2Guide','sklearnLeak']],
    ['z-score 回答“本 gene 在队列里偏高吗”',`<div class="lesson-formula">z<sub>ij</sub> = (x<sub>ij</sub> − mean<sub>i</sub>) ÷ sd<sub>i</sub></div><p>按 gene 标准化后，每行通常均值为 0、标准差为 1。热图中红色可表示“gene A 相对它自己在本队列的平均偏高”，并不能说明 A 比 gene B 的绝对表达更高。加入或删除样本会改变 mean/sd，从而改变颜色。</p><p>只有训练集估计的 mean/sd 才能用于独立测试集；在全队列上先 z-score 再分训练/测试属于数据泄漏。</p>`,['sklearnLeak','deseq2Guide']],
    ['batch、纯度和细胞混合不是一个问题',`<p>文库规模是计数机会的差异；batch 可能是建库日期、仪器或中心；肿瘤纯度是材料的生物组成。它们都能影响矩阵，但处理方式不同。随机化与记录批次最优先；统计模型可以纳入已知 batch，批次校正图像/矩阵时还要防止抹去真实生物信号。</p><p>若所有 tumor 来自中心 A、所有 normal 来自中心 B，无法从数据中分开“疾病”与“中心”。任何 normalization 都不能凭算法制造缺失的对照设计。</p>`,['deseq2Guide','gdcDictionary']],
    ['bulk、单细胞和空间的尺度不可混用',`<p>bulk counts 通常对应组织样本；单细胞 UMI 矩阵对应捕获的细胞或核；Visium bin/spot 与 Xenium 分割细胞又是不同测量对象。单细胞数据稀疏、细胞深度差异大，常有 assay 专用归一化与 QC；无论做哪种图，供体仍是患者级比较的关键重复单位。</p><p>把 bulk TPM 与 single-cell log-normalized counts 合并成一个数值矩阵，既混合单位又混合观测对象。</p>`,['anndata','scanpyQC','visiumMatrix']],
    ['按研究任务保存多份明确命名的矩阵',`<p>一个项目可以同时保留 <code>raw_counts</code>、<code>model_normalized_counts</code>、<code>TPM</code>、<code>vst_for_PCA</code> 和 <code>row_z_for_heatmap</code>。每份都附原始来源、生成代码、gene ID、feature 集合、样本顺序、变换参数及适用目的。</p><p>下游模型读取前加断言：非负？整数？列总和？是否已 log？是否含测试数据估计的参数？这些检查比“统一先 normalize 一遍”可靠。</p>`,['deseq2Guide','sklearnLeak','gdcRNA']]
  ],worked:['一张红色热图到底表示什么',['查看图注：输入是 TPM、normalized counts 还是 VST？','查看是否先按 gene 做 z-score；若是，红色表示该基因在这个队列中相对偏高。','检查队列是否包含训练和测试样本，颜色尺度是否在训练集拟合。','再回到原始或合适的归一化尺度，核对 gene 的实际读数与重复间分布。']],terms:[['Pseudocount','为处理零值而加的小常数，能显著影响低计数的对数变换。','deseq2Guide'],['VST','使 count 的均值与方差关系更适合探索分析的变换。','deseq2Guide'],['Z-score','按一个特征自身的均值和标准差表达相对位置。','sklearnLeak']],check:['热图中 gene A 的红色比 gene B 深，能直接说 A 分子数更多吗？','不能。若按 gene 做了 z-score，颜色只表示各基因相对自身队列均值的位置。']},

  {id:'q09',title:'把测序与归一化接到 TCGA 实际研究',subtitle:'从下载按钮之前开始定义分析表。',intro:'TCGA/GDC 的一个 RNA 文件可以同时含 STAR raw counts、FPKM、FPKM-UQ、TPM 等列。选择哪列，取决于研究问题、分析单位和统计方法；下载后第一件事是核对 data dictionary 与样本层级。',goals:['列出 TCGA RNA 分析的完整检查顺序','为不同任务选择输入尺度','写清结果能够与不能说明的范围'],prereq:['q01','q04','q06','q07','k02','r01'],flow:[['case/sample manifest','谁被测了'],['STAR counts + metadata','数值来自哪条流程'],['QC + cohort','可分析病例'],['方法选择','描述/DE/预测'],['验证与解释','证据边界']],sections:[
    ['先定义病例、样本与比较条件',`<p>例如研究某癌种 primary tumor 与匹配 normal 的 RNA 差异。先按 case 建表，确认每位患者是否真的有两种材料、对应哪一时间点、是否有多个 aliquot。若只有部分患者有配对正常组织，不应把其余病例随意当作配对分析。</p><p>定义终点、纳排和独立患者数后，再取文件；一个患者的多个 RNA 文件不是多个生物重复。</p>`,['gdcDictionary','gdcSample','gdcBarcode']],
    ['确认 GDC 文件的每一列是什么',`<p>GDC 的 mRNA 管线用 STAR 对 GRCh38 比对并给 gene-level raw counts，同时提供 FPKM、FPKM-UQ 和 TPM 等变换；细节与版本以下载文件和当期文档为准。以 STAR gene-count TSV 为例，先识别 <code>gene_id</code>、<code>gene_name</code>、<code>gene_type</code> 等标识列，再区分 <code>unstranded</code>（未按链区分的原始计数）和 <code>tpm_unstranded</code>（对应的 TPM）；<code>stranded_first</code> 与 <code>stranded_second</code> 也是计数列，不应和 TPM 相加。文件开头的 <code>N_unmapped</code> 等诊断行不是基因。核对 workflow、注释、sample type 与 file UUID，才知道两列是否可比。</p><p>“都叫 TCGA”不保证两张表使用同一版处理结果；旧分析对象与新 GDC harmonized 文件可能不一致。<a href="real-cohort-lab.html">在四份经 MD5 核验的真实文件摘录中练习 case/sample/file 与数值列 ↗</a></p>`,['gdcRNA','gdcRepo']],
    ['如果目标是展示一个 gene 的相对丰度',`<p>可在可比文库与相同流程下看 TPM，或用适当的 count-scale 可视化，并报告每位患者的点而非只画均值柱。注明“相对 abundance”，同时展示 tumor purity、组织来源和异常值；不要从 TPM 的倍数推断每个细胞的绝对 RNA 数。</p><p>TPM 的分母是<strong>原流程纳入的完整 feature 集合</strong>：可以从完整 GDC 文件摘出一个基因展示它已计算好的 TPM，但不能只拿少数基因 raw counts 重新归一化后，仍把新数冒充原文件的 TPM。若只比较不同 gene 在同一样本中的表达，长度相关校正更重要；若看同一 gene 跨样本，组成变化仍可能影响 TPM。<a href="https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline/" target="_blank" rel="noopener noreferrer">GDC 对完整基因集的说明 ↗</a></p>`,['gdcRNA','tpmPaper']],
    ['如果目标是正式 differential expression',`<p>保留 GDC 的合适 raw counts，按病例设计对比，检查样本量、低表达过滤、测序 QC、批次与细胞组成。若是成对 tumor/normal，可在统计设计中表示患者配对；若是非配对样本，则不能伪装成成对。DESeq2 等流程在模型内估计有效文库规模与离散度。</p><p>报告 effect size/log2 fold change、调整后的 p 值、方向、独立病例数与设计公式。若用 transcript estimated counts，遵循 tximport 的 offset/长度处理，而不是直接输入 TPM。</p>`,['deseq2Guide','tximportGuide','gdcRNA']],
    ['如果目标是预测患者结局',`<p>先定义诊断或治疗后的 time zero，以及在该时点可得的 RNA 与临床变量。按患者拆分训练/测试；同一患者所有样本与切片要在同一组。缺失填补、特征筛选、标准化、批次处理参数只在训练折估计；测试集最后一次性评估。</p><p>无论用 TPM、VST 还是模型生成特征，都要保证 cohort、标签时间、变换参数和最终评估单位一致。</p>`,['sklearnGroup','sklearnLeak','gdcDictionary']],
    ['每个结果写一张 provenance 卡',`<p>记录：原始文件 UUID 和 release；case/sample/aliquot 映射；组织类型；参考 build 与注释；计数/TPM 列；QC 排除；文库和测序信息；归一化公式或软件版本；模型设计；病例级训练/测试 ID；图中数值的最终单位。这样另一个人才能从结论追回实验。</p><p>把结论分成直接测量、算法分配、统计关联与功能验证四层：RNA 差异可提出机制假设，不能独自证明 enhancer、splicing 或治疗作用的因果方向。</p>`,['gdcRepo','gdcRNA','deseq2Guide']],
    ['按问题选尺度：一页速查',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>目的</th><th>常见起点</th><th>务必再检查</th></tr></thead><tbody><tr><td>看测序与定量</td><td>FASTQ / BAM + QC</td><td>文库、比对、注释</td></tr><tr><td>描述相对 RNA 组成</td><td>TPM</td><td>流程、feature 集与组成偏差</td></tr><tr><td>按基因做组间 DE</td><td>raw/合适 estimated counts</td><td>重复、设计、size factor、离散度</td></tr><tr><td>PCA / 聚类</td><td>VST 等探索尺度</td><td>批次、离群与训练边界</td></tr><tr><td>患者级预测</td><td>预定义特征</td><td>患者拆分、时间与外部验证</td></tr></tbody></table></div><p>这不是“TPM 永远不能比较样本”或“raw count 永远最好”的口号；选择取决于目标和生成数据的 assay。</p>`,['gdcRNA','deseq2Guide','tximportGuide']]
  ],worked:['从 GDC 下载一个癌种后先做什么',['写下问题：例如 primary tumor 与匹配 normal 的 RNA 差异。','按 case/sample/aliquot 关系构建清单，确认独立病例数及配对结构。','读取同一处理流程的 raw gene counts 与 metadata，做 QC。','选择支持该设计的 count 模型，在模型内处理规模与协变量；展示 log2FC/FDR 和病例分布。','保留文件、版本、排除理由及代码，另找验证数据或实验支持。']],terms:[['Harmonized data','经过协调参考与流程处理，便于在规定范围内比较的数据。','gdcDoc'],['Design formula','说明模型中组别、批次与配对等变量的表达式。','deseq2Guide'],['Provenance','把结果追溯到样本、文件、软件和处理参数的记录。','gdcRepo']],check:['GDC 文件同时有 raw count 与 TPM；若做 DESeq2 常规 gene-level 差异表达，应优先检查哪一列？','先确认可用的 raw gene counts 及其计数流程、样本设计；不要直接把 TPM 当作常规 DESeq2 counts。']}
]});
