window.BIOCS_BOOK.push({
  code:'01', title:'遗传学 Genetics', description:'DNA、染色体、遗传规律、重组、变异和群体差异。', chapters:[
  {id:'g01',title:'DNA：四个字母与双链方向',subtitle:'从真实分子走到可以计算的序列。',intro:'DNA 的 A、T、C、G 是碱基缩写；真正的 DNA 是有方向、有化学骨架的双链分子。方向一旦弄错，后面的转录、变异和序列比对都会错。',goals:['认识核苷酸与碱基配对','读懂 5′ 和 3′','求反向互补序列'],prereq:['b03'],flow:[['核苷酸','糖＋磷酸＋碱基'],['单链','有 5′→3′ 方向'],['双链','A–T、C–G 配对'],['序列','计算机中的字符串表示']],sections:[
    ['核苷酸怎样组成 DNA',`<p>一个 DNA 核苷酸含脱氧核糖、磷酸与碱基。核苷酸沿糖—磷酸骨架相连，形成有方向的链。<strong>5′ 端和 3′ 端</strong>是糖上不同碳原子的位置，不是图上的左右标签；书写序列时通常默认从 5′ 到 3′。</p><p>A 与 T 配对，C 与 G 配对，使一条链可提供另一条链的信息。配对是序列规则，实际双螺旋的稳定性还受相邻碱基、盐和温度影响。</p>`,['nhDNA','os14']],
    ['反向平行与 reverse complement',`<p>若上链写作 <code>5′–ATCG–3′</code>，下链对齐时写作 <code>3′–TAGC–5′</code>。如果要把下链也按 5′→3′ 报告，就必须倒过来得到 <code>5′–CGAT–3′</code>。<strong>Complement</strong>只换配对字母；<strong>reverse complement</strong>还要反转书写方向。</p><p>测序读段可能来自任意一条链；比对软件必须允许反向互补。基因组坐标的正负链也因此重要。</p>`,['os14','hts']],
    ['bp 与 nt 为什么不能随手混用',`<p><strong>bp / base pair</strong>常用来描述双链 DNA 上一对碱基占据的一个位置；<strong>nt / nucleotide</strong>数单链上的核苷酸。教学例子中一段 100 bp 的双链 DNA 有 100 个配对位置、两条链各 100 nt。常见短读长 RNA-seq 先把 RNA 转成 cDNA；若所得单端 read 长 150 nt，表示这条测出的单链序列有 150 个位置，并不是仪器直接读取了 RNA 分子。</p><p>生物信息学文件和厂商资料有时把 read length 也写成 bp；阅读时仍要问它说的是单端 read、双端 read pair，还是原始 DNA fragment。长度的对象比缩写本身更重要。</p>`,['osNucleic','illuminaGlossary','illuminaRNAprep']],
    ['DNA 序列能告诉我们什么',`<p>序列可用来找基因、比较个体差异、识别变异，也能预测潜在结合位点。但同一序列在不同细胞中的使用方式可以不同。DNA 没有附带“此刻这个基因正在表达”的状态位；表达要通过 RNA、蛋白或相关实验估计。</p><p>把 DNA 看作“长期保存的信息层”有帮助，但它是细胞内的物理分子，不是能独自运行的程序。</p>`,['nhDNA','nhPhenotype']],
    ["把 DNA 字符串转换成一条 VCF 记录",`<p>想象一个极短的教学参考片段 <code>5′–ATCG–3′</code>，位置从 1 开始编号。若样本第 3 位为 T 而参考第 3 位为 C，单碱基变异可记为 <code>POS=3, REF=C, ALT=T</code>。VCF 的 REF 是所声明<strong>参考基因组在该坐标的序列</strong>，不是“健康人一定具有”的版本；真实记录还需染色体名称和参考版本。</p><p>上例是为了看懂字段而虚构的序列，不能直接当作真实人类 chr 坐标。只有在明确参考序列与方向后，<code>REF/ALT</code> 才能和生物分子对上。</p><details><summary>先猜再展开：参考片段仍是 ATCG，样本是 ATTG，REF 应写 C 还是 T？</summary><p>写 <code>REF=C</code>、<code>ALT=T</code>。REF 根据参考片段决定，ALT 是本条记录报告的另一个 allele；不要把患者样本当成参考。</p></details>`,['os14', 'gdcVCF', 'vcf']]
  ],worked:['手算一条 DNA 的反向互补',['原序列：<code>5′–A T C G–3′</code>。','先逐位互补，对齐写：<code>3′–T A G C–5′</code>。','若输出需要 5′→3′，把顺序反过来：<code>5′–C G A T–3′</code>。']],terms:[['Nucleotide / 核苷酸','DNA 和 RNA 的基本组成单元。','os3'],['Base pair / 碱基对','两条互补 DNA 链上相互配对的碱基。','nhDNA'],['Reverse complement / 反向互补','先求互补，再按相反方向书写序列。','os14']],check:['5′–AAG–3′ 的反向互补是什么？','先写配对链 3′–TTC–5′，再反向得到 <code>5′–CTT–3′</code>。']},
  {id:'g02',title:'Genome、chromosome、gene 与 allele',subtitle:'建立基因组的地址系统。',intro:'“基因”“染色体”和“基因组”不是同义词。计算分析还需要位置、参考版本和标识符，才能把这些概念连接到文件中的行与列。',goals:['画出层级关系','区分 locus 与 allele','拆解 promoter、UTR、exon、CDS','理解参考基因组版本'],prereq:['g01'],image:['assets/genetics-map.svg','原创层级图：细胞核、染色体、DNA、基因、位点和等位基因','比例不代表真实大小。',['nhChrom','nhGene','nhAllele']],sections:[
    ['从整套信息缩小到一个位置',`<p><strong>Genome / 基因组</strong>指一套遗传材料。人类多数体细胞的核内通常有 23 对染色体；每条染色体由长 DNA 与相关蛋白组成。<strong>Gene / 基因</strong>是 DNA 上产生功能性产物的区域，产物可以是蛋白，也可能是功能性 RNA。</p><p><strong>Locus / 位点</strong>描述位置；<strong>allele / 等位基因</strong>描述该位置的某个版本。一个位点在人群中可有多个 allele，一个典型二倍体个体在常染色体位点通常携带两份。</p>`,['nhChrom','nhGene','nhAllele']],
    ['参考基因组不是“标准人”',`<p>测序分析把短读段与一套参考序列比较。坐标必须连同参考版本（例如 GRCh38）一起报告；不然 <code>chr1:1000</code> 只是一个没有地图版本的数字。参考序列是一种共同坐标系统，不等于所有人的真实序列，也不能代表全部人群差异。</p><p>基因标识符也有版本问题。symbol 如 TP53 适合阅读；分析矩阵常用稳定 ID 和注释版本。合并两张表时先核对物种、build、gene ID 与 transcript ID。</p>`,['nhGene','gdcDoc']],
    ['基因有外显子，也可能有多个转录本',`<p>不少人类蛋白编码基因有外显子与内含子。转录后通过剪接形成成熟 RNA；一个基因可产生多个 transcript / 转录本。外显子不全都是蛋白编码区，基因内外的调控序列也可能重要。</p><p>因此“这个变异在基因里”仍不够具体：它在编码区、剪接位点、非编码外显子还是调控区域？对哪个转录本？答案会改变后果预测。</p>`,['os15','nhSplice']],
    ['解剖一条蛋白编码基因的地图',`<p>沿一个教学用正链基因看：<strong>promoter / 启动子</strong>帮助决定何时开始转录；<strong>TSS</strong>是 RNA 开始合成的位置。转录本内部有外显子与内含子；初始 RNA 经剪接去除许多内含子。成熟 mRNA 的外显子又可分成 <strong>5′ UTR</strong>、<strong>CDS / 蛋白编码序列</strong>和 <strong>3′ UTR</strong>。翻译从 start codon 开始，在 stop codon 结束；两者与 TSS、转录终点不是同一个坐标。</p><figure class="concept-figure"><div class="book-image-scroll"><img src="assets/gene-anatomy.svg" alt="原创基因结构图：promoter、TSS、UTR、CDS、exon、intron 到成熟 mRNA" loading="lazy"></div><figcaption>原创教学示意 · 只画一个正链转录本，长度与比例为示意；依据本节 GENCODE 和 OpenStax 来源。</figcaption></figure><p>负链基因在浏览器上可能从右向左转录；“上游”指相对于这个基因的转录方向，不等于屏幕上的左侧。RNA 注释文件分别记录 gene、transcript、exon、CDS 和 UTR，不能把这些行当成同一个对象。</p>`,['gencodeFormat','osTranscription','nhSplice']],
    ['先闭环：同一个 gene X 会留下哪些不同数据',`<p>学到这里就可以先看全局，不必等学完所有遗传概率。假设肿瘤样本中的 <code>gene X</code> 有一段 DNA 序列；细胞若使用它，会转录出 RNA；其中某些 RNA 可指导合成蛋白；蛋白还要折叠、定位或被修饰，才可能改变细胞行为。这是理解数据的<strong>路线图</strong>，不是“DNA 有这个基因就一定产生某种表型”。<a href="#m02">M02 中心法则</a>会拆开箭头，<a href="foundations-lab.html#sequence">互动模型</a>可先亲手改一段序列。</p><div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>想问什么</th><th>可能选择的实验</th><th>表里先看到什么</th><th>不能直接跳到</th></tr></thead><tbody><tr><td>gene X 的 DNA 是否变了？</td><td>DNA-seq</td><td>位点、REF/ALT 与样本证据</td><td>RNA 一定升高</td></tr><tr><td>它的 RNA 读数多少？</td><td>RNA-seq</td><td>gene/transcript count 或 TPM</td><td>蛋白活性已确定</td></tr><tr><td>相关蛋白有多少？</td><td>质谱或经验证的抗体检测</td><td>肽段/蛋白信号</td><td>细胞行为必然改变</td></tr><tr><td>细胞是否改变？</td><td>合适的功能或影像实验</td><td>增殖、死亡、位置等观测</td><td>患者疗效已被证明</td></tr></tbody></table></div><details><summary>先猜再展开：RNA count 高，可否省掉蛋白和功能实验？</summary><p>不能。RNA、蛋白丰度、蛋白活性和细胞行为是不同对象；每一级还受翻译、降解、修饰与环境影响。先写出需要证明的结论，再选真正测到那一层的实验。</p></details>`,['osTranscription','nhTranslation','gdcRNA','nhPhenotype']],
    ['同一个基因为什么有几种长度',`<p>假设一个基因在基因组上跨越 100 kb，其中含较长内含子；某个剪接后的 mRNA 只有 2 kb，而蛋白编码的 CDS 只有 1.2 kb。这三个长度可以同时正确，因为它们分别描述<strong>genomic span</strong>、某条<strong>transcript</strong>和其中的<strong>CDS</strong>。另一个 isoform 还可能改变外显子组合和长度。</p><p>后面计算 TPM/FPKM 时的长度必须与实际定量对象和算法定义对应，常涉及可测的 effective length；不能把基因组跨度直接填进去。<a href="#q06">Q06 会手算长度归一化</a>。</p>`,['gencodeFormat','tximportGuide']],
    ["一个基因为什么会有三种“长度”列",`<p>用 GTF 常见的 1-based、两端都计入的教学坐标：某转录本两个 exon 分别在 100–109 与 200–209。每个 exon 都是 10 nt；拼接后的 exon 总长是 20 nt；从第一个起点到最后一个终点的基因组跨度是 <code>209−100+1=110 nt</code>。若只有其中 12 nt 编码蛋白，则 CDS 长 12 nt。这些数字都可能正确，只是对象不同。</p><p>读表达矩阵的 <code>gene_length</code> 字段时，不要看到基因组 start/end 就自行相减代入 TPM。实际定量会涉及选择的转录本、exon、可比对片段和软件定义的 effective length；先查流程文档。</p><details><summary>先算再展开：这条转录本的 exon 总长是 20 nt 还是 110 nt？</summary><p>是 <strong>20 nt</strong>。110 nt 是 genomic span，其中有未进入成熟转录本的间隔。此例仅训练对象区别，不是建议用 20 nt 作为真实 RNA-seq 的有效长度。</p></details>`,['gencodeFormat', 'tximportGuide', 'gdcRNA']]
  ],worked:['解释一条变异记录前先补齐四个信息',['写明物种与参考 build，例如 human GRCh38。','写明染色体、位置、REF、ALT。','连接到基因和转录本注释版本。','再区分“位于某基因附近”和“已证明影响该基因”。']],terms:[['Chromosome / 染色体','由 DNA 与相关蛋白构成的遗传结构。','nhChrom'],['Gene / 基因','可产生功能性产物的 DNA 区域。','nhGene'],['Allele / 等位基因','某个位点的具体序列版本。','nhAllele']],check:['只写“chr1:1000”为什么不足以重现分析？','因为缺少参考基因组版本及坐标约定；不同版本中的相同数字未必指向同一序列。']},
  {id:'g03',title:'二倍体、基因型与孟德尔模型',subtitle:'把一个位点的两个版本变成可计算的概率。',intro:'遗传学不是“基因决定命运”。孟德尔方格是一种在明确假设下计算子代基因型的模型，适合练习，不适合直接套在所有人类性状上。',goals:['区分 haploid 与 diploid','手填 Aa×Aa 方格','认识外显率与非典型遗传','说出模型前提'],prereq:['g02'],flow:[['父母的 allele','每方通常传一份'],['配子','单倍体'],['受精','两份组合'],['基因型','AA、Aa 或 aa']],sections:[
    ['两份染色体来自哪里',`<p>人类多数体细胞是<strong>diploid / 二倍体</strong>：有两套染色体。形成精子和卵子时，减数分裂产生<strong>haploid / 单倍体</strong>配子；受精后两套结合。在典型常染色体位点，一个人有两份 allele，相同称纯合，不同称杂合。</p><p>基因型是这两份版本的组合，例如 <code>Aa</code>。表型是可观察结果；基因型和表型之间可能隔着很多调控、环境和随机因素。</p>`,['os11','nhGenotype','nhPhenotype']],
    ['同源染色体和姐妹染色单体不是一对同义词',`<p>一个常染色体位点的两份 allele 通常位于一对<strong>同源染色体</strong>上，一条来自每位生物学亲本。细胞在 S 期复制 DNA 后，每条染色体暂时含两条<strong>姐妹染色单体</strong>。这是同一条染色体复制所得的两份 DNA；不能把复制后的四条染色单体误认成四位亲本或四种 allele。</p><p>DNA 总量可在细胞周期中翻倍，而典型细胞在分裂前仍被称为二倍体。肿瘤细胞还可能有非整倍体或局部拷贝数变化，所以分析肿瘤 VAF 时不能机械假定每个位点恰好两份。</p>`,['os10','os11','nhCNV']],
    ['Aa × Aa 怎样得到 1:2:1',`<p>若两个亲本均为 <code>Aa</code>，且每个配子以相同概率得到 A 或 a，则组合有 AA、Aa、aA、aa 四种等概率情况。Aa 与 aA 表示同一种基因型，所以比例是 <strong>1 AA : 2 Aa : 1 aa</strong>。</p><p>只有再加上“一个位点决定该性状、完全显性、没有其他影响”等前提，才会得到常见的 3:1 表型比例。许多疾病和数量性状不满足这些条件。</p>`,['os12','nhAllele']],
    ['显性不是“常见”或“强”',`<p><strong>Dominant / 显性</strong>描述某个 allele 在杂合状态下的特定表型表现；它不表示该 allele 在人群里更常见、更健康或分子作用更大。一个基因的不同变异也可能有不同作用机制。</p><p>研究肿瘤时还要区别先天带有的胚系变异与生命中细胞后来获得的体细胞突变。后者通常不通过生殖细胞传给子女。</p>`,['os12','nciGenetics']],

    ['亲手填一次 Punnett 方格',`<p>令一方配子列为 A、a，另一方配子行为 A、a；交叉相乘得到 <code>AA</code>、<code>Aa</code>、<code>Aa</code>、<code>aa</code>。方格每格是一次<strong>可能组合</strong>，不是一个已经出生的孩子。若四格等概率，P(aa)=1/4，P(Aa)=1/2。<strong>每次妊娠是新的事件</strong>：先前已经有两个 Aa 子代，不会迫使下一个一定是 aa。</p><div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>配子</th><th>A</th><th>a</th></tr></thead><tbody><tr><td>A</td><td>AA</td><td>Aa</td></tr><tr><td>a</td><td>Aa</td><td>aa</td></tr></tbody></table></div><p>方格解决基因型组合问题。要转成疾病风险，还须知道显隐性关系、外显率、年龄与环境等条件。</p>`,['osMendel']],
    ['外显率让“有变异”与“有表型”分开',`<p><strong>Penetrance / 外显率</strong>问携带某种基因型的人中，有多少在规定的年龄、环境和观察条件下呈现对应表型。若某变异的外显率不是 100%，携带者仍可能没有表现；因此不能把“遗传到 allele 的概率”直接写成“患病概率”。<strong>Expressivity / 表现度</strong>则描述已经有表型的人表现到什么程度，两者问题不同。</p><p>家系图可能看起来“跳过一代”，原因不只一个：不完全外显、误诊、年龄尚未到发病期或其他遗传机制都可能影响观察。</p>`,['nhPenetrance','nhPhenotype']],
    ['常染色体模型之外：X 连锁与线粒体',`<p>前面的 Aa×Aa 假设<strong>常染色体、典型二倍体</strong>。对一些 X 染色体位点，携带一条 X 的个体只有一份该位点，遗传概率与常染色体方格不同；X 失活等因素还会影响表型。线粒体有自己的 DNA，通常沿母系传递，不能套用“每位亲本各给一份常染色体 allele”的模型。</p><p>因此遇到家系图，先问位点在常染色体、性染色体还是线粒体，再问变异的显性、外显率与观察年龄。</p>`,['nhXlinked','nhMtDNA','osMendel']],
    ["先区分 GT 与测序读段，再谈等位基因",`<p>假设一个典型二倍体正常样本的 VCF 记录写着 <code>REF=A, ALT=G, FORMAT=GT:AD:DP, sample=0/1:12,10:22</code>。<code>GT=0/1</code> 是未定相的基因型调用：0 指 REF，1 指第一个 ALT；<code>AD=12,10</code> 是本例中分别支持 A 与 G 的读段数；<code>DP=22</code> 是本例该样本在此位点的深度。12 与 10 是<strong>读段抽样</strong>，不是 12 条和 10 条染色体。</p><p>实际 VCF 的 FORMAT 字段由文件头定义；不同 caller 的过滤与计数规则可能让 AD 之和不等于 DP。尤其在肿瘤中，纯度和拷贝数改变会让简单二倍体 GT 解释失效。</p><details><summary>先猜再展开：0/1 是否要求 AD 恰好 11,11？</summary><p>不要求。0/1 是对 allele 组合的调用；有限读段会随机抽样，且覆盖和过滤可偏向某一 allele。读段比例与真实拷贝比例是两个层级。</p></details>`,['vcf', 'gdcVCF', 'nhGenotype']]
  ],worked:['计算 Aa × Aa 生出 aa 的概率',['一个亲本传 a 的概率是 1/2；另一个独立传 a 的概率也是 1/2。','在这个简化模型下，两者同时发生的概率为 <code>1/2 × 1/2 = 1/4</code>。','这个 1/4 是子代基因型概率；不能跳过表型机制，把它直接称作患病概率。']],terms:[['Diploid / 二倍体','具有两套染色体的细胞状态。','os11'],['Genotype / 基因型','个体在某位点或多个位点的遗传版本组合。','nhGenotype'],['Phenotype / 表型','可观察的特征或状态。','nhPhenotype']],check:['Aa × Aa 得到 1:2:1 后，能对任何疾病宣布 3:1 的患病比例吗？','不能。3:1 表型比例需要额外的单基因完全显性等假设，很多疾病由多因素决定。']},
  {id:'g04',title:'减数分裂、重组与连锁',subtitle:'为什么子代不是父母染色体的逐字复制？',intro:'配子形成时，同源染色体的分离与片段交换使遗传信息重新组合。这解释了亲缘关系、连锁，以及为什么某些遗传关联结果不能只看最近的基因。',goals:['认识有丝与减数分裂的区别','理解 crossing over','区分 haplotype 与 phasing','手算简化重组概率'],prereq:['g03'],flow:[['同源染色体','父母来源的两条'],['交换','部分片段重新组合'],['分离','形成单倍体配子'],['受精','重新获得两套']],sections:[
    ['两种分裂解决不同问题',`<p><strong>Mitosis / 有丝分裂</strong>通常把已复制染色体分给两个子细胞，用于生长与修复。<strong>Meiosis / 减数分裂</strong>产生配子，经过两轮分裂使染色体套数减半。两者都与 DNA 复制有关，但产物的染色体组合不同。</p><p>肿瘤细胞不断分裂时，研究者主要关注其体细胞有丝分裂和演化；家族遗传与连锁则需要理解减数分裂。</p>`,['os10','os11']],
    ['交换使同一染色体内部也会重排',`<p>减数分裂时，同源染色体之间可以发生<strong>crossing over / 交换</strong>，于是一个配子里的染色体可能混合了祖父母来源的片段。两个相邻位点未必永远同时传递，但距离较近时通常较少被交换分开，这就是连锁的直观来源。</p><p>因此一个显著遗传标记可能只是与真正起作用的变异共同遗传；“最接近的基因”也未必是被影响的基因。</p>`,['os11','os13']],
    ['连锁不等于功能联系',`<p><strong>GWAS / genome-wide association study / 全基因组关联研究</strong>比较许多人的遗传标记与性状或疾病，寻找统计关联；关联本身不证明因果。连锁是遗传共传递的统计现象；功能联系是分子机制问题。两个变异高度相关可能源于它们在染色体上接近，不表示一个调控另一个。分析 GWAS 时，需要群体结构、重组模式与功能实验等多种证据来定位候选因果变异。</p><p>把“相关的变异集合”先看成一个待拆解的候选区域，比把每个显著点单独当作因果结果更稳妥。</p>`,['osLinkage','nhGWAS']],

    ['Haplotype 与 phasing：同一条染色体上是谁和谁',`<p><strong>Haplotype / 单倍型</strong>是一条染色体上可共同遗传的一组变异。教学例子用大写 A、B 表示两个位点各自的 ALT 版本，小写 a、b 表示各自的另一版本。若某人在两个位点都杂合，分别记作 A/a 与 B/b，仅凭每个位点的基因型，仍不知道排列是 <code>AB | ab</code> 还是 <code>Ab | aB</code>。竖线分开两条同源染色体；确定这种排列叫 <strong>phasing / 定相</strong>。</p><p>在 <code>AB | ab</code> 情况，两个 ALT 位于同一条（<em>cis</em>）；在 <code>Ab | aB</code> 情况，两个 ALT 位于不同条（<em>trans</em>）。对部分隐性疾病或肿瘤中两次打击的解释，这个区别很关键。短 reads 若没有跨越两个位点，就可能无法直接定相。</p>`,['nhHaplotype','osLinkage','hts']],
    ['重组率 20% 代表什么',`<p>假设一个教学用双位点杂合个体的两条染色体是 <code>AB | ab</code>，两个位点间重组率为 20%，且配子类型对称。非重组配子 AB 与 ab 合计 80%，各约 40%；重组配子 Ab 与 aB 合计 20%，各约 10%。这不是每个子代的染色体有 20% 被剪掉，而是<strong>大量配子中两位点组合变化的比例</strong>。</p><p>遗传距离常以 cM 表示，但物理距离和重组概率不是处处固定比例；解释真实人类数据还要考虑性别、区域与群体差异。</p>`,['osLinkage']],
    ["两个 0/1 仍不知道两个变异是否在同一条染色体",`<figure class="concept-figure"><div class="book-image-scroll"><img src="assets/haplotype-phase.svg" alt="两个位点均为杂合时，AB 与 ab 在同一对同源染色体，或 Ab 与 aB 在另一种定相；单独的两条 0/1 记录无法区分" loading="lazy"></div><figcaption>原创教学示意 · 两种定相产生相同的逐位点杂合调用；依据本节来源。</figcaption></figure><p>一个人位点 1 的 <code>GT=0/1</code>、位点 2 的 <code>GT=0/1</code>，只说明每个位置各有两个 allele。它并未告诉软件“两个 ALT 在同一条染色体”。若读取跨过两个位置的长分子或读段，才可能直接观察到同一分子上的组合；家系信息和统计方法也可能帮助定相。</p><details><summary>先猜再展开：只拿到两个独立的 0/1，能断言两处变异是 cis 吗？</summary><p>不能。<code>AB | ab</code> 与 <code>Ab | aB</code> 都产生逐位点 0/1，但前者的 A、B 同在一条，后者分处两条。需要 phasing 信息。</p></details>`,['nhHaplotype', 'osLinkage', 'vcf']]
  ],worked:['解释两个相邻变异为什么常一起出现',['位点 A 与 B 位于同一条染色体的近邻。','在多代遗传中，二者之间发生交换的机会相对较低。','观察到 A 时常也观察到 B；但谁影响表型需另行验证。']],terms:[['Meiosis / 减数分裂','形成单倍体配子的细胞分裂过程。','os11'],['Recombination / 重组','遗传片段重新组合。','os11'],['Linkage / 连锁','位点在遗传中非独立共同传递的现象。','os13']],check:['GWAS 中两个位点同时显著，可以说它们都直接造成疾病吗？','不能。它们可能因连锁而共同出现；因果定位需更多统计和功能证据。']},
  {id:'g05',title:'变异、拷贝数与突变来源',subtitle:'把“基因变了”拆成不同的 DNA 事件。',intro:'同一句“发生突变”可能指一个碱基替换、一段 DNA 缺失、拷贝数增多或染色体重排。不同事件需要不同检测与解释。',goals:['区分 SNV、indel、CNV','区分 germline 与 somatic','手算 VAF 与肿瘤纯度','知道 variant 不等于 pathogenic'],prereq:['g02'],flow:[['SNV','单个碱基替换'],['indel','插入或删除'],['CNV','一段 DNA 的份数变动'],['结构变异','较大范围重排']],sections:[
    ['按尺度描述 DNA 差异',`<p><strong>SNV</strong>是单碱基差异；<strong>indel</strong>是插入或缺失；<strong>CNV</strong>描述一段 DNA 的拷贝数改变；更大的结构变异包括倒位、易位等。一个坐标和一个 ALT 字母不足以表示所有类型。测序技术、覆盖范围与算法决定哪些事件有机会被发现。</p><p>“Variant / 变异”常强调与参考序列不同，未预设好坏。多数序列差异不能直接解释为致病。</p>`,['nhMutation','nhCNV','gdc']],
    ['胚系还是体细胞',`<p>胚系变异来自生殖细胞谱系，可能在个体多数细胞中存在并传给下一代；体细胞变异在生命过程中某些细胞及其后代中出现。肿瘤分析常比较同一患者的 tumor 与 normal 材料，帮助区分两者，但正常样本的选择、肿瘤纯度和测序误差都会影响判断。</p><p>单个肿瘤切片还可能含多个亚克隆，所以同一突变的等位基因频率不一定是 0、1/2 或 1。</p>`,['nciGenetics','gdcDoc']],
    ['从位置到功能需要证据阶梯',`<p>变异落在蛋白编码区，可预测同义、错义、无义或移码等后果；落在剪接位点或调控区也可能有影响。预测标签通常只描述序列或转录本层后果，不能单独证明细胞功能改变，更不能单独证明一个人会患病。</p><p>在癌症中还需区分“driver / 驱动”与伴随扩增的 passenger / 乘客变化，并考虑癌种、治疗与其他改变。</p>`,['os14','os15','nciCancer']],

    ['VAF 是 reads 的比例，先不要把它叫细胞比例',`<p><strong>VAF / variant allele fraction</strong>通常按某位点 ALT reads / 覆盖该位点的有效 reads 计算。教学例子：40 条有效 reads 中 10 条支持 ALT，观测 VAF=0.25。这个数不直接等于“25% 的细胞有变异”：每个细胞有几份该区域、样本里多少正常细胞、多少肿瘤细胞携带变异，以及读段抽样与测序偏差都会改变它。</p><p>对典型二倍体、无局部 CNV、纯肿瘤且所有细胞都只有一份突变拷贝的极简情况，期望 VAF 约 0.5；观察值还会有深度带来的随机波动。</p>`,['gdcVCF','vafPurityPaper']],
    ['肿瘤纯度 50% 时，为何克隆性变异也可能是 0.25',`<p>假设 100 个细胞里 50 个肿瘤细胞、50 个正常细胞；该位点都恰好二倍体。变异存在于所有肿瘤细胞且每个肿瘤细胞只有 1 份 ALT，正常细胞没有。ALT 拷贝共 50 份，总拷贝共 200 份，故理想 VAF=<code>50/200=0.25</code>。这个 0.25 与“只有四分之一的肿瘤细胞有变异”完全不同。</p><p>若有 CNV、亚克隆、参考比对偏差或正常细胞也携带该变异，计算要换模型。没有纯度与局部拷贝数信息，就不能从一个 VAF 唯一解出 cancer cell fraction。</p>`,['vafPurityPaper','nhCNV']],
    ["同一个 0.25 VAF 可以对应两种不同肿瘤",`<p>VCF 中若本例 <code>AD=30,10</code>，支持 ALT 的 10 条除以 40 条有效读段得到<strong>观测 VAF=0.25</strong>。但即使忽略测序偏差，至少有两种简化生物情境会产生相同期望值：</p><div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>情境</th><th>肿瘤纯度</th><th>有 ALT 的肿瘤细胞比例</th><th>理想 ALT / 总拷贝</th></tr></thead><tbody><tr><td>正常细胞混入</td><td>50%</td><td>100%</td><td>50 / 200 = 0.25</td></tr><tr><td>纯肿瘤但有亚克隆</td><td>100%</td><td>50%</td><td>50 / 200 = 0.25</td></tr></tbody></table></div><p>两行均假设该位点每个细胞有两份 DNA，携带者只有一份 ALT。真实 VAF 还会受局部 CNV、测序深度和比对偏差影响。<strong>一个观测比例通常无法唯一反推其生物成因。</strong></p><details><summary>先猜再展开：观察到 VAF 0.25 就能说“25% 肿瘤细胞携带突变”吗？</summary><p>不能。上面两种情境一个是 100% 的肿瘤细胞携带，另一个是 50%；观测 VAF 相同。必须加入纯度、拷贝数和其他证据。</p></details>`,['vafPurityPaper', 'vcf', 'nhCNV']]
  ],worked:['看到“TP53 mutated”，先问哪些问题',['是什么事件：SNV、indel、CNV 还是其他结构改变？','是胚系还是体细胞？用什么正常材料和过滤流程判断？','发生在哪个转录本位置？是否有功能或临床证据？','该队列怎样取样，是否存在多个肿瘤亚克隆？']],terms:[['SNV / 单核苷酸变异','单个碱基与参考序列的差异。','nhMutation'],['CNV / 拷贝数变异','一段 DNA 份数的增加或减少。','nhCNV'],['Somatic mutation / 体细胞突变','生命过程中在某些体细胞谱系获得的改变。','nciGenetics']],check:['为什么不能把检测到的每个肿瘤变异都叫 driver？','许多变异可能是伴随变化或技术误差；需要功能、重复出现、选择优势等证据支持驱动作用。']},
  {id:'g06',title:'群体遗传、进化与风险',subtitle:'从一个人的基因型，走向人群中的频率与关联。',intro:'遗传风险不是命运预测。群体遗传学研究 allele 频率怎样在群体中变化；它也帮助理解为什么一个统计关联可能与因果不同。',goals:['计算 allele frequency','手算 Hardy–Weinberg 基线','区分人群频率与肿瘤 VAF','认识风险与群体结构'],prereq:['g04','g05'],flow:[['群体','定义采样人群'],['allele 频率','统计不同版本比例'],['演化力量','选择、漂变、迁移'],['表型关联','考虑环境和结构']],sections:[
    ['频率是群体层数字',`<p>假设 100 位典型二倍体个体在某常染色体位点共有 200 份 allele，其中 30 份为 A，那么 A 的 allele frequency 是 <code>30/200 = 0.15</code>。它不表示“一个人 15% 的细胞携带 A”，也不等于患病概率。</p><p>频率要注明人群、样本定义与测量质量。不同祖源群体中的频率可以不同，比较病例和对照时尤其要注意群体结构。</p>`,['osHardy','nhAllele']],
    ['频率为什么变化',`<p>突变可产生新的 allele；自然选择、随机遗传漂变与迁移可改变<strong>单个位点</strong>的 allele 频率。重组则把不同位点的 allele 重新搭配：它能改变 <code>AB</code> 与 <code>Ab</code> 这类组合的频率，但仅凭重组本身不会改变 A 这个单个位点的总体比例。选择不是个体“需要某个变异就会长出它”；它描述不同遗传版本在特定环境与时间下的相对传递。</p><p>肿瘤内部也有克隆演化：携带不同改变的细胞群体在组织环境与治疗压力下可出现不同扩张，但这不是人群遗传的同一个采样层。</p>`,['osHardy','osLinkage','nciCancer']],
    ['统计风险与因果边界',`<p>GWAS 报告的是遗传标记与表型在研究人群中的统计关联。一个位点可能通过连锁指向其他变异，也可能受群体结构、测量误差或选择偏差影响。即使关联可靠，个人风险也取决于其他遗传、环境和临床因素。</p><p>计算研究必须写清效应量、置信区间、适用人群和验证方式，而不是把 p 值翻译成“这个基因决定疾病”。</p>`,['nhGWAS','osHardy','nhPhenotype']],

    ['Hardy–Weinberg 是一个零假设模型',`<p>若一个二等位常染色体位点的 A 频率为 <code>p</code>、a 频率为 <code>q</code>，且 <code>p+q=1</code>，在 Hardy–Weinberg 的理想条件下，预期基因型频率为 <code>AA=p²</code>、<code>Aa=2pq</code>、<code>aa=q²</code>。例如 p=0.8、q=0.2，则三者分别为 0.64、0.32、0.04；总和为 1。</p><p>这些不是无需检查的真实频率，而是随机交配、足够大群体以及忽略选择、迁移和新突变等条件下的<strong>基线预测</strong>。实际样本偏离时，要先考虑取样、基因型调用、群体结构和生物过程，不能直接断定某一种机制。</p>`,['osHardy']],
    ['别把人群 allele frequency 与肿瘤 VAF 混为一列',`<div class="lesson-table-wrap"><table class="lesson-table"><thead><tr><th>量</th><th>分子与分母</th><th>单位层级</th></tr></thead><tbody><tr><td>人群 allele frequency</td><td>人群里某 allele 拷贝 / 该位点总拷贝</td><td>不同个体的基因组</td></tr><tr><td>肿瘤样本 VAF</td><td>一个样本某位点 ALT reads / 有效覆盖 reads</td><td>一个混合组织的测序读段</td></tr></tbody></table></div><p>两者都可能写成 0.25，但问题完全不同。前者帮助理解群体多样性、遗传关联与参考数据库；后者帮助分析样本内的体细胞变异，且受纯度、拷贝数与技术误差影响。<a href="#g05">回看 G05 的 50% 肿瘤纯度例题</a>。</p>`,['osHardy','vafPurityPaper']],
    ["allele frequency 与携带者比例不是同一个分母",`<p>在一个教学人群中，100 位典型二倍体个体的基因型为 10 位 AA、20 位 Aa、70 位 aa。A 的拷贝数是 <code>2×10 + 20 = 40</code>，总 allele 拷贝数是 200，所以 <strong>A allele frequency = 40/200 = 0.20</strong>。但至少携带一个 A 的人有 10+20=30 位，<strong>carrier proportion = 30/100 = 0.30</strong>。</p><p>两列都可能写成“频率”，却有不同分母；它们都不是肿瘤样本的 VAF。读数据库的 <code>AF</code> 列，要检查它来自何种样本集合、位点和计算规则。</p><details><summary>先算再展开：若只知道 30% 的人携带 A，可直接确定 A allele frequency 吗？</summary><p>不能。携带者中 AA 和 Aa 的人数不同，A 拷贝总数就不同。要有基因型计数或相应模型。</p></details>`,['osHardy', 'nhAllele', 'vcf']]
  ],worked:['计算 allele frequency',['100 位典型二倍体个体提供 200 份常染色体 allele。','观察到 A 共 30 份，频率 <code>30/200 = 0.15</code>。','这只是所取样人群中的估计；是否代表其他人群需检查抽样与祖源。']],terms:[['Allele frequency / 等位基因频率','指定群体中某版本占所有相应 allele 的比例。','osHardy'],['Genetic drift / 遗传漂变','由于随机抽样造成的频率变化。','osHardy'],['Population structure / 群体结构','不同子群体遗传频率并不相同的格局。','os19']],check:['某 allele 在病例里更常见，能直接证明它本身导致疾病吗？','不能。需排查连锁、群体结构、测量和选择偏差，并寻找功能或其他因果证据。']}
]});
