// Original Chinese teaching text lives in textbook-part-*.js. Sources are linked, not copied.
window.BIOCS_BOOK = [];
window.BIOCS_SOURCES = {
  osTransportPassive:['OpenStax Biology 2e · Passive Transport','https://openstax.org/books/biology-2e/pages/5-2-passive-transport'],
  osTransportActive:['OpenStax Biology 2e · Active Transport','https://openstax.org/books/biology-2e/pages/5-3-active-transport'],
  osEndomembrane:['OpenStax Biology 2e · Endomembrane System and Proteins','https://openstax.org/books/biology-2e/pages/4-4-the-endomembrane-system-and-proteins'],
  osSignalPropagation:['OpenStax Biology 2e · Propagation of the Signal','https://openstax.org/books/biology-2e/pages/9-2-propagation-of-the-signal'],
  osAdaptiveImmune:['OpenStax Biology 2e · Adaptive Immune Response','https://openstax.org/books/biology-2e/pages/42-2-adaptive-immune-response'],
  nhGWAS:['NHGRI · Genome-Wide Association Studies','https://www.genome.gov/genetics-glossary/Genome-Wide-Association-Studies-GWAS'],
  os1:['OpenStax Biology 2e · Science of Biology','https://openstax.org/books/biology-2e/pages/1-1-the-science-of-biology'],
  os2:['OpenStax Biology 2e · Chemistry of Life','https://openstax.org/books/biology-2e/pages/2-introduction'],
  os3:['OpenStax Biology 2e · Biological Macromolecules','https://openstax.org/books/biology-2e/pages/3-introduction'],
  osNucleic:['OpenStax Biology 2e · Nucleic Acids','https://openstax.org/books/biology-2e/pages/3-5-nucleic-acids'],
  osProtein:['OpenStax Biology 2e · Proteins','https://openstax.org/books/biology-2e/pages/3-4-proteins'],
  osEnzyme:['OpenStax Biology 2e · Enzymes','https://openstax.org/books/biology-2e/pages/6-5-enzymes'],
  os4:['OpenStax Biology 2e · Cell Structure','https://openstax.org/books/biology-2e/pages/4-introduction'],
  osCellScale:['OpenStax Biology 2e · Studying Cells','https://openstax.org/books/biology-2e/pages/4-1-studying-cells'],
  os5:['OpenStax Biology 2e · Plasma Membranes','https://openstax.org/books/biology-2e/pages/5-introduction'],
  os6:['OpenStax Biology 2e · Metabolism','https://openstax.org/books/biology-2e/pages/6-introduction'],
  os9:['OpenStax Biology 2e · Cell Communication','https://openstax.org/books/biology-2e/pages/9-introduction'],
  os10:['OpenStax Biology 2e · Cell Reproduction','https://openstax.org/books/biology-2e/pages/10-introduction'],
  osCycle:['OpenStax Biology 2e · The Cell Cycle','https://openstax.org/books/biology-2e/pages/10-2-the-cell-cycle'],
  osCheckpoint:['OpenStax Biology 2e · Cell Cycle Control','https://openstax.org/books/biology-2e/pages/10-3-control-of-the-cell-cycle'],
  os11:['OpenStax Biology 2e · Meiosis','https://openstax.org/books/biology-2e/pages/11-introduction'],
  os12:['OpenStax Biology 2e · Mendel','https://openstax.org/books/biology-2e/pages/12-introduction'],
  osMendel:['OpenStax Biology 2e · Characteristics and Traits','https://openstax.org/books/biology-2e/pages/12-2-characteristics-and-traits'],
  os13:['OpenStax Biology 2e · Modern Inheritance','https://openstax.org/books/biology-2e/pages/13-introduction'],
  osLinkage:['OpenStax Biology 2e · Genetic Linkage','https://openstax.org/books/biology-2e/pages/13-1-chromosomal-theory-and-genetic-linkage'],
  os14:['OpenStax Biology 2e · DNA Structure and Function','https://openstax.org/books/biology-2e/pages/14-introduction'],
  osReplication:['OpenStax Biology 2e · DNA Replication','https://openstax.org/books/biology-2e/pages/14-5-dna-replication-in-eukaryotes'],
  osFork:['OpenStax Biology 2e · Replication Fork','https://openstax.org/books/biology-2e/pages/14-4-dna-replication-in-prokaryotes'],
  os15:['OpenStax Biology 2e · Genes and Proteins','https://openstax.org/books/biology-2e/pages/15-introduction'],
  os16:['OpenStax Biology 2e · Gene Expression','https://openstax.org/books/biology-2e/pages/16-introduction'],
  os17:['OpenStax Biology 2e · Biotechnology','https://openstax.org/books/biology-2e/pages/17-introduction'],
  osPCR:['OpenStax Biology 2e · PCR','https://openstax.org/books/biology-2e/pages/17-1-biotechnology'],
  miqe2:['MIQE 2.0 · qPCR Reporting Guidelines','https://academic.oup.com/clinchem/article/71/6/634/8119148'],
  assayEnzyme:['NCBI Assay Guidance Manual · Basics of Enzymatic Assays','https://www.ncbi.nlm.nih.gov/books/NBK92007/'],
  enzymeKmPaper:['New Standards for Fitting Steady State Kinetics','https://pmc.ncbi.nlm.nih.gov/articles/PMC6334795/'],
  os19:['OpenStax Biology 2e · Evolution of Populations','https://openstax.org/books/biology-2e/pages/19-introduction'],
  osHardy:['OpenStax Biology 2e · Population Evolution','https://openstax.org/books/biology-2e/pages/19-1-population-evolution'],
  osVirus:['OpenStax Biology 2e · Virus Replication','https://openstax.org/books/biology-2e/pages/21-2-virus-infections-and-hosts'],
  os42:['OpenStax Biology 2e · Immune System','https://openstax.org/books/biology-2e/pages/42-introduction'],
  nhDNA:['NHGRI · DNA','https://www.genome.gov/genetics-glossary/Deoxyribonucleic-Acid-DNA'],
  nhGene:['NHGRI · Gene','https://www.genome.gov/genetics-glossary/Gene'],
  nhChrom:['NHGRI · Chromosome','https://www.genome.gov/genetics-glossary/Chromosome'],
  nhAllele:['NHGRI · Allele','https://www.genome.gov/genetics-glossary/Allele'],
  nhHaplotype:['NHGRI · Haplotype','https://www.genome.gov/genetics-glossary/haplotype'],
  nhXlinked:['NHGRI · X-Linked','https://www.genome.gov/genetics-glossary/X-Linked'],
  nhMtDNA:['NHGRI · Mitochondrial DNA','https://www.genome.gov/genetics-glossary/Mitochondrial-DNA'],
  nhPenetrance:['NHGRI · Genetic Testing Glossary (Penetrance)','https://www.genome.gov/10002399/genetic-testing-reportglossary'],
  nhGenetics:['NHGRI · Genetics','https://www.genome.gov/genetics-glossary/Genetics'],
  nhGenotype:['NHGRI · Genotype','https://www.genome.gov/genetics-glossary/genotype'],
  nhPhenotype:['NHGRI · Phenotype','https://www.genome.gov/genetics-glossary/Phenotype'],
  nhMutation:['NHGRI · Mutation','https://www.genome.gov/genetics-glossary/Mutation'],
  nhDogma:['NHGRI · Central Dogma','https://www.genome.gov/genetics-glossary/Central-Dogma'],
  nhRNA:['NHGRI · RNA Fact Sheet','https://www.genome.gov/about-genomics/educational-resources/fact-sheets/ribonucleic-acid-fact-sheet'],
  nhTrans:['NHGRI · Transcription','https://www.genome.gov/genetics-glossary/Transcription'],
  nhTranslation:['NHGRI · Translation','https://www.genome.gov/genetics-glossary/Translation'],
  nhSplice:['NHGRI · Alternative Splicing','https://www.genome.gov/genetics-glossary/Alternative-Splicing'],
  nhCode:['NHGRI · Codon','https://www.genome.gov/genetics-glossary/Codon'],
  nhCell:['NHGRI · Cell','https://www.genome.gov/genetics-glossary/Cell'],
  nhCycle:['NHGRI · Cell Cycle','https://www.genome.gov/genetics-glossary/Cell-Cycle'],
  nhPath:['NHGRI · Biological Pathways','https://www.genome.gov/about-genomics/fact-sheets/Biological-Pathways-Fact-Sheet'],
  nhEpigen:['NHGRI · Epigenetics','https://www.genome.gov/genetics-glossary/Epigenetics'],
  nhCNV:['NHGRI · Copy Number Variation','https://www.genome.gov/genetics-glossary/Copy-Number-Variation-CNV'],
  nhPCR:['NHGRI · PCR','https://www.genome.gov/genetics-glossary/Polymerase-Chain-Reaction'],
  nhSeq:['NHGRI · DNA Sequencing','https://www.genome.gov/genetics-glossary/DNA-Sequencing'],
  nhSanger:['NHGRI · Chain-Termination Sequencing','https://www.genome.gov/nov-7-2017-40th-anniversary-of-landmark-dna-sequencing-methods'],
  nhMicro:['NHGRI · Microbiome','https://www.genome.gov/genetics-glossary/Microbiome'],
  nciCancer:['NCI · What Is Cancer?','https://www.cancer.gov/about-cancer/understanding/what-is-cancer'],
  nciGenetics:['NCI · Genetics of Cancer','https://www.cancer.gov/about-cancer/causes-prevention/genetics'],
  vafPurityPaper:['Tumor Purity, Copy Number and Expected VAF · Primary Study','https://pmc.ncbi.nlm.nih.gov/articles/PMC9373375/'],
  nciSignal:['NCI · Signal Transduction','https://www.cancer.gov/publications/dictionaries/cancer-terms/def/signal-transduction'],
  nciTME:['NCI · Tumor Microenvironment','https://www.cancer.gov/publications/dictionaries/cancer-terms/def/tumor-microenvironment'],
  nciImmune:['NCI · Immune System and Cancer','https://www.cancer.gov/about-cancer/understanding/what-is-cancer'],
  nciCheckpoint:['NCI · Immune Checkpoint Inhibitors','https://www.cancer.gov/about-cancer/treatment/types/immunotherapy/checkpoint-inhibitors'],
  nciDiagnosis:['NCI · Cancer Diagnosis and Staging','https://www.cancer.gov/about-cancer/diagnosis-staging'],
  gdc:['NCI GDC · About Data','https://gdc.cancer.gov/about-data'],
  gdcDoc:['NCI GDC · Data Documentation','https://docs.gdc.cancer.gov/Data/Introduction/'],
  gdcRNA:['NCI GDC · mRNA Pipeline','https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/Expression_mRNA_Pipeline/'],
  gdcDNA:['NCI GDC · DNA Variant Calling Pipeline','https://docs.gdc.cancer.gov/Data/Bioinformatics_Pipelines/DNA_Seq_Variant_Calling_Pipeline/'],
  gdcBarcode:['NCI GDC · TCGA Barcode','https://docs.gdc.cancer.gov/Encyclopedia/pages/TCGA_Barcode/'],
  gdcDictionary:['NCI GDC · Data Dictionary','https://docs.gdc.cancer.gov/Data_Dictionary/'],
  gdcCase:['NCI GDC · Case Definition','https://docs.gdc.cancer.gov/Encyclopedia/pages/Case/'],
  gdcSample:['NCI GDC · Biospecimen Model','https://docs.gdc.cancer.gov/Data_Submission_Portal/Users_Guide/Data_Submission_Walkthrough/'],
  gdcVCF:['NCI GDC · VCF Format','https://docs.gdc.cancer.gov/Data/File_Formats/VCF_Format/'],
  gdcMAF:['NCI GDC · MAF Format','https://docs.gdc.cancer.gov/Data/File_Formats/MAF_Format/'],
  gdcRepo:['NCI GDC · Repository Metadata','https://docs.gdc.cancer.gov/Data_Portal/Users_Guide/Repository/'],
  tcga:['NCI · The Cancer Genome Atlas','https://www.cancer.gov/ccg/research/genome-sequencing/tcga'],
  geo:['NCBI · GEO Overview','https://www.ncbi.nlm.nih.gov/geo/info/overview.html'],
  sra:['NCBI · SRA Documentation','https://www.ncbi.nlm.nih.gov/sra/docs/'],
  gtex:['GTEx Portal · Documentation','https://gtexportal.org/home/documentationPage'],
  encode:['ENCODE Project','https://www.encodeproject.org/pages/homepage/'],
  encodeATAC:['ENCODE · ATAC-seq','https://www.encodeproject.org/atac-seq/'],
  encodeGlossary:['ENCODE · cCRE Glossary','https://www.encodeproject.org/glossary/'],
  encodeScreen:['ENCODE · SCREEN cCRE Registry','https://screen.encodeproject.org/'],
  nhPromoter:['NHGRI · Promoter','https://www.genome.gov/genetics-glossary/Promoter'],
  gencode:['GENCODE · Gene and Transcript Annotation','https://www.gencodegenes.org/'],
  gencodeFormat:['GENCODE · GTF Feature Types','https://www.gencodegenes.org/pages/data_format.html'],
  osTranscription:['OpenStax Biology 2e · Eukaryotic Transcription','https://openstax.org/books/biology-2e/pages/15-3-eukaryotic-transcription'],
  rmats:['rMATS · Differential Alternative Splicing','https://pmc.ncbi.nlm.nih.gov/articles/PMC4280593/'],
  visium:['10x Genomics · Visium Glossary','https://www.10xgenomics.com/support/software/space-ranger/latest/getting-started/space-ranger-glossary'],
  visiumHD:['10x Genomics · Visium HD Technical Note','https://cdn.10xgenomics.com/image/upload/v1722285090/support/documents/CG000686_VisiumHDSpatialGeneExpressionPerformance_TechnicalNote_RevA.pdf'],
  visiumMatrix:['10x Genomics · Space Ranger Matrices','https://www.10xgenomics.com/support/software/space-ranger/latest/tutorials/outputs/space-ranger-feature-barcode-matrices'],
  visiumSpatial:['10x Genomics · Space Ranger Spatial Outputs','https://www.10xgenomics.com/support/software/space-ranger/latest/analysis/spatial-outputs'],
  xenium:['10x Genomics · Xenium Technology','https://www.10xgenomics.com/in-situ-technology'],
  xeniumPanel:['10x Genomics · Xenium Gene Panels','https://www.10xgenomics.com/support/software/xenium-panel-designer/latest/tutorials/pre-designed-xenium-v1'],
  xeniumOutput:['10x Genomics · Xenium Outputs','https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/analysis/outputs/xoa-output-at-a-glance'],
  xeniumSeg:['10x Genomics · Xenium Segmentation','https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/algorithms-overview/segmentation'],
  codexPaper:['CODEX · DNA-barcoded Antibody Protocol','https://pmc.ncbi.nlm.nih.gov/articles/PMC8647621/'],
  codexBrand:['Akoya · CODEX / PhenoCycler Naming','https://www.akoyabio.com/wp-content/uploads/2022/01/PhenoCycler_App-Note_Single-Cell-Spatial-Biology-in-FFPE-Tissues_DN00139.pdf'],
  merfish:['MERFISH · Method Protocol','https://pmc.ncbi.nlm.nih.gov/articles/PMC5023431/'],
  cosmx:['Bruker Spatial Biology · CosMx','https://brukerspatialbiology.com/products/cosmx-spatial-molecular-imager/'],
  imc:['Standard BioTools · Imaging Mass Cytometry','https://standardbio.com/our-technology/spatial-proteomics/'],
  cellxgene:['CELLxGENE Discover · Documentation','https://cellxgene.cziscience.com/docs/02__Find%20Published%20Data'],
  pride:['EMBL-EBI · PRIDE','https://www.ebi.ac.uk/training/online/courses/pride-quick-tour/what-is-pride/'],
  tcia:['TCIA · About','https://www.cancerimagingarchive.net/about-the-cancer-imaging-archive-tcia/'],
  idr:['Image Data Resource · About','https://idr.openmicroscopy.org/about/'],
  reactome:['Reactome · Pathway Database','https://reactome.org/'],
  vcf:['GA4GH · VCF Specification','https://samtools.github.io/hts-specs/VCFv4.3.pdf'],
  hts:['GA4GH · HTS Specifications','https://samtools.github.io/hts-specs/'],
  ensemblIDs:['Ensembl · Stable IDs','https://www.ensembl.org/info/genome/stable_ids/index.html'],
  ensemblMap:['Ensembl REST · Assembly Map','https://rest.ensembl.org/documentation/info/assembly_map'],
  ucscCoord:['UCSC Genome Browser · Coordinate FAQ','https://www.genome.ucsc.edu/FAQ/FAQtracks'],
  anndata:['AnnData · On-disk Format','https://anndata.readthedocs.io/en/stable/fileformat-prose.html'],
  scanpyQC:['Scanpy · QC Metrics','https://scanpy.readthedocs.io/en/latest/generated/scanpy.pp.calculate_qc_metrics.html'],
  omeTiff:['OME · OME-TIFF Format','https://ome-model.readthedocs.io/en/stable/ome-tiff/specification.html'],
  sklearnGroup:['scikit-learn · GroupKFold','https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GroupKFold.html'],
  sklearnLeak:['scikit-learn · Common Pitfalls','https://scikit-learn.org/stable/common_pitfalls.html'],
  deseq2:['DESeq2 · Original Method Paper','https://pmc.ncbi.nlm.nih.gov/articles/PMC4302049/'],
  deseq2Guide:['Bioconductor · DESeq2 Vignette','https://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html'],
  illuminaWorkflow:['Illumina · NGS Workflow','https://www.illumina.com/science/technology/next-generation-sequencing/beginners/ngs-workflow.html'],
  illuminaSBS:['Illumina · Sequencing by Synthesis','https://www.illumina.com/science/technology/next-generation-sequencing/sequencing-technology.html'],
  illuminaGlossary:['Illumina · NGS Glossary','https://www.illumina.com/science/technology/next-generation-sequencing/beginners/tutorials/glossary.html'],
  illuminaRNAprep:['Illumina · RNA Library Preparation','https://www.illumina.com/techniques/sequencing/ngs-library-prep/rna.html'],
  illuminaRRNA:['Illumina · rRNA Depletion Guide','https://www.illumina.com/products/selection-tools/rrna-depletion-selection-guide.html'],
  illuminaUMI:['Illumina · Unique Molecular Identifiers','https://www.illumina.com/techniques/sequencing/ngs-library-prep/multiplexing/unique-molecular-identifiers.html'],
  illuminaQ:['Illumina · Sequencing Quality Scores','https://www.illumina.com/science/technology/next-generation-sequencing/plan-experiments/quality-scores.html'],
  samSpec:['GA4GH · SAM/BAM Specification','https://samtools.github.io/hts-specs/SAMv1.pdf'],
  tpmPaper:['Wagner et al. · TPM and RPKM','https://pubmed.ncbi.nlm.nih.gov/22872506/'],
  tmmPaper:['Robinson & Oshlack · TMM Normalization','https://pmc.ncbi.nlm.nih.gov/articles/PMC2864565/'],
  tximportGuide:['Bioconductor · tximport Vignette','https://bioconductor.org/packages/release/bioc/vignettes/tximport/inst/doc/tximport.html'],
  nanoporeTech:['Oxford Nanopore · Sequencing Principle','https://nanoporetech.com/platform/technology'],
  pacbioHiFi:['PacBio · How HiFi Sequencing Works','https://www.pacb.com/technology/hifi-sequencing/how-it-works/'],
  ncbiRNA:['NCBI Bookshelf · RNA Processing','https://www.ncbi.nlm.nih.gov/books/NBK9864/'],
  ncbiCode:['NCBI · Standard Genetic Code','https://www.ncbi.nlm.nih.gov/books/NBK2327/bin/stdcode.pdf']
};
