/* Authored semantics after inspecting all 171 visible chapter flow arrays. */
(function () {
  'use strict';
  const groups={
  "sequence": [
    "b04",
    "g03",
    "g04",
    "x02",
    "x05",
    "x08",
    "x09",
    "x13",
    "x15",
    "x16",
    "x18",
    "x21",
    "m01",
    "m05",
    "c04",
    "c05",
    "t01",
    "t02",
    "t04",
    "d02",
    "d03",
    "d04",
    "d06",
    "r03",
    "r05",
    "r06",
    "s02",
    "s03",
    "s04",
    "s07",
    "k04",
    "k05",
    "k06",
    "k10",
    "q02",
    "q04",
    "q05",
    "q07",
    "q09",
    "u02",
    "u05",
    "h03",
    "h06",
    "h07",
    "l02",
    "l03",
    "l05",
    "v02",
    "i03",
    "i04",
    "i06",
    "i07",
    "n01",
    "n02",
    "n03",
    "n04",
    "n05",
    "o04",
    "a02",
    "a03",
    "a05",
    "a10",
    "w01",
    "w02",
    "w03",
    "w04",
    "w05",
    "w06",
    "w07",
    "w08",
    "w09",
    "w10",
    "z06",
    "z07",
    "j01",
    "j02",
    "j04",
    "j06",
    "j08",
    "y05"
  ],
  "parallel": [
    "b03",
    "g05",
    "c06",
    "t03",
    "d07",
    "s05",
    "k07",
    "u01",
    "u03",
    "o02",
    "i05",
    "q08",
    "a06"
  ],
  "relations": [
    "b01",
    "b02",
    "g01",
    "g06",
    "x01",
    "x03",
    "x04",
    "x06",
    "x07",
    "x10",
    "x11",
    "x12",
    "x14",
    "x17",
    "x19",
    "x20",
    "x22",
    "m03",
    "m04",
    "m06",
    "m07",
    "c03",
    "d01",
    "d05",
    "d08",
    "r01",
    "r02",
    "r04",
    "s06",
    "s08",
    "k02",
    "k03",
    "k08",
    "k09",
    "q03",
    "e01",
    "e02",
    "e03",
    "e04",
    "e05",
    "u04",
    "h01",
    "h02",
    "h04",
    "h05",
    "l01",
    "l04",
    "l06",
    "v01",
    "v03",
    "v04",
    "v05",
    "i01",
    "i02",
    "i08",
    "i09",
    "i10",
    "o01",
    "o03",
    "o05",
    "a01",
    "a04",
    "a07",
    "a08",
    "a09",
    "z01",
    "z02",
    "z03",
    "z04",
    "z05",
    "j03",
    "j05",
    "j07",
    "y01",
    "y02",
    "y03",
    "y04",
    "y06"
  ]
};
  const types=Object.freeze(Object.fromEntries(Object.entries(groups).flatMap(([type,ids])=>ids.map(id=>[id,type]))));
  const notes={
  "u01": "Boundary、Information、Machinery 与 Energy 是细胞协作要素，布局不表示发生先后。",
  "o02": "出生、死亡和迁移共同进入数量收支；density/stage 改变各项 rate，布局不表示发生先后。",
  "q08": "按分析目标选择并组合处理；log/VST、z-score 与 batch model 不构成所有任务都必走的管线。",
  "s05": "并列平台类型供选型比较；研究问题是选择依据，不是最后执行的一种平台。",
  "i05": "Tolerance、activation、memory 与 checkpoint 是相互作用的调控主题；checkpoint 不只在 memory 之后发生。"
};
  const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function render(chapter) {
    const requested=chapter.flowType||types[chapter.id];
    const type=['sequence','parallel','relations'].includes(requested)?requested:'relations';
    const sequential=type==='sequence';
    const label=sequential?'过程或工作流顺序':type==='parallel'?'并列要素或选项':'关联概念概览';
    const summary=chapter.flow.map(item=>`${item[0]}：${item[1]}`).join(sequential?'；接着，':'；');
    const boxes=chapter.flow.map((item,i)=>`${sequential&&i?'<span aria-hidden="true">→</span>':''}<div><b>${escape(item[0])}</b><small>${escape(item[1])}</small></div>`).join('');
    const note=notes[chapter.id]||(sequential?'所示过程或工作流的顺序概览；省略的分支、循环与适用条件见正文。':type==='parallel'?'并列要素或类型，布局不规定先后；细节与限制见正文。':'关联概念概览；布局不规定先后或单一路径，具体关系与分支见正文。');
    return `<figure class="concept-figure"><div class="concept-flow concept-flow-${type}" data-flow-type="${type}" role="img" aria-label="${escape(label+'：'+summary)}">${boxes}</div><figcaption>原创概念图 · ${escape(note)} 依据本章来源。</figcaption></figure>`;
  }
  const api={types,render};
  if(typeof module!=='undefined'&&module.exports)module.exports=api;
  if(typeof window!=='undefined')window.BIOCS_FLOWS=api;
})();
