window.BIOCS_BOOK.push({
  code:'07', title:'空间组学、增强子与剪接 Spatial Biology', description:'Visium HD、Xenium、CODEX 等空间平台；从 enhancer 和 splicing 走到肿瘤组织的多模态推断。', chapters:[
  {id:'s01',title:'Spatial biology：测量单位',subtitle:'组织里“谁、是什么、在哪里”是三个不同问题。',intro:'单细胞数据把细胞分开，却常在解离时丢掉原位置。空间实验尽量保留组织坐标；要读懂结果，先认清每个平台把信号分配给什么单位。',goals:['区分捕获式、成像式 RNA 与蛋白成像','识别像素、方格、RNA 分子、细胞和患者','理解空间分辨率不等于生物学准确率'],prereq:['b05','d07','d08'],image:['assets/spatial-platforms.svg','原创比较示意：组织切片进入 Visium HD 捕获网格、Xenium RNA 分子成像和 CODEX 蛋白成像，最后形成不同的数据单位','图形展示测量原理，大小和通量不按真实比例。',['visiumHD','xenium','codexPaper']],sections:[
    ['从组织到数据表：先画层级',`<p>一位<strong>patient / 患者</strong>可以提供多块组织；每块组织可做多张<strong>section / 切片</strong>。一张切片上有许多区域、细胞或网格点。某个点位的数值来自哪里，取决于实验：捕获式方法记录带空间条形码的区域，成像式 RNA 方法记录被解码的分子坐标，蛋白成像记录像素强度并常汇总到分割出的细胞。</p><p>统计时必须保留 patient → specimen → section → region → observation 的层级。十万点位来自三位患者，不能把十万当作患者组间比较的独立样本数。</p>`,['visiumMatrix','xeniumOutput','codexPaper']],
    ['两个实验都叫 spatial，却可能测不同对象',`<p>Visium HD 的基因表达 assay 通过空间条形码与测序把 RNA 信号放回组织；Xenium 的基因表达 assay 用循环原位成像解码选定 RNA 目标；经典 CODEX / PhenoCycler 用 DNA 条形码抗体做多轮蛋白成像。它们的信号分别接近<strong>测序 UMI 计数</strong>、<strong>解码 RNA 分子计数</strong>与<strong>荧光标记强度</strong>，不能把三张矩阵直接当成同一种量。具体产品还可能提供蛋白或联合 assay，须看实际文件的 feature type。</p><p>“高分辨率”也要追问：探针或方格有多细、细胞边界如何推断、能测多少目标、组织区域有多大。这些维度互相制约。</p>`,['visiumHD','xeniumOutput','codexPaper']],
    ['从研究问题选读数',`<p>想知道一块肿瘤中免疫相关转录程序在边缘如何变化，可先考虑覆盖较广的空间 RNA；想看某组特定细胞标记 RNA 在单个细胞中的位置，可考虑成像式 RNA；想看 PD-L1、CD3 等蛋白标记的细胞邻域，可考虑多重蛋白成像。选择前写清问题、样本可用性、目标列表和需要的尺度。</p><p>这些例子只说明测量与问题的匹配逻辑；任何平台的结果仍需独立病例、病理复核和适当验证。</p>`,['visium','xeniumPanel','codexPaper']],
    ['空间邻近不是细胞通信的直接证明',`<p>两种细胞在同一组织区域接近，说明空间上有机会接触；不自动证明受体结合、信号传递或因果作用。图像配准误差、二维切片、细胞分割错误和组织密度都会影响邻近统计。</p><p>先用统一的物理坐标定义距离，再比较随机置换或合适的空间背景；提出通信假设后，仍需蛋白、功能或扰动证据。</p>`,['xeniumSeg','codexPaper','nciTME']]
  ],worked:['把同一研究问题拆成三种数据需求',['问题：肿瘤边缘的 T 细胞是否靠近癌细胞，且处于活化状态？','位置：需要切片坐标、细胞边界及肿瘤区域标注。','身份：需要 T 细胞与癌细胞标记；活化需要与功能相关的独立测量。','统计：邻近距离可按细胞计算，组间推断仍应按独立患者汇总。']],terms:[['Spatial transcriptomics / 空间转录组','带组织坐标的 RNA 测量；输出单位依技术而变。','visium'],['Spatial proteomics / 空间蛋白组','在组织位置上观察多个蛋白标记。','codexPaper'],['Segmentation / 分割','根据图像或分子信号估计细胞边界。','xeniumSeg']],check:['为什么 Visium HD 的 2 µm 方格不能直接称为一个细胞？','方格是捕获表面的空间单位；一个细胞可覆盖多个方格，一个方格的 RNA 也未必只来自单个细胞。']},

  {id:'s02',title:'Visium HD：空间条形码与 binning',subtitle:'2 µm 是捕获网格尺寸，不是“天然单细胞”。',intro:'Visium HD 把组织切片的表达测量与空间网格、显微图像连接。计算分析通常从带坐标的稀疏矩阵开始，而不是从“每个细胞一行”的表开始。',goals:['说出捕获与空间条形码的逻辑','理解 2/8/16 µm bin 的取舍','读懂矩阵、坐标与图像配准文件'],prereq:['s01','d04'],flow:[['组织切片','保留形态与局部环境'],['带条形码方格','2 × 2 µm 捕获位置'],['文库和测序','读段连回空间 barcode'],['Space Ranger','表达矩阵 + 坐标 + 图像']],sections:[
    ['实验怎样保留“在哪里”',`<p>组织切片与具有空间条形码的捕获表面对应。Visium HD 的捕获网格由<strong>2 × 2 µm barcoded squares / 带条形码方格</strong>构成；测序读段携带可映射回方格的条形码信息。图像配准把分子网格放在 H&amp;E 或荧光显微图上。</p><p>这里的“2 µm”描述捕获单元的边长，不是光学像素、细胞直径，也不承诺每个方格都有足够 RNA 可单独可靠聚类。</p>`,['visiumHD','visiumSpatial']],
    ['为什么把方格合成 bin',`<p>单个 2 µm 方格可能只有少量分子。把相邻方格求和成 8 µm 或 16 µm bin，可提高每个单位的计数，但同时把不同局部结构混在一起。标准 Space Ranger 输出可包含多个 bin 尺度；分析结论可能随尺度改变。</p><p>例如一条很窄的免疫边界在 2 µm 图上可见，合到 16 µm 后可能被平均掉；反过来，过细单位的噪声又可能制造虚假的斑点。应展示敏感性分析，并写清所用尺度。</p>`,['visiumMatrix','visiumHD']],
    ['输出文件怎么连起来',`<p>按当前 Space Ranger 的 Visium HD 目录结构，先进入 <code>binned_outputs/square_002um</code>、<code>square_008um</code> 或 <code>square_016um</code>，不要把不同尺度的矩阵混成一张。每层的 <code>filtered_feature_bc_matrix</code> 存 feature × barcode/bin 的 UMI 计数；相应 <code>spatial/</code> 中的 <code>tissue_positions.parquet</code> 把位置键连接到阵列与图像坐标，图像和缩放文件也在空间输出中。具体目录随软件和 assay 版本核对。<a href="https://www.10xgenomics.com/support/software/space-ranger/latest/analysis/output-overview" target="_blank" rel="noopener noreferrer">10x 官方输出目录 ↗</a></p><p>仅有矩阵而没有坐标就无法做空间定位。把图叠到病理切片前先检查图像方向、尺度、组织检测和配准；坐标系错位会使“肿瘤边缘”标签落到另一块组织。</p>`,['visiumMatrix','visiumSpatial']],
    ['细胞类型推断仍是推断',`<p>可利用参考单细胞数据估计每个 bin 的细胞组成，也可结合显微图像分割来尝试细胞级汇总。参考图谱缺少肿瘤特殊状态、不同切片组织成分不一致或图像边界不清时，推断会偏。</p><p>报告时区分<strong>observed count / 观测计数</strong>与<strong>inferred cell type / 推断细胞类型</strong>；并保留原始网格、bin 大小和参考版本以便复核。</p>`,['visiumMatrix','cellxgene']]
  ],worked:['手算 binning 改变了什么',['四个相邻 2 µm 方格某基因 UMI 分别为 0、1、0、3。','合并后的一个 4 µm 示意 bin 得到 4 个 UMI；信号更稳定，但无法再分清来自哪个小方格。','若两个不同细胞各覆盖其中两个方格，合并的表达不再属于单一细胞。','真实平台的输出尺度与软件版本以对应文档为准。']],terms:[['Spatial barcode / 空间条形码','把测序读段映射回组织捕获位置的标识。','visiumHD'],['Bin / 合并区域','由多个相邻方格组成的分析单位。','visiumMatrix'],['Registration / 图像配准','把分子测量位置与显微图像坐标对齐。','visiumSpatial']],check:['把 2 µm 方格合成 8 µm bin 后，能说空间分辨率提高了吗？','不能。每个 bin 的计数通常增加，但位置被更大区域平均，空间细节减少。']},

  {id:'s03',title:'Xenium：原位 RNA 成像',subtitle:'从探针到 transcript coordinates，再到细胞矩阵。',intro:'本章以 Xenium In Situ Gene Expression 的 RNA 读出为例：先选目标 RNA，再在组织上通过多轮成像识别分子。具体 Xenium assay 也可能同时测蛋白，读文件时须按 feature type 分开。',goals:['理解 panel、成像循环与解码','区分 molecule table 与 cell matrix','识别 segmentation 和 panel bias'],prereq:['s01','m03'],flow:[['目标 panel','选择要看的 RNA'],['原位探针','在切片中标记目标'],['多轮荧光成像','解码分子身份与坐标'],['细胞分割','把分子分配到细胞']],sections:[
    ['先选哪些 RNA 能被看见',`<p>Xenium 是<strong>targeted in situ</strong>实验：探针针对预选基因或目标设计。组织准备后，探针结合、扩增与多轮荧光读出帮助识别 RNA 分子。能得到高精细的组织位置，并不意味着未进入 panel 的基因也被测到了。</p><p>如果研究重点是可变剪接或某个罕见转录本，不能仅看到该基因在 panel 中就默认可分辨 isoform；须核对探针具体覆盖的序列和设计限制。</p>`,['xenium','xeniumPanel']],
    ['先有分子点，再有“每细胞表达”',`<p>解码后可得到带基因身份和坐标的 transcript / 分子点。细胞级矩阵需要再把点分配给细胞边界；边界通常由核和其他染色图像经算法估计。肿瘤中细胞密集、形状不规则时，边界可能切错或漏掉胞质 RNA。</p><p><code>transcripts.parquet</code> 保存逐个解码点及质量、坐标信息；<code>cells.parquet</code> 是细胞摘要，<code>cell_feature_matrix.h5</code> 是按细胞与 feature 汇总的矩阵。官方默认矩阵只纳入通过 Q20 质量阈值且已分配给细胞的 transcript；未分配点或低质量点不能从矩阵的 0 值中恢复。若使用 RNA+蛋白 assay，还要查看 <code>feature_type</code>，因为蛋白特征是强度尺度，不是 RNA 分子数。<a href="https://www.10xgenomics.com/support/software/xenium-onboard-analysis/latest/analysis/xoa-output-understanding-outputs" target="_blank" rel="noopener noreferrer">10x 官方字段说明 ↗</a></p>`,['xeniumOutput','xeniumSeg']],
    ['QC：点、细胞与图像要一起看',`<p>检查阴性对照、分子质量分数、每细胞转录本数、未分配点比例，以及细胞边界是否符合组织形态。某区域某基因点数异常，可能是生物富集，也可能来自背景、光学伪影、细胞密度或组织质量。</p><p>空间邻域分析前，确保坐标使用同一单位与同一配准。选择代表性 ROI 展示时，也要报告选择规则，避免只展示最漂亮的区域。</p>`,['xeniumOutput','xeniumSeg']],
    ['Xenium 与 Visium HD 能怎样互补',`<p>可把 Visium HD 的较广 RNA 趋势用 Xenium 的目标分子位置细化，也可用单细胞参考帮助给 Xenium 的细胞群命名。但不同切片、不同 panel、不同定量流程不保证数值可一一相等。</p><p>同一病例的相邻切片仍可能因为厚度、方向和局部异质性而不同。跨平台整合先核对病例、区域、时间及组织标记，再讨论模型。</p>`,['visiumHD','xenium','gdcDoc']]
  ],worked:['为什么一个 RNA 点可能分给错误细胞？',['某分子点位于两细胞接触边界附近。','算法先从核/膜图像估计边界；若边界偏移，点会被归给另一细胞。','两细胞的 cell-feature matrix 因此改变，即使原始分子点坐标不变。','复核原始点图与分割图，并做边界或参数敏感性分析。']],terms:[['Gene panel / 目标面板','实验预先指定的可检测目标集合。','xeniumPanel'],['Transcript coordinate / RNA 分子坐标','原位成像解码后某 RNA 信号的位置。','xeniumOutput'],['Cell-feature matrix / 细胞特征矩阵','把分子或其他信号汇总到估计细胞后的矩阵。','xeniumOutput']],check:['Xenium 的 cell count 是直接从显微镜读出的原始事实吗？','不是。分子位置经过解码，细胞边界经过算法估计；cell count 是依据边界分配后的汇总。']},

  {id:'s04',title:'CODEX：多重空间蛋白成像',subtitle:'同一张切片怎样看许多蛋白标记？',intro:'在空间生物学语境中，CODEX 指 co-detection by indexing；它测的是抗体识别的蛋白标记。商用名称后来使用 PhenoCycler，因此读论文时常见两种称呼。',goals:['解释 DNA 条形码抗体与循环成像','从图像走到细胞 × 蛋白矩阵','认识抗体、配准和分割的限制'],prereq:['s01','d06','d08'],flow:[['抗体 panel','每种抗体带 DNA 标记'],['多轮读出','荧光探针结合、成像、去除'],['多通道图像','各蛋白信号对齐'],['细胞表型','分割与标记组合']],sections:[
    ['原理：标记相同切片的多种蛋白',`<p>CODEX 使用带有不同 DNA 寡核苷酸条形码的抗体识别组织中的蛋白。每轮让少数互补的荧光读出探针结合，拍照后移除读出探针，再测下一组。多轮图像合起来，使有限荧光通道支持更多蛋白标记。</p><p>抗体的靶标特异性和组织染色质量是前提。DNA 条形码在这里帮助“轮流显示抗体”，并不表示平台直接测 DNA 序列或 RNA 表达。</p>`,['codexPaper','codexBrand']],
    ['数据处理：像素到细胞',`<p>首先校正背景和多轮图像位移，再按核和细胞标记估计细胞边界。对每个细胞计算每个标记的荧光强度或阳性状态，就得到<strong>cell × marker matrix</strong>；同时保留细胞质心、轮廓和组织区域标签。</p><p>若细胞分割把紧邻的 T 细胞与癌细胞合成一个对象，矩阵会出现“同时高表达两类标记”的假双阳性细胞。应回看原始通道与边界叠图。</p>`,['codexPaper']],
    ['从 marker 组合到邻域',`<p>一个蛋白标记通常不能独自定义细胞类型。可组合上皮、免疫、增殖等标记，并与形态及位置核对，再观察细胞密度、最近邻距离和局部组成。ROI 选择、组织坏死与切片边缘都可能影响结果。</p><p>“T 细胞离癌细胞更近”是可测的空间描述；“T 细胞正在杀伤癌细胞”还需功能标记、时间信息或实验验证。</p>`,['codexPaper','nciTME']],
    ['名称与模态边界',`<p>Akoya 将商业 CODEX 产品更名为 PhenoCycler；文献中还可见 PhenoCycler-Fusion。与 Xenium 主体的 RNA 原位读出或 Visium HD 的空间测序相比，CODEX 的经典强项是多重<strong>蛋白</strong>定位。具体新产品可能另有组合测量能力，分析时以所用 assay 的说明书为准。</p><p>比较平台时先列出“组织类型、标记 panel、原始测量、细胞分割、坐标单位、病例数”六栏，再谈整合。</p>`,['codexBrand','codexPaper','xenium']]
  ],worked:['一个可疑的 CD3+ / pan-CK+ 对象怎么查？',['先查看 CD3 与 pan-CK 原始通道是否分别落在相邻细胞。','核对细胞边界及多轮图像配准；若两个核被合并，重新分割。','若确实共定位，再考虑抗体背景、通道串扰与生物解释。','在 QC 前，不把“奇特细胞类型”当作发现。']],terms:[['CODEX','以 DNA 条形码抗体和循环成像实现多重组织蛋白测量的方法。','codexPaper'],['PhenoCycler','Akoya 对 CODEX 商业系统使用的后续名称。','codexBrand'],['Multiplex imaging / 多重成像','在组织同一区域测量多个分子标记并保留位置。','codexPaper']],check:['CODEX 使用 DNA 条形码抗体，是否意味着它输出 DNA 变异表？','不意味着。DNA 标签服务于抗体读出；经典 CODEX 输出是组织蛋白标记图像及细胞级强度。']},

  {id:'s05',title:'其他空间平台与选型',subtitle:'MERFISH、CosMx、IMC 属于哪条技术路线？',intro:'空间技术不断变化，背平台名字很快会过时。按“测量分子、读出方式、输出单位”分类，才能理解新平台和论文。',goals:['把常见平台放到正确模态','理解 panel 与覆盖的权衡','设计公平的平台比较'],prereq:['s02','s03','s04'],flow:[['捕获 + 测序','Visium 系列'],['RNA 原位成像','Xenium / MERFISH / CosMx'],['蛋白多重成像','CODEX / IMC'],['研究问题','决定平台和验证']],sections:[
    ['成像式 RNA：MERFISH 与 CosMx',`<p><strong>MERFISH</strong>以多轮原位荧光读出和容错编码识别 RNA；<strong>CosMx SMI</strong>也通过循环原位读出测组织中的 RNA，并有相应蛋白检测方案。和 Xenium 一样，应检查目标集合、点位质量、细胞分割及组织准备；名称相似不保证实验性能或输出文件一致。</p><p>成像式平台能提供细胞或亚细胞尺度的 RNA 位置信息。目标覆盖从有限 panel 到更广的转录组流程，取决于平台和 assay 版本；未纳入所用 assay 的基因不能从“未检测到”推断生物学缺失。</p>`,['merfish','cosmx','xeniumPanel']],
    ['另一种蛋白读出：IMC / Hyperion',`<p><strong>Imaging Mass Cytometry, IMC</strong>在组织中使用金属标记抗体，由仪器成像读出多重标记。它与以荧光循环为核心的 CODEX 在信号物理原理上不同，但分析同样要处理抗体 panel、像素、细胞分割与空间邻域。</p><p>不能只按“能测多少 marker”选平台：样本兼容性、覆盖区域、速度、抗体质量、像素尺度、试剂成本和已有数据都影响选择。</p>`,['imc','codexPaper']],
    ['做技术比较时避免苹果和橘子',`<p>比较敏感度或细胞类型分辨能力时，最好使用相同组织、相近区域与可对齐的目标集合。测全转录组倾向的平台与目标 panel 平台可回答的问题范围不同；RNA 与蛋白的数值单位也不同。</p><p>若一个平台用高质量 FFPE 区域，另一个用坏死区，差异未必来自技术本身。报告样本处理、ROI、panel、软件版本和过滤步骤。</p>`,['visiumHD','xenium','imc']],
    ['从公开数据练习',`<p>读取公开空间数据时，先下载元数据和预处理输出，确认病例数、组织来源、平台、数据许可、参考基因组或 panel 版本。GEO 可存放相关研究提交，但具体文件格式因研究和平台而异；平台官方示例则适合练习文件结构。</p><p>第一份练习应先完成“在切片上定位几个可信 marker”，再做细胞邻域或多模态建模；提前保留图像和坐标的对应关系。</p>`,['geo','visiumMatrix','xeniumOutput']]
  ],worked:['为“免疫细胞在肿瘤边缘的蛋白状态”选技术',['核心读数是蛋白标记及细胞邻域，优先考虑多重蛋白成像。','列出需要的标记，并核对抗体能否在样本保存方式下工作。','若还要无偏寻找 RNA 程序，可加覆盖较广的 RNA 测量，但两层样本要能对齐。','对每一种平台都按患者级而非像素级规划重复。']],terms:[['MERFISH','以容错编码和多轮原位成像识别 RNA 的方法。','merfish'],['CosMx SMI','用于组织空间分子成像的商业平台。','cosmx'],['IMC / 成像质谱流式','使用金属标记抗体进行组织多重成像的技术。','imc']],check:['Xenium panel 中没有 gene X 却没有检测到 X，能说明组织不表达 X 吗？','不能。没有为 X 设计或纳入读出目标，就没有测它。']},

  {id:'s06',title:'Enhancer：远端调控怎样影响基因',subtitle:'一段非编码 DNA 为什么会改变肿瘤细胞的 RNA？',intro:'Central Dogma 说明序列信息怎样流向 RNA 和蛋白；enhancer 进一步解释不同细胞何时、何处转录。非编码区域也可能具有关键作用。',goals:['区分 promoter、enhancer 与候选 cCRE','按证据强弱寻找靶基因','理解开放染色质不等于功能证明'],prereq:['m03','m06','d05'],flow:[['DNA 调控区域','可能含 TF 结合位点'],['染色质状态','细胞类型相关的可及性'],['promoter 接触','候选靶基因转录'],['RNA 读数','观察到的表达变化']],sections:[
    ['promoter 与 enhancer 扮演什么角色',`<p><strong>Promoter / 启动子</strong>与转录起始相关；<strong>enhancer / 增强子</strong>是可影响转录的调控 DNA 元件，可能离目标基因较远。增强子不是“任何非编码区”，也不是固定写着某一个基因名字的开关：其作用依赖细胞类型、转录因子、染色质和实验条件。</p><p>一段区域可有多个候选靶基因，最近的基因未必是真靶。肿瘤中的拷贝数变化、突变或染色质改变都可能影响这一调控关系，但需逐步验证。</p>`,['nhPromoter','encodeGlossary','nciGenetics']],
    ['如何从实验找到候选区域',`<p>ATAC-seq 给出染色质可及性峰，H3K27ac 等标记与某些活跃调控区域相关；ENCODE 的<strong>cCRE / candidate cis-regulatory element</strong>整合多种生化信号，把区域标为 promoter-like 或 enhancer-like 候选。这里的 <em>candidate</em> 很重要：信号表明“值得检验”，并非已经证明调控了某基因。</p><p>同一基因组位置在 T 细胞与癌细胞中的调控状态可能不同。拿混合组织的 ATAC 峰直接解释癌细胞表达，容易混淆细胞来源。</p>`,['encodeGlossary','encodeScreen','encodeATAC']],
    ['enhancer 到靶基因：证据阶梯',`<p>首先核对 genome build 和区间；再看区域在相关细胞类型是否开放、是否具有相关组蛋白标记。接着看与候选基因的染色质接触或跨样本表达关联。最强的机制支持通常来自对候选区域的扰动以及靶 RNA 或表型改变。</p><p>相关性和距离可排序假设；CRISPR 删除或抑制等扰动更接近测试因果，但也要检查脱靶、局部结构效应和独立重复。</p>`,['encodeScreen','encodeGlossary','os16']],
    ['肿瘤例子：不要跳过中间步骤',`<p>假设某肿瘤亚型中一处远端区域开放且附近癌基因 RNA 升高。可能是该区域调控此基因，也可能是拷贝数、细胞组成或其他调控因子同时造成两种变化。优先用配对的 DNA、ATAC、RNA 与纯度信息缩小解释。</p><p>表达差异和 enhancer 位置写进论文图示前，明确标注“候选调控关系”或“经扰动验证”，不要画成没有证据的确定箭头。</p>`,['encodeATAC','gdcRNA','gdcDoc']]
  ],worked:['从 ATAC peak 到 enhancer 假设的四步',['在 GRCh38 上找到一段 ATAC peak，先确认患者与细胞来源。','查看 ENCODE SCREEN 的 cCRE 注释，并记录其仅为候选分类。','列出可能靶基因，检查接触、表达关联和拷贝数混杂。','设计扰动和独立重复，观察候选靶基因 RNA 与细胞表型。']],terms:[['Enhancer / 增强子','可能在远处影响基因转录的 DNA 调控元件。','encodeGlossary'],['cCRE / 候选顺式调控元件','由生化信号预测具有调控特征的基因组区域。','encodeGlossary'],['ATAC peak / 可及性峰','ATAC-seq 中信号富集的基因组区间。','encodeATAC']],check:['ATAC peak 离 MYC 最近，是否已证明它调控 MYC？','没有。距离与可及性只生成候选假设；还需细胞类型、接触、表达及扰动等证据。']},

  {id:'s07',title:'Splicing：从 exon 组合到 RNA 事件',subtitle:'gene count 不变，细胞功能也可能变。',intro:'剪接将前体 RNA 的不同区域连接成成熟转录本。对计算研究者，关键是把 gene、transcript、splice junction 与蛋白后果分开。',goals:['看懂基本可变剪接事件','理解 junction read、PSI 与 isoform','识别短读长数据的推断边界'],prereq:['m04','d04'],flow:[['pre-mRNA','多个 exon 与 intron'],['spliceosome','选择剪接位点'],['RNA isoforms','不同 exon 连接方式'],['蛋白或调控','可能改变结构、稳定性或位置']],sections:[
    ['从基本剪接到可变剪接',`<p>对许多真核蛋白编码基因，<strong>spliceosome / 剪接体</strong>识别前体 RNA 的剪接位点，移除内含子并连接外显子。可变剪接允许同一基因出现不同 exon 组合，常见描述包括 exon skipping / 外显子跳读、替代 5′/3′ 位点和 intron retention / 内含子保留。</p><p>并非所有 transcript 都会产生不同蛋白：有的差异只在非翻译区，有的 RNA 会被降解。因此从“剪接差异”到“蛋白功能改变”还有几步。</p>`,['nhSplice','ncbiRNA','gencode']],
    ['读数：gene count、junction 与 PSI',`<p>gene-level count 把一个基因的多种转录本合并。跨越两段 exon 接缝的<strong>junction reads</strong>能支持某种连接方式；常用的 <strong>PSI / percent spliced in</strong> 表示特定外显子或事件的纳入比例，定义依事件和工具而定。</p><p>短读长 RNA-seq 可能无法唯一确定完整 transcript：不同 isoform 可共享大部分 exon。稀疏覆盖、读长、比对和注释版本都会影响 PSI 或 transcript 丰度估计。</p>`,['rmats','gencode','gdcRNA']],
    ['比较组别时保留生物重复',`<p>“某事件在肿瘤样本中 PSI 比正常组织低”应在患者或独立样本层统计，考虑批次、组织组成、表达量和测序覆盖。若只找到一两个 junction read，比例可能非常不稳定。rMATS 等方法在重复样本下建模剪接差异，但软件显著性仍不是功能证据。</p><p>若要研究具体蛋白后果，可进一步检查阅读框、蛋白结构域、RNA 稳定性，并用 RT-PCR、长读长或蛋白证据验证关键事件。</p>`,['rmats','nhSplice','pride']],
    ['剪接位点变异如何接进肿瘤多组学',`<p>DNA 变异靠近 splice site 或调控剪接的序列，可能改变 RNA 产物；反过来，剪接变化也可能来自转录因子、RNA 结合蛋白或细胞状态，未必由该基因自身 DNA 变异造成。</p><p>最有力的案例把同一病例的 DNA 事件、异常 junction、转录本变化、蛋白后果和功能实验串起来，同时排除正常细胞混入与批次因素。</p>`,['nhSplice','rmats','gdcDNA']]
  ],worked:['PSI 怎样揭示 gene count 看不到的变化',['教学例：样本 A 的事件纳入 reads 为 80，跳过 reads 为 20，简化 PSI≈80%。','样本 B 为 30 和 70，简化 PSI≈30%；两组 gene 总 count 都可以是 100。','真实 PSI 估计需按事件结构、junction 长度、覆盖与模型调整。','结论应是“剪接模式变化的证据”，不是“蛋白活性必然变化”。']],terms:[['Splice junction / 剪接接缝','成熟 RNA 中两个区域连接形成的边界。','rmats'],['PSI / percent spliced in','描述某剪接事件纳入比例的常用量。','rmats'],['Isoform / 转录本异构体','同一基因产生的不同 RNA 形式。','nhSplice']],check:['两个病例某基因的 gene count 相同，是否能排除与疾病有关的剪接改变？','不能。不同 isoform 或 exon 纳入比例可改变，但基因总量不变。']},

  {id:'s08',title:'把空间、enhancer 与 splicing 接回肿瘤研究',subtitle:'从跨模态故事走向可检验的证据链。',intro:'空间位置、非编码调控和 RNA 剪接常出现在同一篇肿瘤论文里。整合时先找共同病例、明确样本层级，再逐条验证机制箭头。',goals:['设计一个多模态肿瘤问题','避免跨切片/跨平台过度拼接','建立可复核的分析和验证方案'],prereq:['s02','s03','s04','s06','s07','r02'],flow:[['临床问题','癌种、区域、患者结局'],['分子层','DNA、enhancer、RNA、splice'],['空间层','Visium / Xenium / CODEX'],['验证','独立病例与扰动实验']],sections:[
    ['先写一条可以被反驳的假设',`<p>例子：某候选增强子状态改变，导致肿瘤细胞中受体基因的特定剪接形式增加，并使肿瘤边缘的免疫细胞分布改变。每一段都要对应测量：DNA/ATAC 或调控实验、junction/isoform RNA、蛋白状态、空间细胞位置。</p><p>若只有 TCGA bulk RNA 和一个公开空间切片，最多提出跨数据集的假设；不能说“同一患者中 enhancer 造成了局部 T 细胞排斥”。</p>`,['gdc','encodeScreen','rmats','visiumHD']],
    ['建立 sample manifest，再整合',`<p>最小清单包括 patient ID、癌种/亚型、取样时间、部位、组织块、切片编号、平台、panel/参考版本、是否同片或相邻片、图像文件及坐标系。把这些信息做成一张表，明确哪些模态真正来自同一患者，哪些只属于类似队列。</p><p>图像对齐只能解决位置问题，不能让不同病例变成配对样本；相邻切片也可能因肿瘤异质性呈现不同局部细胞结构。</p>`,['gdcBarcode','visiumSpatial','xeniumOutput']],
    ['空间统计的独立单位和背景',`<p>可以在细胞级计算某两类细胞的距离、接触次数或局部富集，但患者组间推断要按患者汇总或建立层级模型。还需控制组织面积、边界、细胞密度、ROI 选择与坏死区；随机标签置换要保留合适的组织结构。</p><p>图像分割或 bin 大小变化若使结果翻转，应明确报告为方法敏感，而非只保留有利参数。</p>`,['xeniumSeg','visiumMatrix','codexPaper']],
    ['形成可复核的结论',`<p>最终报告应分层写：“观测到某区域 RNA 信号”“推断这些点位富集某细胞类型”“候选 enhancer 与表达相关”“扰动支持该 enhancer 对目标基因有作用”。每个动词表示不同证据强度。</p><p>公开代码、版本、参数、样本清单和图像 QC；保留不支持假设的结果。若延伸到患者预后，拆分与评估仍以患者为单位，并在独立队列验证。</p>`,['gdcDoc','encodeScreen','visiumSpatial','rmats']]
  ],worked:['检查一张“空间多组学机制图”',['图中每个箭头旁标注数据来源及病例是否配对。','把测量事实、算法推断和因果实验分成三种线型。','检查 ROI、分割、binning 与临床拆分的敏感性。','若缺少中间层，降级为待验证假设，而不是补上未经测量的箭头。']],terms:[['Sample manifest / 样本清单','记录病例、组织、切片、模态与文件对应关系的表。','gdcDoc'],['ROI / 感兴趣区域','从组织图像中选定用于观察或分析的区域。','visiumSpatial'],['Multimodal integration / 多模态整合','在明确样本映射与测量差异后联合解释多种数据。','gdcDoc']],check:['TCGA 病例 A 的 RNA 与另一研究病例 B 的 CODEX 图像出现相似趋势，能证明 A 患者的 RNA 导致 B 图像中的蛋白空间模式吗？','不能。两个病例不配对，且 RNA 与蛋白/空间之间缺少机制验证；只能作为跨队列假设线索。']}
]});
