window.BIOCS_BOOK.push({
  code:'08', title:'计算数据实战 Data Literacy', description:'从实验文件、样本键和矩阵语义出发，读懂组学、空间、影像与临床数据，再建立可信模型。', chapters:[
  {id:'k01',title:'一份生物数据是怎么来的',subtitle:'从实验材料到 raw file、processed file 和分析表。',intro:'生物数据不是一张天然干净的 CSV。它沿着“患者—材料—实验—仪器—软件”生成；任何一级的信息丢失，模型都可能学到错误对象。',goals:['为文件找到实验与样本来源','区分原始、处理中和分析级数据','识别每类文件里的观测单位'],prereq:['d01','d02','r01'],image:['assets/data-lineage.svg','原创数据谱系示意：患者、组织样本、实验、原始文件、处理文件与分析矩阵','示意结构不代表所有平台都经过同样步骤。',['gdcDictionary','gdcSample','hts']],sections:[
    ['先画 data lineage / 数据谱系',`<p>一位患者可能有原发灶、复发灶和正常组织样本；同一块组织可切片、提取 DNA、RNA 或蛋白；一次实验又可产生多个仪器文件。<strong>case / sample / aliquot / file</strong>是不同实体，不是“某患者的一条记录”的别名。GDC 的数据字典显式描述这些实体与关系。</p><p>开始分析前写一个 <strong>manifest / 文件清单</strong>，至少含患者、样本、组织类型、时间、实验、文件 ID、处理流程和版本。<a href="data-lab.html#join">数据练习</a>可以手动试一遍连接。</p>`,['gdcDictionary','gdcSample']],
    ['P01 的三行 manifest：join 后发生什么',`<p>沿用 <a href="#d01">D01</a> 的虚构例子：<code>P01 / T01</code> 有 <code>F-DNA</code>、<code>F-RNA</code>、<code>F-IMG</code> 三份输出。临床表只有一行 <code>case=P01, outcome=12 个月时仍在随访</code>。按 <code>case</code> 把它接到文件清单，三行都会复制同一个 outcome；行数变 3，<strong>独立患者数仍是 1</strong>。这叫一对多连接，必须在分析前说清目标单位。</p><p>要分析 RNA，就先筛 <code>assay=RNA-seq</code> 并核对 <code>F-RNA</code> 的工作流、单位和样本；要研究患者结局，就把多文件信息汇总到患者层，避免三次计算同一个人的结局。进入 <a href="real-data-walkthrough.html">真实 GDC 单文件练习</a>，再核对官方 case、sample 与 file ID。</p><details><summary>先猜再展开：按 case join 得到的三行能直接喂给患者级生存模型吗？</summary><p>不能当成三位患者。三个文件共享 P01 的结局；应先确定患者层的变量或使用能表示嵌套结构的方法，并按病例划分训练和测试。</p></details>`,['gdcDictionary','gdcSample','sklearnGroup']],
    ['文件扩展名告诉你大致在哪一步',`<p>测序可从 <code>FASTQ</code>读段开始，经比对生成 <code>SAM/BAM/CRAM</code>，变异检测产生 <code>VCF</code>，RNA 定量产生 count 表。空间平台可能给稀疏矩阵、位置文件和组织图像；单细胞分析常用 <code>h5ad</code>封装矩阵与元数据；图像可能是 OME-TIFF 或平台专用格式。</p><p>扩展名不能单独决定语义：两个 TSV 可能一个是 gene count，另一个是临床元数据。要看文件说明、列名、单位、参考版本和生成工作流。</p>`,['hts','gdcRNA','anndata','omeTiff']],
    ['raw 与 processed 的边界',`<p><strong>Raw / 原始</strong>总是相对于某一步而言：FASTQ 比 gene count 更靠近仪器读出，而所谓 <strong>raw gene count</strong> 已经经过比对、注释和读段分配，只是尚未做 TPM/FPKM 等表达量变换。<strong>Processed / 处理后</strong> 也可能进一步经过过滤、细胞分割或标准化；每一步都继承软件参数、参考版本和阈值选择。</p><p>例如 GDC RNA 表中的 raw count 与 TPM 虽在同一下载结果里，单位和用途不同；Xenium 的分子坐标与 cell matrix 中间还经过质量过滤和细胞分割。复现研究需要记录每一步来源，不能凭文件名里的 “raw” 推断它未经计算。</p>`,['gdcRNA','xeniumOutput','xeniumSeg']],
    ['给每张表写 schema',`<p>用一句话说明每一行是什么、每一列是什么、主键和外键是什么、数值单位是什么、缺失值表示什么。例如“每行一个病例，每列一个诊断字段”与“每行一个变异事件，按样本重复”不能用同一段 groupby 代码解释。</p><p>先检查唯一性与行数，再画图、做机器学习。数据表形状正确，只说明代码跑通；它不证明样本映射或生物学问题正确。</p>`,['gdcDictionary','gdcRepo']]
  ],worked:['为一个下载目录写最小 manifest',['取一个 RNA 文件，记录 file ID、case ID、sample ID、sample type 和 workflow。','打开文件说明，确认数值是 raw count 还是转换后的表达量。','核对是否还有对应的图像、临床信息或其他模态，记录关联键。','把“这是什么文件”写成一条可由别人复核的记录。']],terms:[['Data lineage / 数据谱系','记录数据从材料到最终分析结果的处理来源和步骤。','gdcDictionary'],['Aliquot / 分装材料','从样本或分析物产生、用于特定实验的材料实体。','gdcSample'],['Manifest / 文件清单','把文件与样本、实验和处理信息对应起来的元数据表。','gdcRepo']],check:['只拿到名叫 sampleA.tsv 的文件，能断定它是一位患者的 RNA count 吗？','不能。要核对文件说明、行列单位、case/sample 映射、实验和处理流程。']},

  {id:'k02',title:'ID、主键与跨表连接',subtitle:'机器会成功 join，但生物样本可能接错。',intro:'计算生物学里的“样本”是层级关系。把 case、sample、cell 和 tile 混成同一个 ID，会让数据库操作在语法正确时仍产生错误研究队列。',goals:['分清一对一与一对多','用断言检查重复和丢失','按正确实体连接多组学'],prereq:['k01','r02'],flow:[['case 表','一位参与者一行'],['sample 表','一个病例可有多个组织'],['assay 表','同一材料可有多种实验'],['feature 表','每个实验有多条特征']],sections:[
    ['每张表先定义 primary key',`<p>病例表可能以 case ID 唯一，材料表以 sample ID 唯一，测序文件以 file ID 唯一。case ID 在材料表中可重复，这是合法的一对多；sample ID 在一张声称“一行一个样本”的表中重复，就需要调查。</p><p>真实 GDC 模型还有 portion、analyte、aliquot 等层级；不能仅用文件名或 gene symbol 代替生物材料的键。</p>`,['gdcCase','gdcSample','gdcDictionary']],
    ['inner join 会悄悄改变队列',`<p>假设临床表有 5 位病例，RNA 表有 4 位，DNA 表有 3 位；三表 inner join 最多只剩共同出现的病例。丢掉的人若集中在晚期或低质量样本，最终队列代表的人群会改变。</p><p>在每次 join 前后分别统计病例数、样本数、重复键、缺失比例与组别分布。缺失本身是研究结果的一部分，不应在代码里静默消失。</p>`,['gdcRepo','gdcDictionary']],
    ['one-to-many 最容易制造假样本量',`<p>若患者 P1 有两张病理切片、每张切出 100 个 tile，临床表只有 P1 一行。将临床标签 join 到 tile 表后出现 200 行是预期的；这不是新增 200 位患者。若同一 P1 的 tile 跨训练和测试，模型会泄漏患者特征。</p><p>在 SQL 或 pandas 中，可以把预期连接关系写成断言：case→sample 是一对多，sample→某 assay 文件可能仍是一对多，最终训练样本层级必须显式确定。</p>`,['gdcSample','sklearnGroup']],
    ['构建跨组学病例表',`<p>先在各模态内选好组织类型、时间与质量，再产生每个 case 的可用样本映射。若同一病例有两个 RNA 样本，要预先定义保留、聚合还是分层分析；不能随意挑第一条。最后只连接真正配对的材料，报告交集病例及排除原因。</p><p>TCGA barcode 可帮助定位层级，但跨项目时应优先使用官方实体关系。<a href="data-lab.html#join">交互练习：看看错误 join 会怎样放大行数</a>。</p>`,['gdcBarcode','gdcDictionary']]
  ],worked:['检查一个危险的连接',['临床表：P1、P2 各一行；材料表：P1-T1、P1-T2、P2-T1 共三行。','按 patient ID 连接后应该是三行，而不是两个独立病例。','如果还把每个样本的 100 个 tile 接入，会得到 300 行，但独立病例仍只有两个。','建模拆分时以 P1、P2 为组，不在 tile 层随机打散。']],terms:[['Primary key / 主键','在所定义表中唯一标识一条记录的字段。','gdcDictionary'],['Cardinality / 基数关系','两表实体间一对一、一对多或多对多的关系。','gdcDictionary'],['Inner join / 内连接','只保留两侧键都存在的记录。','gdcRepo']],check:['临床 100 行 join 后变成 5,000 行，是否有了 5,000 位独立患者？','没有。应检查一对多或多对多扩张；独立患者仍由唯一 case ID 数决定。']},

  {id:'k03',title:'基因组坐标、build 与基因 ID',subtitle:'同一个 chr:pos 字符串并不总指同一个碱基。',intro:'序列分析是带参考坐标的计算。基因组版本、坐标起点、区间闭合规则和转录本版本任何一项错位，都可能把一个变异标到错误区域。',goals:['区分 GRCh37/GRCh38','读懂 BED 与 VCF 坐标规则','记录 Ensembl ID 与转录本版本'],prereq:['g02','d03','k01'],flow:[['参考组装','GRCh37 / GRCh38'],['坐标系统','0-based / 1-based'],['基因注释','gene / transcript / exon'],['生物解释','变异与调控区域']],sections:[
    ['位置要带上 reference assembly',`<p>一个 <code>chr7:position</code> 只有在指定参考组装后才可解释。GRCh37 与 GRCh38 是不同的人类参考版本；不能只因染色体名相同就直接连接坐标。转换坐标通常还要检查未映射、多重映射和 REF 碱基是否匹配。</p><p>分析结果至少记录物种、build、染色体命名、参考序列、注释版本和所用转换方法。</p>`,['ensemblMap','gdcRNA','hts']],
    ['BED 与 VCF 的 off-by-one 陷阱',`<p>VCF 的 POS 按规范以 1 为首位；常见 BED 区间使用 0-based、左闭右开。例如某个单碱基位点在 VCF 是 POS=101，对应 BED 可写作 start=100、end=101。直接把 101 填进 BED start 会整体错开一位。</p><p>区间操作前先写出“基于 0 还是 1、右端是否包含”；可拿已知变异和参考碱基做单元验证，尤其在 splice site、motif 和 enhancer 边界分析中。</p>`,['vcf','ucscCoord']],
    ['symbol、gene ID 与 transcript ID 不是一回事',`<p>基因 symbol 是便于人读的名称，会有别名或变化；Ensembl stable ID 较适合机器连接，但仍应记录版本。一个 gene 可有多个 transcript，变异的编码后果可能因转录本而不同。不能把 gene ID 与 transcript ID 当成同一列。</p><p>做跨数据库 join 前，列出输入 ID 命名空间、版本号、物种以及一对多映射的处理规则；不要仅靠大写字母相同就匹配。</p>`,['ensemblIDs','gencode','nhSplice']],
    ['坐标相同也要核对等位基因',`<p>VCF 中 REF/ALT 描述相对于参考的变化。同一位置可能有不同替代等位基因，插入缺失还存在表示方式差异。一个 “chr、pos” join 若忽略 REF、ALT 与 build，可能把不同事件合并。</p><p>变异可采用规范化表示和参考序列检查；最终报告保留完整事件、样本与检测条件。</p>`,['vcf','gdcVCF']]
  ],worked:['把单碱基 VCF 位置写成 BED',['给定 VCF <code>CHROM=7, POS=101, REF=A, ALT=G</code>。','在相同 build 与染色体命名下，单碱基 BED 可写 <code>chr7 100 101</code>。','检查 BED 的区间长度是 1，并核对参考位置 101 确为 A。','若来源 build 不同，先做正式坐标转换与 REF 检查。']],terms:[['Reference assembly / 参考组装','用于给序列指定位置的基因组版本。','ensemblMap'],['BED interval / BED 区间','常用 0-based、左闭右开的基因组区间表示。','ucscCoord'],['Ensembl stable ID','用于标识基因、转录本等注释实体的稳定编号。','ensemblIDs']],check:['把 VCF POS=101 当作 BED start=101 有什么风险？','在常见 BED 规则下会右移一个碱基，可能错判变异是否落在目标区域。']},

  {id:'k04',title:'RNA 矩阵：count、CPM、TPM 与变换',subtitle:'数值看起来都像“表达量”，计算意义却不同。',intro:'RNA-seq 最常见的错误，是把不同来源、单位和预处理的数值放进同一模型。先看数值如何形成，再选择相应的统计方法。',goals:['说出 gene × sample 矩阵的两条轴','手算简化 CPM','区分原始 count 与 TPM/对数变换'],prereq:['d04','k01'],flow:[['reads','测序深度和比对'],['gene count','离散原始读数'],['归一化','深度/组成等校正'],['统计或可视化','使用适合的输入']],sections:[
    ['一列 count 属于一个样本',`<p>GDC 的 RNA pipeline 以 STAR 产生 gene-level raw read counts，并附加 FPKM、TPM 等变换。<strong>Raw count</strong>是离散读段计数，受文库大小、基因长度、组成偏差及测量流程影响；它不是“细胞中该基因 RNA 分子的绝对数量”。</p><p>比较两个样本前，确认列确实是样本、行是同一种基因 ID 与注释版本、计数流程一致；组织混合与肿瘤纯度也会影响读数。</p>`,['gdcRNA','ensemblIDs']],
    ['手算 CPM，看清深度因素',`<p>简化的 <strong>CPM / counts per million</strong> = gene count ÷ 总可用 counts × 1,000,000。样本 A 某基因 100 reads、总数 1,000；样本 B 200 reads、总数 2,000；两者 raw count 不同，但该基因 CPM 都是 100,000。这个小例子只演示测序深度的影响。</p><p>真实差异表达还要处理组成偏差、重复样本与离散计数的方差；不能把 CPM 的简单比值当作完整的差异分析模型。<a href="data-lab.html#counts">在数据练习中切换 raw 与 CPM</a>。</p>`,['gdcRNA','deseq2']],
    ['TPM 和 log 值有另外的语义',`<p><strong>TPM</strong>先考虑长度相关的计数，再按样本总量缩放；它与 raw count 不同。<code>log1p(x)</code> 是对数变换以压缩动态范围，变换后不再是原始计数。不同来源的 TPM 还可能因流程和参考版本不同而不可直接拼接。</p><p>差异表达工具常要求相应的原始 count 或特定输入，不能因为 TPM 数字更“平滑”就替代。模型、图表和代码里均要写明单位及变换。</p>`,['gdcRNA','deseq2']],
    ['零值和高值都需要背景',`<p>若某基因确实进入测量和计数流程，<code>0</code> 表示该样本在此流程下未计到它；原因可能是表达很低、捕获/测序不足或读段未能分配。<strong>目标根本未纳入靶向 panel 时应标为未测，而不是填 0。</strong>极高读数可能反映强信号、细胞比例变化或技术偏差。单细胞数据更稀疏，解释还依赖 cell-level QC。</p><p>先核对 feature 是否在测量范围内，再看样本总量、检出基因数、分布及可用的对照，选择归一化或过滤方式。不要在全数据中决定过滤阈值后再把同一数据宣称为独立测试集。</p>`,['gdcRNA','scanpyQC','sklearnLeak']],
    ['进一步区分每一种 normalized 数值',`<p>本章是数据阅读地图。<a href="#q05">Q05</a> 逐步算 raw 与 CPM，<a href="#q06">Q06</a> 用同一张矩阵算 RPKM/FPKM/TPM，<a href="#q07">Q07</a> 解释 DESeq2 size factor 与 TMM，<a href="#q08">Q08</a> 再拆开 log、VST、z-score 和批次。<a href="data-lab.html#normalization">交互表</a>可直接切换数值观察。</p>`,['gdcRNA','deseq2Guide','tmmPaper']]
  ],worked:['两个样本 count 相差两倍，表达比例相同吗？',['A：gene X=100、总 counts=1,000，CPM=100,000。','B：gene X=200、总 counts=2,000，CPM=100,000。','在这个简化例子中占比相同；不能据此断言每个细胞的 RNA 绝对量完全相同。','若要做组间检验，仍需生物重复和适合 count 的模型。']],terms:[['Raw count / 原始计数','特定定量流程给出的离散读数。','gdcRNA'],['CPM','按样本文库总数缩放的每百万计数。','deseq2'],['TPM','同时考虑长度相关计数和样本总量的表达尺度。','gdcRNA']],check:['A 样本 raw=100，B 样本 raw=200，能直接说 B 的表达是 A 两倍吗？','不能。要检查测序深度、归一化、组织组成和实验流程。']},

  {id:'k05',title:'变异表：VCF、MAF、CNV 怎么读',subtitle:'“有突变”是一个经过检测与过滤的判断。',intro:'DNA 分析中的每一行，可能描述一个基因组事件、一个样本中的事件或一个更大区间。先区分 variant call、注释和肿瘤细胞群体比例。',goals:['读 VCF 核心列与样本字段','区分 VAF、纯度与克隆比例','理解 MAF 和 CNV 的不同粒度'],prereq:['d03','k03'],flow:[['DNA reads','覆盖与碱基质量'],['variant calling','REF / ALT 与证据'],['annotation','转录本和功能标签'],['cohort table','MAF / CNV 分析']],sections:[
    ['VCF 的一行代表什么',`<p>VCF 常见核心列有 <code>CHROM</code>、<code>POS</code>、<code>ID</code>、<code>REF</code>、<code>ALT</code>、<code>QUAL</code>、<code>FILTER</code>、<code>INFO</code>，后面可有样本特定字段。<code>DP</code>、<code>AD</code>等字段的定义应读文件头：标签名相同也要看调用器与版本。</p><p>QUAL 高不代表肿瘤驱动；FILTER=PASS 也不证明变异是体细胞。最好核对匹配正常样本、覆盖、等位基因支持与过滤流程。</p>`,['vcf','gdcVCF','gdcDNA']],
    ['VAF 不是“突变细胞占比”',`<p>若一个位点有 12 个 ALT reads、总覆盖 40，简化 <strong>VAF / variant allele fraction</strong> = 12/40 = 0.30。它表示被读到的等位基因比例，不直接等于 30% 肿瘤细胞携带该变异。</p><p>肿瘤纯度、局部拷贝数、倍性、杂合/纯合、亚克隆结构和比对偏差都会改变 VAF。把 VAF 直接当作细胞比例，会误读克隆演化。</p>`,['gdcVCF','gdcDNA']],
    ['MAF 是注释与汇总层',`<p>GDC 的<strong>MAF / Mutation Annotation Format</strong>把变异调用结果按项目和流程汇总，并带有基因、转录本与预测后果等信息。它更方便做肿瘤队列分析，但并不包含原始读段的全部证据。注释取决于参考基因组和转录本版本。</p><p>同一基因若有多个变异事件，不应未经定义就缩成“基因突变=1”；不同过滤方式会改变事件集合。</p>`,['gdcMAF','gdcVCF','gencode']],
    ['CNV 常是区间，不是单个位点',`<p><strong>Copy-number variation / 拷贝数变化</strong>可在大片基因组区间发生；原始或处理中间结果可能是 segment × sample，随后才汇总到 gene-level。一个基因跨区间边界、肿瘤纯度不同或算法阈值不同，都可能改变“扩增/缺失”的标签。</p><p>和 RNA 关联时要确保 CNV 与 RNA 来自合适的配对样本，并报告把连续拷贝数转成类别的规则。</p>`,['nhCNV','gdcDNA','gdcDoc']]
  ],worked:['解释 VCF 中的 12/40',['假设某样本在该位置有 12 个 ALT reads、28 个 REF reads，总覆盖 40。','VAF=12/40=0.30；这只是读段比例。','若样本混有正常细胞或局部拷贝数改变，携带变异的癌细胞比例不能由 0.30 单独确定。','回看原始覆盖、匹配正常、CNV 与纯度后再讨论克隆性。']],terms:[['VCF','储存基因组变异及其调用信息的格式。','vcf'],['MAF','对体细胞变异进行注释和队列汇总的表格格式。','gdcMAF'],['VAF / 变异等位基因比例','在指定测量下支持 ALT 的读数比例。','gdcVCF']],check:['VAF=0.3 是否说明恰好 30% 的肿瘤细胞有该突变？','不说明。VAF 还受到纯度、拷贝数、倍性、克隆和技术因素影响。']},

  {id:'k06',title:'QC、批次、缺失值与异常样本',subtitle:'建模前先证明数据可用。',intro:'大型公开数据的主要挑战经常不是算法复杂度，而是不同实验流程、样本质量和缺失机制混在一起。质量控制要对应实际测量。',goals:['从样本和特征两层做 QC','识别批次与组别混淆','区分缺失、未检测与真实零值'],prereq:['k01','k04','r03'],flow:[['输入文件','读取与版本校验'],['样本 QC','深度、覆盖、污染等'],['特征 QC','低表达或不可靠区域'],['批次/缺失审计','检查与研究组别关系']],sections:[
    ['每个模态有自己的 QC 指标',`<p>RNA 可检查文库大小、检出基因数和表达分布；单细胞还常看线粒体相关计数比例等，但阈值应按组织、实验与目的决定。DNA 变异需看覆盖、等位基因支持、过滤和正常对照。图像要看焦点、组织覆盖、染色及配准。</p><p>“所有平台统一用一个质量分数”会掩盖具体失败模式。QC 报告要有原始与过滤后样本数以及阈值理由。</p>`,['scanpyQC','gdcVCF','visiumSpatial']],
    ['batch / 批次会与生物组别混在一起',`<p>如果所有肿瘤在实验批次 A、所有正常在批次 B，数据无法仅凭观察分清“疾病差异”与“批次差异”。PCA 图上按批次分群是警示，但不一定说明所有差异都是技术噪声。</p><p>优先在设计阶段让组别分散到批次。后续模型可纳入批次协变量或使用合适校正，但完全混淆的设计无法靠一个函数可靠地恢复生物效应。</p>`,['deseq2','gdcDoc']],
    ['零、NA 和不存在是三种情况',`<p>RNA count=0 表示所用流程未计到读段；NA 表示该值缺失；目标根本不在 Xenium panel 中则是“未测”。它们不应都填成 0。临床表里无随访记录，也不等同于“没有事件”。</p><p>给每个字段建立缺失字典：缺失原因、是否可恢复、是否与组别有关、如何在分析中处理。完整病例筛选可能让病例数和临床组成改变。</p>`,['gdcDictionary','xeniumPanel','gdcDoc']],
    ['异常值先回到样本，而非立刻删除',`<p>离群样本可能来自污染、标签错误、肿瘤异质性或真实罕见生物状态。检查元数据、实验批次、分布与原始文件，再用预先写好的规则决定是否排除。</p><p>记录每个排除动作的原因和对主要结果的敏感性；不能因为一个样本让 p 值不显著就删掉它。</p>`,['gdcRepo','scanpyQC']]
  ],worked:['批次与疾病完全重合的例子',['批次 A：10 位肿瘤；批次 B：10 位正常。','任何表达差异都可能由疾病或批次引起，当前数据无法把两者区分。','理想办法是在设计阶段让每个批次同时包含肿瘤和正常。','若数据已产生，应明确不可识别的限制并寻求独立队列验证。']],terms:[['QC / 质量控制','根据测量机制检查样本和特征是否可信。','scanpyQC'],['Batch effect / 批次效应','处理、仪器或时间等技术因素造成的系统差异。','deseq2'],['Missingness / 缺失机制','某项观测未出现的原因和规律。','gdcDictionary']],check:['Xenium panel 没有 gene X，可以把 X 的表达填为 0 吗？','不能。未测与测了但计数为零在语义上不同。']},

  {id:'k07',title:'单细胞对象：AnnData 与伪重复',subtitle:'X、obs、var 是什么，为什么十万个细胞不是十万个病例。',intro:'单细胞分析经常把矩阵和元数据装进一个对象。理解对象轴、原始与变换后的层，以及细胞嵌套在患者内的结构，才能安全使用 Scanpy 等工具。',goals:['读懂 AnnData 的主要槽位','区分细胞数和供体数','理解 pseudobulk 的患者级思路'],prereq:['d07','k02','k04'],flow:[['X / layers','cells × genes 数值'],['obs','每个细胞的元数据'],['var','每个基因的元数据'],['donor ID','患者级统计单位']],sections:[
    ['AnnData 的矩阵与注释轴',`<p>AnnData 常用 <code>X</code> 存 observations × variables 的主矩阵；<code>obs</code>是一行一个细胞的元数据，<code>var</code>是一行一个基因的注释。<code>layers</code>可保存相同形状的其他数值版本；<code>obsm</code>可保存降维坐标等。</p><p>打开 h5ad 后先打印形状、obs/var 列名、X 是否为整数 count、layers 有什么、细胞 ID 和 donor ID 是否唯一。<code>X</code> 不必然是 raw counts，取决于数据创建者。</p>`,['anndata']],
    ['稀疏矩阵与零的解释',`<p>细胞 × 基因矩阵通常很大而稀疏，可用稀疏存储省内存；把它直接转成 dense 可能耗尽计算资源。大量零值与测量捕获、测序深度和细胞状态有关，不等于基因永久关闭。</p><p>质控时还要看每细胞总 counts、检出基因数与实验特有指标，核对低质量细胞、双细胞和不合适的批次。</p>`,['anndata','scanpyQC']],
    ['pseudobulk 为什么重要',`<p>若 4 位患者各有 5,000 个 T 细胞，比较“患者组别的 T 细胞表达”时独立生物重复主要是 4 位患者。一个常见思路是在每位患者、每种细胞类型内汇总 raw counts，形成<strong>pseudobulk / 伪 bulk</strong>样本，再在供体层比较。</p><p>这种汇总不会凭空产生更多患者，也会受到每位患者细胞数和细胞类型标注误差的影响。细胞级模型也应显式表示供体层级。</p>`,['anndata','deseq2']],
    ['把单细胞标签转移到空间数据',`<p>单细胞参考可帮助解释 Visium bin 或 Xenium 细胞的身份，但参考未必包含肿瘤特有状态。标签是模型推断，不能把 UMAP 上接近或“marker 相似”写成确定细胞系谱。</p><p>保留原始表达、参考版本、被拒绝或低置信度标签及组织形态复核，尤其要警惕不同病例和平台间的 domain shift。</p>`,['cellxgene','visiumMatrix','xeniumOutput']]
  ],worked:['读一个 20,000 × 15,000 的 h5ad',['20,000 是 observations，通常是细胞；15,000 是 variables，通常是基因。','从 obs 找 donor_id、sample_id、batch、cell_type；从 var 找 gene_id、symbol。','比较组别前统计独立 donor 的数量及每位 donor 的细胞数。','确认 X/layers 的单位，再选择合适的 QC 和差异分析。']],terms:[['AnnData / h5ad','结合矩阵及 observation/variable 元数据的常见单细胞格式。','anndata'],['Pseudobulk / 伪 bulk','按供体及细胞类型汇总单细胞读数的分析思路。','deseq2'],['Doublet / 双细胞','一次测量混入两个或多个细胞信号的情形。','scanpyQC']],check:['一组有 50,000 个细胞、另一组有 40,000 个细胞，能因此说两组有 90,000 个独立患者吗？','不能。细胞嵌套在供体内，患者级效应取决于独立供体数。']},

  {id:'k08',title:'空间与影像数据：像素、坐标和分割',subtitle:'矩阵、图像和几何对象必须在同一坐标系。',intro:'空间组学和生物影像通常不是单一矩阵，而是分子、坐标、图像、细胞轮廓和患者元数据的组合。丢掉任何一层，邻域分析就可能失真。',goals:['解释 pixel、µm、bin 与 cell 的关系','识别分割/配准输出与原始信号','按病例处理图像切块'],prereq:['s01','d08','k02'],flow:[['图像','像素和物理尺寸'],['分子/marker','点位或强度'],['几何对象','bin、polygon、ROI'],['样本层','slide、section、patient']],sections:[
    ['像素不自动等于微米',`<p>图像有像素坐标，组织有物理距离。把两细胞质心的像素距离解释成 20 µm，必须知道像素大小及缩放、裁剪和旋转。Visium 还需把 barcode/bin 的位置与显微图像配准；Xenium 的点位要与细胞轮廓对应。</p><p>分析前记录坐标原点、轴方向、单位、图像层级和变换矩阵。不同图像文件即便尺寸相同，也不代表已经配准。</p>`,['visiumSpatial','xeniumOutput','omeTiff']],
    ['segmentation 使“细胞”成为推断对象',`<p>原始显微图的像素和分子点位更接近测量结果；<strong>cell polygon / 细胞轮廓</strong>由算法根据染色、形态或分子分布估计。一个切分错误可能把两个邻近细胞合成一个，改变 cell × gene 或 cell × marker 矩阵。</p><p>保存分割算法、版本、参数和质量示例；关键结果对边界选择做敏感性分析。空间邻近模型的节点，往往是这种估计出的细胞对象。</p>`,['xeniumSeg','codexPaper']],
    ['WSI、OME-TIFF 与 tile',`<p>数字病理全切片图像通常很大，算法切成 tile 处理；显微多通道图可用 OME-TIFF 保存像素和多维元数据。tile 的行数反映切块数量，不是患者数量。切块间还有高度相似的局部纹理。</p><p>训练与测试要按患者、机构或时间等适当层级拆分，再切 tile。记录组织区域、扫描仪、倍率或像素间距，避免模型学到数据来源。</p>`,['omeTiff','tcia','sklearnGroup']],
    ['空间图的边怎样定义',`<p>常见做法把细胞或 bin 当节点，按物理半径、k 近邻或组织接触定义边。但不同密度、组织边界和坏死区会改变邻居数量。把“邻接图”直接叫细胞通信网络过度解释了模型输入。</p><p>比较条件前固定合理的距离尺度，并检查半径变化、边界效应与标签置换背景。<a href="data-lab.html#split">数据练习</a>还会展示为何图像 tile 不能跨患者拆分。</p>`,['visiumSpatial','xeniumSeg','nciTME']]
  ],worked:['从 25 pixels 换算到物理距离',['假设图像元数据给出 0.5 µm/pixel，且没有额外缩放。','两质心相距 25 pixels，则物理距离为 12.5 µm。','如果图像又缩小到原来的 1/2，新的像素比例会改变，不能沿用 0.5。','核对实际图像层级和配准变换后再做邻域统计。']],terms:[['OME-TIFF','包含多维显微图像与 OME 元数据的文件格式。','omeTiff'],['Cell polygon / 细胞轮廓','算法表示一个估计细胞边界的几何区域。','xeniumSeg'],['Registration / 配准','把不同图像或测量坐标映射到同一空间。','visiumSpatial']],check:['两细胞相距 25 pixels，是否可以直接写成 25 µm？','不能。必须知道该图像层的物理像素尺寸和配准/缩放。']},

  {id:'k09',title:'临床表：时间、结局和随访',subtitle:'同一个字段何时可用，会改变预测问题。',intro:'临床数据不是普通标签表。诊断、治疗、复发和随访发生在不同时间；把未来才知道的信息当作基线特征，会让模型看起来很准。',goals:['定义 time zero 与结局','区分事件、删失和缺失','建立有时间语义的特征表'],prereq:['t04','r04','k02'],flow:[['诊断/入组','time zero'],['基线信息','当时可得的特征'],['治疗与随访','随时间变化'],['事件/删失','定义结局与观察窗口']],sections:[
    ['每个预测任务先写 time zero',`<p>“诊断时预测两年死亡”与“治疗后六个月预测复发”是不同任务。前者只能使用诊断时或更早可得的变量；后者的起点和允许特征窗口不同。若治疗反应被错误放进诊断模型输入，就把未来信息传给了算法。</p><p>对每个字段记录采集时间、可用时间和所属病例，时间戳不全时应谨慎说明。</p>`,['gdcDictionary','nciDiagnosis','sklearnLeak']],
    ['event、censoring 和 NA',`<p>随访结束仍未观察到死亡，通常是删失，不等于“患者永远不会死亡”。若连最后随访时间都缺少，则是另一类缺失。分析时分别记录事件状态、事件或最后观察时间、时间单位和删失原因。</p><p>病例可能有多个 follow-up 记录；把它们 join 到一行病例表时，必须定义取最近、首次还是构建时间变化的表，不能让 join 任意复制结局。</p>`,['gdcDictionary','gdcDoc']],
    ['终点定义需要临床上下文',`<p>Overall survival、progression-free survival 等终点记录不同事件；数据门户里的字段也可能因项目、治疗和随访方式而不同。把缺失治疗记录解释为“未治疗”，或把不明死亡原因硬归类，会引入错误标签。</p><p>建立 endpoint dictionary：事件定义、起点、单位、删失和纳排规则。研究结论要对应这个实际可观测的终点。</p>`,['nciDiagnosis','gdcDictionary']],
    ['数据集划分和外部验证',`<p>同一患者的多次随访、扫描或病理切片应留在同一分组；更严格的外部验证可按医院、时间或研究来源划分。随机按记录分组可能让模型记住患者背景。</p><p>评价除判别力外还看校准、各组样本量、事件数与缺失。一个在训练队列上显著的组学特征，不保证对新患者有预测价值。</p>`,['sklearnGroup','sklearnLeak','gdcDoc']]
  ],worked:['找出“诊断时预测”中的泄漏变量',['time zero 定义为首次诊断日。','病理分期若当日已确定，可能是候选基线特征；需核对真实记录时间。','六个月后治疗反应与一年后复发状态都是未来信息，不能放在基线输入。','若预测任务改为治疗后六个月，需重新定义起点、入组人群和结果窗口。']],terms:[['Time zero / 时间零点','预测或生存分析开始的明确定义时点。','nciDiagnosis'],['Censoring / 删失','到最后观察时仍未记录目标事件的情形。','gdcDoc'],['Endpoint / 终点','研究预先定义并测量的结局。','gdcDictionary']],check:['诊断时预测复发的模型能使用“六个月治疗反应”作输入吗？','不能；该字段在预测时尚不可得，属于未来信息泄漏。']},

  {id:'k10',title:'从数据到模型：拆分、验证与复现',subtitle:'先建立可信任务，再选算法。',intro:'深度学习、图模型和多模态融合都可以用于计算生物学，但表现首先受标签、单位、拆分和外部验证约束。复杂模型不能补救错误数据。',goals:['定义训练样本与独立测试单位','理解组别交叉验证和预处理泄漏','按证据层报告多模态结果'],prereq:['k02','k04','k06','k08','k09'],flow:[['任务与标签','谁、何时、预测什么'],['数据切分','患者/机构层独立'],['训练流程','训练内拟合 QC/特征/标准化'],['评估与复现','外部队列 + provenance']],sections:[
    ['预测任务与机制问题分开写',`<p>“根据 WSI 与 RNA 预测两年结局”是预测任务；“某 enhancer 通过剪接改变免疫浸润”是机制假设。前者需要锁定标签、可用时间、拆分与泛化指标；后者需要配对证据、替代解释和功能实验。模型准确并不自动给出因果机制。</p><p>先写清样本单位：一个患者、一块切片、一个细胞还是一个时间窗口。若结果是患者级，报告和拆分也要回到患者级。</p>`,['sklearnLeak','gdcDictionary','encodeScreen']],
    ['split 在模型之前',`<p>患者有多张 WSI、许多 tile、多个组学文件时，先按患者分训练与测试，再在各组内部生成 tile 或聚合特征。<strong>GroupKFold</strong>可让同一组不跨折，但它不保证外部医院或未来时间泛化；这些需要另设验证。</p><p>特征选择、缺失填补、批次校正、缩放参数和超参数搜索都应只在训练折内拟合。让测试数据参与任一步，就污染了性能估计。<a href="data-lab.html#split">在练习页亲手比较 tile 拆分与患者拆分</a>。</p>`,['sklearnGroup','sklearnLeak']],
    ['多模态融合先看配对与缺失',`<p>early fusion 把对齐的特征共同输入模型；late fusion 先训练模态内模型再合并预测。无论哪种，病例、时间、组织位置是否真的配对都比网络结构更关键。只选“所有模态齐全”病例，也可能造成偏差。</p><p>应报告单模态基线、缺失比例、最终病例数、融合带来的增益及不确定性。路径富集与网络图适合生成解释假设，但其背景基因集、注释版本和多重检验也要透明。</p>`,['gdcDoc','reactome','deseq2']],
    ['建立别人能复核的交付物',`<p>一个可信项目包含样本 manifest、数据字典、处理流程和参数、参考 build/基因注释、代码环境、随机种子、训练/测试分组 ID、QC 图和失败记录。若数据访问受控，公开代码和汇总结果也应遵守其权限规则。</p><p>论文结论按“直接测量”“算法推断”“统计关联”“功能验证”分层表达；这比只发布最高的 AUROC 更能帮助下一个研究者判断结果可否复用。</p>`,['gdcDoc','sklearnLeak','gdcDictionary']]
  ],worked:['设计一个有空间图像和 RNA 的临床模型',['标签：诊断时预测两年内事件；先定义 time zero 与删失。','单位：病例；同一病例的所有切片、tile 和 RNA 文件都进同一拆分。','在训练集内做图像特征、RNA 过滤和标准化，并保留单模态基线。','报告独立测试病例数、事件数、校准、错误分析和数据版本。']],terms:[['GroupKFold','让同一 group 不同时进入训练和验证折的拆分方法。','sklearnGroup'],['Data leakage / 数据泄漏','训练过程获得本不该可用的测试或未来信息。','sklearnLeak'],['Provenance / 数据来源记录','记录数据、处理和模型生成过程的可追溯信息。','gdcDictionary']],check:['训练/测试按 tile 随机切分，但同一患者出现在两组，能称为患者级独立验证吗？','不能。模型可能利用患者、染色和扫描的共享特征；需要按患者分组。']}
]});
